### ISSUE TITLE
Lib autoloader fails with custom module

### ISSUE THREAD

**Issue by TesseraSkye** [JacquesLucke/animation_nodes#1006]
Upon adding a custom library to animation_nodes\libs\, animation nodes's auto-loader throws an exception on a submodule of that module, claiming that the parent module couldn't be imported. This obviously is not true,  as the submodule itself loaded, which would not have occurred if the parent was unable to load. 
This may be tangentially related to the some of the other issues with the auto-loader, which appears to attempt an execution of every section of every lib module before import, which is a problem for modules that have unused components that have not been acquired.

**Comment by JacquesLucke** [comment]
Please be a bit more specific about what you are doing and what the problem is.

**Comment by TesseraSkye** [comment]
I'm implementing an OSC module with pythonosc. I place the pythonosc module in the libs folder and compile, copying into my addon directory. Upon enabling Animation Nodes, I get the attached error:

![importerror](https://user-images.githubusercontent.com/39166259/51350271-04705300-1a65-11e9-9dae-8ffeccf7a46b.png)

The call to pythonosc is to the previous level. I've used this module extensively and I know it works as I put it in.

**Comment by JacquesLucke** [comment]
I see, the problem is that the module expects to be in the "global module namespace".
You'd have to create a new subfolder that contains **no** `__init__.py`. Then put the `pythonosc` module inside that (so that e.g. a file `animation_nodes/external_deps/pythonosc/__init__.py` exists).
Inside of some AN module, you have to add that `external_deps` folder to `sys.path`.
Then you should be able to do `import pythonosc`.

Does that make sense?
