### ISSUE TITLE
Very lax approach to compatibility between versions.

### ISSUE THREAD

**Issue by sqward** [JacquesLucke/animation_nodes#1211]
Hi there. I really love Animation Nodes. It changed the way I work with Blender, but... Every time there's new version all my projects are broken, nodes go missing, etc. This is a real PITA for me. Is it only me who feels that pain? I don't really mean to rant. Maybe nobody pointed out this problem before?

**Comment by OmarEmaraDev** [comment]
Hi, you are correct. Unfortunately, Animation Nodes does not try to be backward compatible. I don't think we will ever care about backward compatibility because it hinders development. So, you will either have to update your node trees or stay on old versions for that project.

**Comment by sqward** [comment]
Really, already closed? This is unhelpful attitude. 

Can you point out how this hinders development? To me it's saying that "we, developers, care about out own convenience more then our users" - kind of a slap in the face...

**Comment by OmarEmaraDev** [comment]
Sorry, I though it was just a question, I didn't realize you wanted to discuss this further.

It is not that we want to cause inconvenience to users. It is just that we want to direct the efforts into improving Animation Nodes. In most cases, breakage is very simple, and can be fixed with minimal efforts, so I think it is acceptable.

**Comment by sqward** [comment]
Well, you see it as acceptable, but users may have a different opinion. Say you have 50 projects and you want to move to Blender 2.8. Load every single one, figure out what's broken, fix it... That's easily 10 minutes per project. Maybe faster if you spot the breakage pattern...

This not only causes annoyance to the user. It also creates perception that Blender ecosystem is not professional environment. I get it, this is not a paid plugin, but Blender itself is free and I can't remember a situation when older project wouldn't load correctly into a new version.

How costly it would be (in terms of precious dev time) to move deprecated nodes to a "deprecated" folder in the source tree and only allow instantiation when project is loaded and only allow the user to instantiate newer nodes explicitly? Ok, I get that there's more nuance to it, but it should work in general.

**Comment by OmarEmaraDev** [comment]
Yes, I feel you. But handling backward compatibility is not as easy as you paint it. Sometimes the breaking happens because of architectural changes or node changes, this would require writing lots of code to handle the compatibility. I worked on Blender before and backward compatibility was a pain, and it did hinder development. Plus we can't just leave dead code every time we make a change.

I didn't make this decision, but I support it, even though we know it is not ideal.
So, as I said, just update your node trees or use older versions. Terminal output and CHANGELOG should help you update your node trees pretty fast.
