### ISSUE TITLE
Render does not match what's in the view and/or scene in camera view

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1258]
The render does not match what's in the view and/or scene in the camera view
I tired 2.1.4 and [2.1.5]  (Build 07-12-2019). (https://blender.community/c/graphicall/Wdbbbc/) https://blender.community/c/graphicall/Wdbbbc/ and the issue still pops up.

**When I use the command below the render works correctly.**
/snap/bin/blender -b /home/user1/image_rot_3.blend -E CYCLES -o /tmp/frame_cycles_##### -f 130; 

![frame_cycles_00193_correct](https://user-images.githubusercontent.com/28985314/71217644-74e2ae00-228c-11ea-84e3-1819d572a3c1.png)

**When I try and render from the Blender Gui directly (I have to enable Render - Lock Interface (enabled) to prevent crashes)**

The image I get is completely different and incorrect.  From what I can tell the issue can be narrowed down somewhere in the **Animation Nodes Script Node** (since this controls this value).  Why the render works from the command line and not directly in Blender is strange.
 
![frame_cycles_00193_incorrect](https://user-images.githubusercontent.com/28985314/71217751-cbe88300-228c-11ea-856c-b00e0c6885b7.png)

I'm using Ubuntu 18.04 64bit Linux
Blender 2.81
Tried Animation Nodes 2.1.4 and 2.1.5

**Comment by OmarEmaraDev** [comment]
I think this is related to #1200 , you will have to render from the CLI for now. It would be nice if you can share a test blend file so that we can confirm this.

**Comment by stillpointx** [comment]
I think this is a little different I made an animation that shows the issue and here's a blend file that produces the issue.  **Notice how the rendered image does not match the viewport image**  I've also attached the blend file.


![an_render_doesnt_match](https://user-images.githubusercontent.com/28985314/71268714-92ab2400-231b-11ea-99ca-a9782f334e1e.gif)

I'm using Blender 2.81 Ubuntu 18.04 64bit Linux
Animation Nodes 2.1.5

[an_script_question.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/3989162/an_script_question.blend.zip)

**Comment by OmarEmaraDev** [comment]
Ok, I can replicate that. I will look into it this Sunday.

**Comment by stillpointx** [comment]
Thanks!

**Comment by 3DSinghVFX** [comment]
In AN, if you append an element to an input list (WHICH IS NOT REASSIGNED) in each iteration then the list shows all the elements,
![screen](https://user-images.githubusercontent.com/30294746/71277685-92427580-237b-11ea-883e-00f1440d0f7c.png)
 
Now, if you enable the Copy option of Loop Node in the N-panel, you will see there is only one (zero for Output option) element in the list, which is correct because we have not stored the list on each iteration,
![screen1](https://user-images.githubusercontent.com/30294746/71277915-2ca2b900-237c-11ea-9883-44d840e46cb3.png)

In @stillpointx example, in each iteration, a point is appended to a spline but the spline is not stored or reassigned in the loop node. So, I have modified the node-tree, and now the rendered image is the same as in the preview :)
![an_script_question_edit](https://user-images.githubusercontent.com/30294746/71278531-e0f10f00-237d-11ea-82ea-d077a0efcf86.png)

[an_script_question_edit.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/3989503/an_script_question_edit.blend.zip)

**Comment by OmarEmaraDev** [comment]
Thanks for looking into this Kuldeep!
@stillpointx did this resolve your issue?

**Comment by stillpointx** [comment]
Thanks! Yes it did :-)
