### ISSUE TITLE
Particle system bug with rotations

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#1267]
When rotations are used in a particle system:
![particle_bug_01](https://user-images.githubusercontent.com/738650/71518235-c2bd6e80-28a9-11ea-9669-3e7bfd1a07d8.png)

And the number of particles exceeds the length of the list:
![particle_bug_02](https://user-images.githubusercontent.com/738650/71518237-c650f580-28a9-11ea-84fd-ad7d034e025a.png)

Then there is an exception:
![particle_bug_03](https://user-images.githubusercontent.com/738650/71518242-ca7d1300-28a9-11ea-9f91-0d95c953ca52.png)

This is when using locations, for the rotations it does not matter.

(Blender 2.8)

**Comment by OmarEmaraDev** [comment]
The Particles Output node is not part of official Animation Nodes. You should report this to the creator of the node. Perhaps @3DSinghVFX?

**Comment by 3DSinghVFX** [comment]
@clankill3r This is related to Extra Nodes, so please report the issue here: https://github.com/3DSinghVFX/animation_nodes/issues

Btw, this is not an issue. The length of the input list (location, velocities, etc) should be equal to the total number of particles. I have also made video tutorials for Particle Output node: https://www.youtube.com/watch?v=8pvX2_ZH1l0
