### ISSUE TITLE
Proposal: Informative "noodles"

### ISSUE THREAD

**Issue by grinvaldsjanis** [JacquesLucke/animation_nodes#1272]
Sometimes, when tree grows big, it could be helpful
- to find out where the noodle comes from, popup some info about socket and node of departure;
- highlight noodle itself when hovering or selecting it.
- if selected, there could be some left mouse options related to connection; place reroute node, erase noodle, place viewer of some type, maybe noodle could be "listened" on hover popup infobox
- noodles could have an indication if something or nothing is "transferred" similar to UE4 blueprints
- maybe noodles can have colours as well. Esp. if You have some important data connected, you might want to highlight that.

**Comment by Gerstmann-Bradley** [comment]
non-developer, just to give some responses to these proposals.
1. choose a node and hit E, there is a manual where you can choose dependency (where noodles comes from).
2. It's already doing so, and personally I think it's obvious enough.
3.  **This seems more of a blender issue**. There is no reason for AN to do this work specifically. Also, just to mention that once a noodle has been made, you can "**hold shift + left mouse botton**" to cut that noodle to add a reroute. Also "**hold ctrl + left mouse botton**" to cut/erase that noodle as well.
short cut key for viewer requires "**selecting node and hitting W**". or you just add a reroute and connect that to viewer. It's not hard.
4.  (Haven't used UE4 would you explain more?)

-------------------------------------------
5. This reminds me about a discussion people did on "particle nodes UI" for new node-based particle system: https://devtalk.blender.org/t/particle-nodes-ui/8808/186
I have seen illustration of people's proposal. I am not sure if this is done by photoshop or add-on, but AFAIK this is not something that I can do in function branch.
![example](https://user-images.githubusercontent.com/55994236/71563578-eaeece00-2a5f-11ea-968e-f42bff5f6acd.png)

I am not sure the exact thoughts Jacques about this. But I think this is a question beyond the scope of animation nodes itself. **Maybe you should rather propose this in blender forum**.
Also, **another possibility is to color the frame instead of noodles, and you can already do this in blender**. Animation node tree can really grow very huge, I think it will be too messy to have noodles colored. **Personally speaking, I vote against this** currently, and that's why the second thought which is already available turns to be important here:
![example2](https://user-images.githubusercontent.com/55994236/71563594-36a17780-2a60-11ea-9734-14e327a3a2fc.png)
This is also something that I saw on particle node UI. and certainly you can achieve this in current blender already.

**Comment by grinvaldsjanis** [comment]
In terms of a tree growing big. And this could be just 1/4 of finished project :)
BTW, I would like to be able to navigate easily from Invoke subprogram node to subprogram. As You may understand, it may take a lot of time to travel around the map of trees.

![image](https://user-images.githubusercontent.com/6594177/71563818-a9c9de80-2a9e-11ea-93dc-2979cb00ec49.png)

**Comment by Gerstmann-Bradley** [comment]
> In terms of a tree growing big. And this could be just 1/4 of finished project :)
> BTW, I would like to be able to navigate easily from Invoke subprogram node to subprogram. As You may understand, it may take a lot of time to travel around the map of trees.
> 
> ![image](https://user-images.githubusercontent.com/6594177/71563818-a9c9de80-2a9e-11ea-93dc-2979cb00ec49.png)

It happens to me as well, but you didn't respond to my responses. I think many of your proposals should be more general drawn to blender instead of AN. The others almost have ways to solve that already as I have mentioned. Also looking at your node tree, I don't see coloring noddles will be helpful, won't that just hurting eyes when multiple colors mix.

----------------------
in terms of second proposal, I am not sure I understand correctly, but I was thinking to easily take me from subprogram to the main program, just like hitting tab can take you from node group to the group inside. This, however, is partially doable already in AN.

I suppose you just need to take the main program to a different tree, instead of making all of your stuff to a single tree.

**Comment by OmarEmaraDev** [comment]
I mostly agree with @Gerstmann-Bradley. Personally, I don't think this should be implemented at the Animation Nodes level. Also, most of what you are asking is provided by Animation Nodes already. Take a look at the Interface Guide in the documentation:

https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/getting_started/interface.html#shortcuts

**Comment by grinvaldsjanis** [comment]
The idea for colouring nodes came after I use several important parameters in many nodes, and I want to have them emphasized at least temporarily - if I decide that something is too colourful, I can then fix it. But when I have a real spaghetti of noodles, it might take a lot of time to find that proper noodle when I need it.

If this is not related to AN then ok.

That would be my answer.
------------------------------------------

Still a question for consideration: would noodles show some data transferring, to see without using a  viewer, where something is missing. Sometimes a lot of time is lost when You try to find out that something is not connected.

**Comment by OmarEmaraDev** [comment]
I am not sure what you mean by "something is not connected" or "show some data transferring". Something is always being transferred along links, and if something that is needed and is not connected or have a wrong value, the node will raise an exception, which is pretty clear.

**Comment by OmarEmaraDev** [comment]
Feel free to reopen if you want to discuss this further.
