### ISSUE TITLE
Cmd line vertex col not applied

### ISSUE THREAD

**Issue by Bambushacker** [JacquesLucke/animation_nodes#1296]
The new build is much more stable and I am able to render in the gui without crashes. :)
While rendering on cmd line the vertex col sometimes doesn't work.

It looks like it can't refresh the vertex col and is just black, especially when random frame ranges are used. The vertex col is only applied 80% of the time, but completely random.

I'm not sure if this is reproducible. I'm on win btw.

Example file:
https://drive.google.com/file/d/1FBotdlQPuY4SXMu_keSyWyZmAape6avo/view

**Comment by OmarEmaraDev** [comment]
Hi, great to hear the new builds are more stable!

I can reproduce the issue. But it is not exactly a bug. Take a look at the following part of the node tree:

![20200128-161242](https://user-images.githubusercontent.com/25300994/73271226-e1848d00-41e8-11ea-8f8a-ae4f0dda883d.png)

We have two "parallel" branches of nodes starting from the *Mesh Object Input node*, that is, they don't depend on each other. There is no indication which of the branches should be executed first. So Animation Nodes makes an arbitrary decision, it chooses any of them. Apparently, AN chooses the upper branch 80% of the times.

The other 20% of the times, AN executes the lower branch first. The problem is, there is no vertex color layer (Because the Insert Vertex Color node is in the other branch), so the *Set Vertex Color* nodes does nothing. Then the upper branch is executed, a vertex color is inserted and set to black then the mesh is output. Hence why you get Black 20% of the times.

How to fix this? Well, the *Insert Vertex Color Layer* node already allow you to set the color, so why try to set it again using the *Set Vertex Color* node. You node tree should be like this:

![20200128-162334](https://user-images.githubusercontent.com/25300994/73272048-67ed9e80-41ea-11ea-9d30-9e162a99aaed.png)

Everything is sequential, there is no ambiguity. Plus you do less work, so it is faster.

**Comment by OmarEmaraDev** [comment]
You also have multiple *Mesh Object Output* nodes. You should only have one at the end. To get the vertices and polygons of a mesh, just use the *Mesh Info* node. So your node tree can be like this:

![20200128-162916](https://user-images.githubusercontent.com/25300994/73272588-4a6d0480-41eb-11ea-98cf-45493a1d3cfd.png)

Also, you can use the Vertices mode of the Vertex Color nodes to set the colors, allowing you skip separating the polygons:

![20200128-163240](https://user-images.githubusercontent.com/25300994/73272802-a46dca00-41eb-11ea-8c8f-228a446ef60d.png)

**Comment by Bambushacker** [comment]
Ok, you are awesome! Thank you for your time and this fast and easy explanation :)
