### ISSUE TITLE
Time Info node uses the wrong scene on creation

### ISSUE THREAD

**Issue by liquid600pgm** [JacquesLucke/animation_nodes#1370]
![image](https://user-images.githubusercontent.com/16415678/77214398-47b5ce00-6b0f-11ea-9fb1-8fb7b918cf3d.png)

**Comment by liquid600pgm** [comment]
After some investigation, it seems like the scene used in the node was a different scene from the current one. I suppose this is a bug? Time Info should always use the *currently selected* scene, as far as common sense goes.

**Comment by Gerstmann-Bradley** [comment]
> After some investigation, it seems like the scene used in the node was a different scene from the current one. I suppose this is a bug? Time Info should always use the _currently selected_ scene, as far as common sense goes.

disclaimer: I am not a developer but just an AN-user.
The node tree refers to only one scene instead of multiple. So the "time info" node within that node tree also refers to "the scene that node tree refers to".
Just change scene and execute node tree again then it will solve the problem; it works on my side.
Thus, I suppose this isn't a bug. The issue is that if your node tree doesn't refers to the scene you are working right now, I think it won't work anyway. So just fixing "time info" node won't be meaningful imo.

![scene](https://user-images.githubusercontent.com/55994236/77215310-d0ba0e80-6ae9-11ea-82a7-f082826d28b9.png)

**Comment by OmarEmaraDev** [comment]
The node use the Node Tree scene by default. (The target scene is a hidden input). You may change the Node Tree scene in the *Animation Node Tree* panel or disable global selection in the socket and change the scene as needed.

**Comment by liquid600pgm** [comment]
Oh, right. I thought that Animation Node Trees are global, but thinking about it a second time it makes sense. Time Info *can* return the start and end frame, and also the framerate after all.
Thanks for your help.
