### ISSUE TITLE
How to import external python modules? 

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1384]
How can i import external python modules like scipy inside animation nodes?

**Comment by OmarEmaraDev** [comment]
You mean globally in the node tree? What difficulty are you having?

**Comment by harisreedhar** [comment]
![scpiyyyy](https://user-images.githubusercontent.com/46858047/77843514-958b9f80-71bb-11ea-8a0f-9a31a3c528dc.PNG)
I mean how to specify it's correct path or a way to include module in AN library

**Comment by OmarEmaraDev** [comment]
You can import an external module like any other module. The module have to be loadable of course. The installation procedure for modules differ, it can be installed using pip, using the package manager, or manually. So I think the question you should be asking is how to install an external python module in Blender. I can't tell you how exactly because I am on Linux and use the system python instead of Blender's, but there should be plenty of resources on how to do this online.

**Comment by harisreedhar** [comment]
So i have to change blender's python into system python. Thanks

**Comment by OmarEmaraDev** [comment]
Not necessary, this is just how I like it. You could use Blender's python as well.
