### ISSUE TITLE
Use Modifier option does work when Object is disabled for rendering

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1386]
Hi :)
If I disable the object for rendering then _Use Modifier_ option of the _Mesh Object Input_ node does not give the evaluated mesh in rendering, however it does gives in the viewport.

**Viewport:**
![Screenshot from 2020-03-29 13-57-21](https://user-images.githubusercontent.com/30294746/77844565-53fff200-71c5-11ea-85ea-30403b03616e.png)

**Rendered:**
![Screenshot from 2020-03-29 13-57-42](https://user-images.githubusercontent.com/30294746/77844573-5b270000-71c5-11ea-8ab5-2b3c57152f2a.png)

Blend File: 
[Issue.zip](https://github.com/JacquesLucke/animation_nodes/files/4398465/Issue.zip)

**Comment by Gerstmann-Bradley** [comment]
I think this is what I have reported in #1318, Omar states it's a feature in Blender. and It does make sense that we may not want blender to read modifier when it's hidden.
The issue is that "disable the viewport" (screen icon) will cause the issue in rendering viewport as well.
Currently I mostly just "hide the viewport" and render in viewport. There are also other options, but they are more complicate workaround and I may not discuss that for now.

**Comment by 3DSinghVFX** [comment]
Thanks for the information. 
That what I'm doing right now, Disable the _Use World Space_ -> apply the scale -> move the object out of the camera view.
