### ISSUE TITLE
Object transform Input not updating when using rigidbodies

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1393]
![translationbug](https://user-images.githubusercontent.com/46858047/79107370-e097dc00-7d91-11ea-81de-02f0dd6977aa.gif)

**Comment by Gerstmann-Bradley** [comment]
I think it's because physics is not updating transform anyway in blender.
Technically should use "object matrix input" instead. You can decompose it for location.

**Comment by harisreedhar** [comment]
So it is problem on blender side?

**Comment by Gerstmann-Bradley** [comment]
> So the problem is on blender side?

I don't know if I should call it a "problem"...but at some point I would say "yes"?
But it may make sense why physics is not updating transform data.
Imagine if I were to animate its transform property before triggering the physics, and its transform data were to be changed due to physics afterwards, how will the graph editor looks like? It will also be weird if such information shows on transform but not on graph editor?
These are just personal thoughts, I don't know what maybe a better solution/proposal to this.

**Comment by harisreedhar** [comment]
Thanks

**Comment by OmarEmaraDev** [comment]
Constraints, rigid bodies, and parenting act as modifiers on the object transforms. The object location is the actual location of the object, the object transform is the computed location after applying all constraints, simulations, and parenting. So this is the expected behavior as far as I know.
