### ISSUE TITLE
"Compare" node only output one boolean while inputing a list of values

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1399]
1. It gives an illusion that "Compare node" can compare multiple values.
But its output is limited to a single value regardlessly.
I have to make a loop for that node to get multiple output.
Another issue is that this node very hard to get a subprogram preset.
because I can't get so many options easily through the subprogram.
I hope this can be fixed in actual AN.

2. I also have another proposal.
If I input a list to compare node, it will convert the second socket to a "list input" as well.
But this may not be what I want.
Many times, I may only want to compare multiple values to a single value.
But if the second socket has to be switched to a list input automatically, each time I need to add an extra input node (likely a create list node, while I also need to turn off the second socket which presents as default), I think it rather makes life worse in such a case.
I have seen examples like "float math" node,
even if I input multiple values to socket A, the socket B will be kept as a readily editable socket for a single value.
Furthermore, B can be converted to a list value when I input a list.
I hope this turns to be the behavior of compare node as well.

**Comment by OmarEmaraDev** [comment]
I agree. This is one of the most annoying things about this node.

**Comment by JacquesLucke** [comment]
I'm fine with adding more operation modes to this node.

**Comment by OmarEmaraDev** [comment]
I opted for adding a new node for numbers specifically in 7b80edc. Aside from the technical difficulties, there are some design issue with the Compare node including:

- `<`, `>`, `<=`, and `>=` only works for numbers.
- `Is` only works for generic sockets, since Animation Nodes' copying mechanism makes this nearly useless for other types.
- `is None` only works for generic sockets, since most of the non primitive types usually return empty objects instead of None.

That's why I though type specific comparisons are good enough solution.
