### ISSUE TITLE
What is the difference between a[index] and a.data[index] in cython?

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1424]

**Comment by OmarEmaraDev** [comment]
Lists have an underlying contiguous array, its elements can be accessed using `a.data[index]` with no overhead, this can only be done in Cython, not python. On the other hand, `a[index]` is a wrapper around the aforementioned method but with additional index bound checking, Cython to python type conversion and a general python overhead in order to use it from Python code. As you might guess, it is significantly slower.

So in general, if you are in Cython code, use `a.data[index]`. If you are Python code, use `a[index]`.

**Comment by harisreedhar** [comment]
Thanks, One more thing. Is there any issue when using `-ve` index values on `a.data[index]`. when i use -ve values blender closes.

**Comment by OmarEmaraDev** [comment]
C doesn't support python indexing you are used to, if you want to index from the end, you will have to do `a.data[a.length - index]`.

**Comment by harisreedhar** [comment]
Ok Thanks Omar😊
