### ISSUE TITLE
add cuteness to the tree (my node proposal :D +viewers, reroute, frames and socket tricks)

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#145]
There are some nodes I tried to make (really!) and some tricks I was looking for. 

1. So far I managed to successfully do only on one, with a second variation. Enough to open 2 sides of discussion, plus the debug node / viewer in itself

**1.1 mini debug and nano debug nodes**
I made 2 variations of debug node to better fit my usage. Used it for a while, no change but in layout:

![mini and nano debug](https://cloud.githubusercontent.com/assets/11709974/7803262/70bf70a4-0353-11e5-84f7-1ee5f426b8b0.png)

on the original
- I hate that I always hit the print check when I actually wanna drag the node
and I find it too big for only viewing purposes with print button
- I'd like to see the value in the most compact minimized (hide) state
- I'd like to have wider than default width for some values

thus
- I remove the print button, move on the right panel
- I make the label show the value if no custom label is typed
- I change the default to some 640 width
(+I would have made it wrap the text for some lists, but it's too much)

bonus extra trick is that in those times when debugs freeze and not update (you know..) this one makes it obvious by changing back the label to bl_label. so at least you can see there's an issue. I guess It's about "if not input" that makes it work immediately and not on mouse up, but may not be cool in other respect. Doh, I don't think I have to explain to you any of that...

**1.2 The nano debug variation** has an extra trick (that is meant to open a second whole discussion here):
- in the right panel I place a check that hides the link (noodle) on th input. So you end up with a little node with no apparent sockets that updates and I usually place very close to the value that it shows
+ it always shows the sock if no link is connected, so that you see

here the blend with codes inside:
https://drive.google.com/file/d/0BzzAoBwXO8dsSWJSZ3VfeWJBLUU/view?usp=sharing

   I'd like to know your thoughts on this. 
   Do you think such features can be included? :D (my baby, my first node...!)

-----

*And now the 2 topics, Values in Labels and Link hiding (remote nodes)*
**2. on the labels** 
**2.1** I tried to show the value in **label for other nodes**, but with no success (no wonder)
I was looking for a convert node, that would also present the value in the label header. Actually a reroute like behavior would be optimal. But did not made it even with float, integer or text input :(

That would be interesting if just minimize (hide) respective nodes, and still see something. 

**2.2** as an extra trick, for allowing to minimize and still see whats there:
**math nodes** could have operation in label (not made it, of course :( )
A+B, A-B, sinA etc   

**2.3** another trick with labels and values would be to have :
- **reroute** node showing the value in the label, usefull for seeing along the noodles what happens, and very descreete label shown directly on the background
- a frame to show the value of it's child, or a certain child , useful cause the font can be bigger so is visible when zoom out. This is a more complicated design logic and may be flawed easely...
But there are no specific AN reroute and frame, so I did not manage to try anything without a template or so (great excuse!)

blend script mockup animation nodes reroute and frame, functional 
https://drive.google.com/file/d/0BzzAoBwXO8dsVmNBRFI4eHpzWDA/view?usp=sharing

Seeing what you did with the sockets in a general (not only AN) way, made me think that this could be a more general prop panel thing, showing the value in the label. Or maybe not.

however, I really like the reroute discrete label, the rest may be too much

**3.  Remote connections, like the hide noodle**

There are some attempts to this afaiks:
-here is a proposal that hides the links on some reroutes. well, I find that rather confusing for reroutes, but the "tele" or "buss" node (as they call it ) has basically this idea of a remote hidden connection, some suggestions being for stronger visual indications https://developer.blender.org/T33627
-sverchock does this with the wifi nodes, but they actually set a variable, that you can pick on the other end from a drop down and such

my idea is simpler:
**This is just a visual trick, like I did with nano debug. No complications,  just enable or not the respective input socket links!** 
(Besides the nano Debug I tried a convert node, to no avail. At least I got a cute name, "Remote connect")

*As design*
- I would use a convert node and *allow hiding the input sock* just like the nano debug + show if no connection. 
Maybe a dedicated "remote connection" node would do .. (should work rather as reroute, I don't see a more appropriate one)  
- I *only allow hiding the input*. the receiver should be the one to establish this, while the emitter may have n links and not all should hide
- maybe for the output socks, in the emitter, we could have a 1 hit update like button to just  "show all connections, for receivers" that will just switch on respective links when confused

-I would show the value in the node or in the label too, at least to see if something there (miniRemote...)

   I'd very much like to know your thoughts on these remote and label nodes.
   Does any of this make sense to you?

-----

*ps: I just realized I'm posting blends with a changed debug node in it. No data loss, just a debug, but may be confusing. Also, you already messing with sockets show/hide, manage and conversions so I decided not to wait.*
Now that I got that out, I'll keep myself from such long comments :)

*as for the title, Christmas is far, but cuteness should be in the tree.*

**Comment by JacquesLucke** [comment]
I only read the first few sentences for now, because I will got to bed now :D

I also worked on the debug node today:
![debug node](https://cloud.githubusercontent.com/assets/5881326/7803478/1701b5d8-0351-11e5-89ed-4d3a3951c0cf.PNG)


I will read the rest tomorrow. good night :)

**Comment by og76** [comment]
you had to spoil it for me! you just had to be 1 day ahead!  I thought I'll have my 5 min of glory. :)

ok. besides the debug that is a specific case, there are the 2 subjects, **label** and **remote link**. In the debug they are more of a demo.

**Comment by JacquesLucke** [comment]
Haha nevertheless it's very good that you start writing/changing nodes! :D 

showing some more information in a label or in a frame sounds like a good idea :)

I'm not sure about remote links. Invisible links can be a bit problematic, don't you think so?

**Comment by og76** [comment]
Remote? hmm. Depending on use case
* I used it with debug cause I place a lot of debugs just above the math nodes to see the result, and then I know what that is without an extra twisted noodle that I really don't like. 

I see those debug viewers as not part of the tree so I don't like having more links (or at all) distracting me from the normal connection. I also use darker colors on debugs, to fade them so I see better when I zoom out. Maybe same would work for links, but that is not possible I think.

* Other possible use is when I have one of those very big trees where I connect 2 nodes from the beginning to the end and then I use reroutes and make a big wire around that noodle soup. Or when I have some long wires that kinda overlap with an angle, so that you don't see clear. 

Plus in these cases I end up with more noodles instead of clearing out and I have the impression the ui has a performance issue in itself (see, I already talk about optimization, you could think I'm programer or so..)


Unfortunately I was unable to practically experiment with it. So I'm speculating. Tell me how to work with that inline execution and I'll crack a convert node. Or I should make a script to mockup like I did with frames and reroutes.

+ I see it as a specific node and I keep thinking that if u use it you know what you do. 
+ you can always toggle to see a bit  (aha, there it was)
+ I keep thinking about some appropriate visual indicators, same color? (as source) some extra label thing? They use strong colors in sverchok for all nodes and the guys in blender dev were talking about the need of strong visuals too.

**Comment by og76** [comment]
I forgot to say, I should have put it on the forum when I first said so, I would have had my glory. :( 

Seriously, on the label when minimized (hide, H) , there is also a width of the minimized (hidden) state. I took that out cause there is no default value, at a certain point I made it work with same as expanded, but it was too unstable. That in case a big label is there ...


I have more ideas on such,  but the effort just to experiment is not really worth it. Like having a button in propr that "draw grase pencil to connected" (temp or not) or "highlight the branch" (temp change of color for all the up/down nodes up to a certain kind/ instead of frames)
Or showing something in the background. Values? but the actual 3d would be so cool, like compositor. They actually just  implemented that for graph editor ...

Don't get me started, some lists with sort, min, max, avg, value are more important ...

**Comment by JacquesLucke** [comment]
uff thats too much for now. I will finish the spline stuff etc and then come back to all that here. I cannot do everything at once :D
But I'm pretty sure that some of the suggestions you made here will make it into master soon or later

**Comment by og76** [comment]
OK. I guess the debug node is already there, mostly. Well maybe with a label ...would be perfect :)
The rest is a discussion.

**Comment by og76** [comment]
I've tested the new debug. Ok, yours is longer than mine. (but mine has a label..)

**Comment by JacquesLucke** [comment]
yes the label is nice. The debug node can become way smaller and cleaner with this :))

**Comment by og76** [comment]
I'll put that into documentation: 
"Debug node, size does matter..."

**Comment by og76** [comment]
Update:
I managed to further crack some nodes, but still not to the extent I need. However:
1. I think the debug now is good for now. I cannot say if it's worth the time now to look into the label etc. 

fwiw Here's the new mini Debug, the new debug, but with label and link hide
https://drive.google.com/file/d/0BzzAoBwXO8dsRkJrbDdkVlFzeGM/view?usp=sharing

2. I managed to further crack some nodes and play with the remote part. Point being, if I use it in practice, in real setups, I can come with a more serious proposal. 
![first remote attempts](https://cloud.githubusercontent.com/assets/11709974/7932788/713de88c-0923-11e5-801e-ba9778fcc22c.PNG)


But for now I 'm stuck in the Inline execution area (for convert or math). I'll try some other way...

**Comment by og76** [comment]
Update 2:
1 Extra trick variation on **debug node**:
- no label, *show value in the socket custom name* [not if iterable  rows ...] >> even smaller !
- header value only when hidden/minimized or link hide (if u don't see the sock name/value...)
>>seams more decent instead of showing same value 2 times

https://drive.google.com/file/d/0BzzAoBwXO8dsX0hZWWRkNmVZbXc/view?usp=sharing the py, if u care
(I call this nano debug cause that's the experimental version of my experimental mini :smile: )
![nano debug variation2](https://cloud.githubusercontent.com/assets/11709974/8017082/d2473ec4-0bf5-11e5-8f2f-3820c4303ed5.PNG)

---

2 I managed to make a working **Remote Connect** node.

Apparently decent working. So I'll start using it slowly in real nets and hope to draw some more realistic conclusions on design (one node that adapts or 2 in/out, how many visuals...). But mostly if it's really useful for more than a trick
![remote2](https://cloud.githubusercontent.com/assets/11709974/8017150/50313c4e-0bf7-11e5-805d-b055af60f32d.PNG)
yeah, looks bloated with data, but I need that so see what works  etc ..
also, I wish I'd base that on convert, but I cannot deal with  inline execution. yet

If u care to see it, well I should clean and organize it first ...

**Comment by JacquesLucke** [comment]
1. Ahhh I didn't know about this enabled property of a socket. Looks quite good so far. Tell me when I shall comment on your code

2. Now that I know the enabled property some things became a bit clearer to me. Having a remote node doesn't sound like a bad idea then. Without this property it would have been a terrible hack, but so it is fine :) :)

Do you have a basic understanding of the inline execution method?
Basically it is one of the three execution methods I implemented for different types of nodes.
1. Execution function that has a dictionary as input and another one as output. This is for nodes which have a dynamic amount of sockets and it is the most simple but slowest way.
2. Execution function that has mutiple keyword parameters. This is a faster method because there is no need to create a dictionary for each node execution. To enable this execution method your node needs the getInputSocketNames and getOutputSocketNames functions, which map the socket identifiers to your variable names.
3. In Line Execution: This is the fastest but maybe more advanced method as you have to write 'indirect python code'. To enable it your node has to have a function called useInLineExecution that returns True. Also it should have a function named getModuleList which returns list of module names that are needed to execute the code that is returned by the most important function called getInLineExecutionString. This function has to return a string that contains python code. This code will be slightly modified and inserted into the "Node Network Code".
![inline execution](https://cloud.githubusercontent.com/assets/5881326/8019302/b70cfc28-0c47-11e5-99cc-d054c25af61d.PNG)
The Math node uses in line execution. If you look into the auto generated code you see that no function call is needed to execute this node (red arrow) -> optimal performance
You can show the code by pressing the button at the blue arrow
Here is how the code of the math node (partially) looks like:
![math node code](https://cloud.githubusercontent.com/assets/5881326/8019309/175561ec-0c48-11e5-9aed-0892b358eb30.PNG)
The input sockets variable names (which were specified in the two functions at the top) get the percentage sign to mark them, to make it easier to replace them later. And the output names get surroundedthe dollar sign.

**Comment by og76** [comment]
Thank you for looking into this.
I'll clean it even further and also put the remote nodes

**Debug.**
*I'm very curious if you like the idea of using the custom names.*
 As ux, but also technically, as efficiency. 
Note that it does not format the floats, but show them in full. I like that ...

--
**Enabled**
My whole point was to do UI tricks, no complication with extra variables etc. More than that, switch on off all the time. No effect on the code under.

However, this **"enabled" has a trick**, selection issue, [ select menu / from nodes or to nodes (L, shift L) will go up/down the connected nodes with the selection. It does not (!) include the hidden (not enabled) links. But who the hell uses that ? ] 
*More on this when I put up the Remote Connect as I have some more explaining on what I do there. And how I work around such...*

--
**On execution**
I did read the doc on these and I understand the principles of these execution modes. And even better now. Not that I know how and where to use it yet.
But I did not use the dev tools . Thanks for that, I'll have to digg ...

My issue so far with inline execution:
(I work with UI stuff that has nothing to do with code lines, and should not have)
- **Where do I put the exec part for my (ui) showInputLink or Label stuff?** I was not able to find that so I stopped looking for Convert and made my own Remote using simpler execute.
- I tried the math, where I was looking for the label to have A+B, sin A etc depending on the op. But, again, I don't know *how to execute /update changing the label.*
- Should I use the update part? or some def for that?
 (some def I do for those operators/callFunctionFromUi that I use in remote work. I guess I'll have to upload that to be more clear...)

--
but, hey, I'm making nodes and scripts :stuck_out_tongue_closed_eyes:  :hammer:

**Comment by JacquesLucke** [comment]
Yes the custom name is exactly for such stuff :)
A few notes about your code:

1. You have multiple times  if not ###: ... else: ...    It would be easier to read when you remove the 'not' and switch the instructions.
2. the code "self.inputs[0].links" is very uneffecient. I had to learn that the hard way.. 
That is because some internal python code iterates through all links in the node tree and checks wether it is connected with your socket. I found that here: https://developer.blender.org/diffusion/B/browse/master/release/scripts/modules/bpy_types.py;5aade17bdf0f9d230c2e0bb7a97ead21a48895af$804
This is also a important reason why large node trees can become slower and slower (although the C code for drawing nodes seems a bit slow... I tested this with disabling all sockets, and it's still kinda slow :/)
You may want to use this property instead: http://www.blender.org/api/blender_python_api_2_74_5/bpy.types.NodeSocket.html?highlight=nodesocket#bpy.types.NodeSocket.is_linked 
Maybe it is faster.
3. Does this line: "else: self.showInputLink = self.showInputLink" make any sense?
4. In line 42/43 you temporary used the keyword None to say that nothing happens (your commented some code out). Python has the 'pass' keyword for that. It just looks a bit nicer.

Yes this issue with shift-L is unimportant. But thanks for mentioning that. I didn't know about that shortcut.

Okay, there are multiple different places to put your code.

1. Code that changes the custom name or whatever should be in the execute function, It's clear why, isn't it?
2. Code that you want to execute when someone linked/unlinked the node should be in the update function. For some help you can look into other nodes that change something based on what you plug in.
3. Code that shall execute after you changed a property (e.g.: 'showInputLink') gets an own function. 
Here is an example where I used this: https://github.com/JacquesLucke/animation_nodes/blob/b5f1c552906c2a3813a9719a18f7e8d76fa14685/nodes/mesh/mn_create_polygon_indices.py#L13-L17

**Comment by og76** [comment]
Thank you for this review!  I'll have to digg into this further.

Ahh! That is why I started talkin about shiftL, is based on the very is_linked.
 **is_linked is not gonna work!** it is False if the link is not enabled. The two are tied. 
(practically it does not make sense, it should not be tied to the ui ..or maybe the enabled had another purpose originally.) 

Is this gonna break anything else? do you use that is_linked in any other part? I just wonder if there is any other implication

 I found this in Remote looking for connected stuff. I workaround this further ,but for links that are there, to determine the source or target nodes. Not for links that are not ..

**Comment by JacquesLucke** [comment]
No problem :)

Hmm okay. Not sure how to do this at best.. I wrote a class that optimizes the checking if there are links. But this is only efficient if you need to check this mutliple times. 
https://github.com/JacquesLucke/animation_nodes/blob/master/utils/mn_node_utils.py#L118
I mainly used this class to speed up the execution script creation by roughly 95% ^^
You see, it is quite a big deal.

**Comment by og76** [comment]
huh, that's a lot to dig. not only for linked or not. ok, some comments:

1. I dear a little comment on the above utils code:
U use **terminology Parent/Child** node. *Maybe use Source and Target* or others if not already widely used and hard to change ... 
It's already used in Blender for frames, as parents to child nodes. I gather you refer to linked to inputs/outputs and so. I know it does not matter and may use whatever names, but if eventually wanna use parent and child for frames or so (self.parent is what I use in op mockup on frames label 

2. **On linked state** I was thinking about workarounds:
maybe to use the **update area** , 
 something like
 ```
link = self.getFirstOutputLink()
if link is not None:

or

if originSocket is not None
 ```
 could this be enough to see if something linked there? .. uses the utils code?

3. So I gather **you don't use is_linked anywhere?** Cause the *enabled* would break that.
And I would hate it cause I was doing so well with the Remote... I even got it a personalized pie menu.
![remote pie](https://cloud.githubusercontent.com/assets/11709974/8026198/2029491c-0d76-11e5-8887-73bf433cf07d.PNG)


[ I just thought pie menu may need an issue (feature) itself, or to comment in the menu renaming thing. So I made a comment on pie there #146.]

**Comment by JacquesLucke** [comment]
Yes the terminology may change in the future. 
All this can be part of what I mentioned here: https://github.com/JacquesLucke/animation_nodes/issues/142#issuecomment-103819780
This is quite important but a LOT of work. And it can take quite some time until we would have a working version again.......

2. not sure what you mean exactly.. but yes this could be enouph.

3. Well, using the search on github gives me no result for 'is_linked'. So I guess I never used it.

**Comment by JacquesLucke** [comment]
I will close it for now because it is quite old. If there is still something very special that isn't yet implemented please open another issue for that
