### ISSUE TITLE
Issue of spiral mode of "distribute matrices" node when controlled by subprogram

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1451]
![Error](https://user-images.githubusercontent.com/55994236/85047217-cc0d0100-b191-11ea-80f3-08006e4e5cb2.png)
I think the photo is illustrative enough for this error.
I remember I have seen a bug fix post about this node in the past, although I do not remember further details. Currently, the node itself can bear a negative value, but when it's controlled by the subprogram, but error still occurs. The other mode are clean without any issue.
The error is not fatal. So it can be resolved after fixing and retry, but sometimes it is still annoying.

Is it a bug? are you able to resolve that? Thanks.
win10, blender 2.83 LTS; most updated AN.

**Comment by 3DSinghVFX** [comment]
@Gerstmann-Bradley Hi. This also happens if you use input node and it is also true for other input types as well:
![Screenshot from 2020-06-18 22-03-47](https://user-images.githubusercontent.com/30294746/85047606-b1498500-b1af-11ea-81d8-4bb05c71c261.png)

@OmarEmaraDev The `minValue` property of the socket only handles the input if is not connected to other node. It is also true for `maxValue` as well.

**Comment by OmarEmaraDev** [comment]
Fixed in 087c0ef. Thanks for the report!
