### ISSUE TITLE
"Keyframe" or "Key"?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#147]
According to the related function in AN (so far), it appears we better use the word "Key" instead of "Keyframe" for better understanding.

They are:
Node Editor > Add > Object > AN Keyframe
3D View > Toolshelf > "Animation Nodes" tab > "Keyframe Manager" and "Keyframes" panel.

FYI

**Comment by JacquesLucke** [comment]
maybe something like "Object Key"? because it only works with objects...

**Comment by LeonCheung** [comment]
Ya, something like that.

**Comment by JacquesLucke** [comment]
I reimplemented this ID Key system (I called to so because it can be extended to work with all subclasses of the ID class: http://www.blender.org/api/blender_python_api_2_74_5/bpy.types.ID.html#bpy.types.ID)

It is in the id-key-system branch.
There is only one thing I still have to do for this: Currently there can be problems when you have multiple ID Keys and remove one.. 
The way to work around unwanted changes in the node is to separate the 'selected type' from the 'assigned type'. This separation is already used in multiple areas of the addon like here:
![group selection](https://cloud.githubusercontent.com/assets/5881326/8192284/52087798-146d-11e5-8015-d9691d011184.PNG)

**Comment by og76** [comment]
http://lists.blender.org/pipermail/bf-extensions-cvs/2010-June/000237.html
also found in default blender addons. activate  as system / property chart

fwiw, this one updates well the props if changed, renamed, 
on deletion says missing (so it knows you just removed/deleted)

may even rename /change value inside of it (the above commit refers to renaming..)
tough it works for selected object(s)

hope it helps
