### ISSUE TITLE
Negative scale value error in Decompose Matrix node

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1483]
Decompose Matrix node ignores sign of scale when list of matrix is applied.

![matrixDecomposeError](https://user-images.githubusercontent.com/46858047/88303063-2fa3c480-cd24-11ea-8a93-6e82ad439df3.png)

**Comment by OmarEmaraDev** [comment]
Decomposing the scale components of a transformation matrix is not possible as far as I know, because it can be interpreted as a positive scale plus rotation/mirroring. The single-value computation produces negatives values because Blender negates the scales if the determinant of the 3x3 matrix is negative, which I suppose is meant to reverse the orientation. I don't exactly understand this, so I am not sure if we should do the same.

@JacquesLucke Any insights?

**Comment by OmarEmaraDev** [comment]
Fixed in 55ccdb9.
