### ISSUE TITLE
Problem with Rigid Body, Particles and Animation Nodes

### ISSUE THREAD

**Issue by Door204** [JacquesLucke/animation_nodes#1551]
Hi there! I've got some problem when I was working on my project in blender.  LSS - When you add a Rigid Body to an Object Instancer and you have a particle system where the rigid particles should come out - they start to come out from the Instancer! I made a screenshots so you can understand this stuff better. Can you explain me please what I'm a doing wrong, cuz I watched a dozens of rigid bodies tutorials and they all using this scheme on previous versions of blender and Animation Nodes and it all work perfectly fine. or maybe it's just a bug. 

Blender 2.90
AN 2.1
![Untitled-1](https://user-images.githubusercontent.com/72503280/95333859-0374fa00-08b6-11eb-9ea4-45d312c8b4d7.jpg)

**Comment by Gerstmann-Bradley** [comment]
Not a developer, just a user.
If I understand correctly, in your first picture, the icosahedrons are "particles" not instancer.
And you are asking, based on your node tree, why instanced object doesn't come out from the emitter as these particles?
I think it's because rigid body physics is overwriting data from your node tree.
It makes sense, because if your node tree will overwrite rigid body, then you are just asking object to follow particles without any physical motion.
On the other side, since rigid body is overwriting your node tree, your node tree in this case becomes useless after the first frame.

There is a concept in my head, I tested it and seems working to me.
There is "animated" option available in rigid body physics. if you have checked the box, "transform data", which is controlled by your node tree, will overwrite physics. On the other side, if you uncheck the box, as you are doing right now, physics will overwrite your object transform data.
It's possible to regulate this checkbox through AN using "object attribute output" node. The rest you need to think is how to uncheck the box according to certain condition. I will finish my sentence here, good luck.
