### ISSUE TITLE
Range Mapper Node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#158]
Last week I wen to a presentation from a CG local artist (https://vimeo.com/57125220). For animations he relies heavily on Xpresso from C4D. On the presentation he give a clue on how sequential animations are done. They are based on the Range Mapper Node.

It was quite inteeresting for me, because I think that sequential animations are the main lack of Animation Nodes. They can be done but not so easily.  

As the artist explianed this node receives a numerical input (from 0  to 100) from a slider. According to that number and rules defined by the user, this node generates outputs that could be assign to set of objects. 

It´s very hard to me explain in english how this node works. But it doesn´t seem to be very complicated to implement. Here are some videos: 

https://vimeo.com/43257366
https://vimeo.com/44111756

**Comment by og76** [comment]
At first glimpse there are several answers to this, if I get it right.
Because it seams to me that the map range node features are already in AN
(I don't really understand what  sequential animations means here ...)

some use cases would be better to understand this, but not the 1/2 move or rotate, that is too simple.

- one node that actually is mapping some values is **the animate node** (in float, vector or matrix)
You basically can use that to *map the duration/time parameters to the start/end values*. It also clamps to start end and it also allows some cascading of these nodes...
![simple animate math](https://cloud.githubusercontent.com/assets/11709974/8394319/3259f572-1d3a-11e5-8ee3-cc09cb42f980.PNG)


- for the 2 tutorial links, rotation and translation relations, any math can just do.(note that you can drag a vector to the math socket and it will add the separate/combine nodes automatically ..) 
*object transforms input to get the xyz from source
*math or other relations (including a clamp node..)
*object transforms output to set the xyz on the target obj
![simple translate math](https://cloud.githubusercontent.com/assets/11709974/8394320/3c941284-1d3a-11e5-8427-92fd57aa6946.PNG)


- if u have a very complex relation (not just 1/2 rotation or so) you can define the respective node **setup as a group** that can be used with various inputs and outputs
![simple group math](https://cloud.githubusercontent.com/assets/11709974/8394323/4335694e-1d3a-11e5-93b2-129b3ec6c5b2.PNG)

**Comment by YorsLosilla** [comment]
Well the example exposed on the tutorial is quite simple maybe if you take a look at this video  https://vimeo.com/131194370 from 2:33 to 2:35  you´ll see the sequentation effect. I´ll try it to write down.
Imagine you have 10 objects that you want to scale from 0 to 1. The thing is that you want to animate them sequentally and you want that the animation of the second starts when the first one fineshes. But for the animation of the third one you want to started just a little bit before to the end of the animation of the second one(lets say when 90% its done). And continuing with that sequence, the animation of the fourth should begin when 80% of the animation of the third element is done.

Hope that his will clarify something. The idea is some sort of animate node with a range input (This should be a number that controls the total animation), on object list sockect input, two vectors or numbers for the beginning and the end of the transition. And two output sockects, one for the objects and another one for the values, which could be connected to a Transform Output node. 

This is what

**Comment by og76** [comment]
Ok. We are talking loops then. loops are the ones to iterate a list (sequence) of objects with variation of rule.
I'll look into it later to be more specific.

**Comment by og76** [comment]
https://drive.google.com/file/d/0BzzAoBwXO8dsMHpwTFhLNDVNOXc/view?usp=sharing
an example // play frames to see
- the animation is a rotation (as indicated), going from 180 to 0 in 10 frames
- the frames and speed is logical ..
- the math depending on index may contain whatever , for normal sequence get only the multiply by 10 node, so that each obj starts on frame 0, 10, 20 ..
the rest is altering this 10 step ... (for example play with the curve in interpolation node ...)

ps
a complex math may be reduced to an expression node

**Comment by YorsLosilla** [comment]
Well that´s exactly what I was trying to mean. Now the thing is wether or not could  be convenient to have a single node to perform such frequent type of opeartions in motion design.

**Comment by YorsLosilla** [comment]
One possible approach to this node. Input sockets:

Objects: Black socket. Receives a list of objects.
Input: The values that drive the results of the node.(Float)
Max Input, Min input: Determines the range of values for the previous socket(Float)
Output Range: Float or vector. Basically the values t o animate for the set of objects.
Anim Start Factor: A factor that changes the animation start point of the following object. (Float)
Anim Duration Factor: A factor that changes the duration of the animation duration
Duration: How much units does the animation last for the first item.

Outoput:

Objects:

Animation Result:
