### ISSUE TITLE
Handling sockets in AN

### ISSUE THREAD

**Issue by Durman** [JacquesLucke/animation_nodes#1583]
Hello I'm Sverchok developer would like ask you an advice. 
We in Sverchok have [the problem](https://github.com/nortikin/sverchok/issues/3514) with changing sockets code of already existed nodes. If someone wants to change any socket type of existing node or even rename it he have to copy whole node code and move old code to `old nodes` category. I'm finding this more than inconvenient. 

The question is how AN deals with such situations? I expect that just changing socket type in existing node is not the solution because it will broke existing tree layouts.

**Comment by OmarEmaraDev** [comment]
Animation Nodes mostly relies on socket identifiers. Since we use identifiers, we can freely change socket names without breaking node trees. As for type changes, the socket value will not be retained but the link will **only** be removed if no implicit conversion between the source and the new type exist. Finally, if the identifier change, the link will be removed with a warning printed in the terminal informing the user about the removal, more on this later.

The identifier is set here:
https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/base_types/nodes/base_node.py#L317

File updates happen here:
https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/base_types/update_file.py

---

While we generally try to avoid breaking files, Animation Nodes does not try to be backward compatible, so we don't implement any versioning code. If you do want to implement versioning, I suppose you can keep a look up table for the changes you make and look at them in the `setSocketProperties`  and `setLinks` functions in `update_file.py`. So instead of removing links or skip value setting, you look at the look up table and see if there are any entries for this node and sockets identifiers, and if there are, you use those entries to try to update the sockets and links.

**Comment by Durman** [comment]
Sverchok always does not search easy way. I would definitely want Sverchok could use the same tehnic of sanitizing opening files as AN does. It would help to solve many problems with sockets. Thanks for pointing on to exact files in AN. I will investigate them later when I'll came to this problem in Sverchok. Look table is good idea I guess. There is probably no other alternative of keeping backward compatibility of sockets with old layouts. I don't know how this could be implemented in sverchok yet. 

For now there is one particular problem. Vertices socket has old name of default value - `prop`.

https://github.com/nortikin/sverchok/blob/2f900648543ead3b7a310890c0f5a162861e12b4/core/sockets.py#L564

And I can't rename it because old layouts are point on this property. I had made python property wrapper but it is not the same and sockets API is inconsistent now. Hope it will be fixed someday.

https://github.com/nortikin/sverchok/blob/2f900648543ead3b7a310890c0f5a162861e12b4/core/sockets.py#L571-L577
