### ISSUE TITLE
Why not merge extra nodes?

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/animation_nodes#1603]
Hi

Is there any reason why the extra nodes part of Animation Nodes give that the maintainer already has submissions for this repo already? This can be very helpful for production purposes because Animation Nodes will be high likely hood of getting maintained.

thanks

**Comment by OmarEmaraDev** [comment]
1. As you said, the maintainer already pushes some of his nodes our way, but this is a lengthy processes as a review of the code has to take place, which is bound by our time and his time. So it is a waiting game for some of those nodes.
2. Other nodes will not be accepted into Animation Nodes, due to one reason or another. But that is okay, that's why we have extensions, and the nodes will be easily accessible.
