### ISSUE TITLE
AN animation freezes when rendering in 2.9 

### ISSUE THREAD

**Issue by sickmotion** [JacquesLucke/animation_nodes#1632]
Hello,
i followed the tutorial of BlueFox creations (https://youtu.be/5YHW1EUtIYw ) and when I render every other animation in the scene works but only the "ballman" freezes.
If somebody has a solution for this pls help.
Thanks!
(the animation works in the view port just fine btw)
![Screenshot (2)](https://user-images.githubusercontent.com/77440554/104584387-d37e8500-5662-11eb-94c3-28c4df8011c5.png)

**Comment by OmarEmaraDev** [comment]
Freeze as in crash?

**Comment by sickmotion** [comment]
No blender renders the animations around as normal only the ballman doesn`t move a frame (freezes)

**Comment by OmarEmaraDev** [comment]
Perhaps @harisreedhar can take a look.

**Comment by harisreedhar** [comment]
@sickmotion Hi, At the time of recording the tutorial sverchok doesn't have particle support. To overcome this situation animation nodes is used. But in recent release sverchok supports particles. So, you don't need animation nodes for this task.

Here is updated node tree you can use:
![dancer_nodeTree](https://user-images.githubusercontent.com/46858047/104600282-cda69500-569e-11eb-8032-891c5ad82a82.png)

If you still have rendering issue you can bake instanced spheres objects using ``Bake Action``.

Since this topic is not relevant to animation nodes for further discussion you can contact me via twitter or instagram.
Thank you

**Comment by sickmotion** [comment]
Thanks dude you`re insane now it`s rendering. Keep making AN tutorials pls!
