### ISSUE TITLE
Trying to make a node with some new inputs 

### ISSUE THREAD

**Issue by LaurineCapdeville** [JacquesLucke/animation_nodes#1642]
Hello!

I'm trying to create a node that can take new inputs just like the "create list" node does, but since the code of this node is mixed with the type handling of the list, I'm having a hard time understanding what is necessary or what is not for what I want to do.

Here is what I want my node to do :
-Input = quantum_circuit_input
-Input = Index 0
-Input = Index 1
.... as many indexes as the user wants
-Output = quantum_circuit_output
-Execution: for all the indexes, apply a function to quantum_circuit_input at each index and then return the quantum circuit

Here is the code that I have so far, inspired by the "create list " node, but my understanding of it is quite limited (and it's my first time developing in python) so they might be some lame mistakes...

```python 
import bpy
from qiskit import *
from animation_nodes.base_types import AnimationNode

class QuantumGateHNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_QuantumGateHNode"
    bl_label = "Quantum GateH"
    dynamicLabelType = "ALWAYS"

    def create(self):
        # input circuit and output circuit
        self.newInput("Quantum Circuit", "Input Circuit", "input_circuit")
        self.newOutput("Quantum Circuit", "Output Circuit", "output_circuit")

    def draw(self, layout):
        row = layout.row(align = True)
        self.invokeFunction(row, "newInputSocket",
            text = "Add Other Gate",
            description = "Create a new input socket",
            icon = "PLUS")
        self.invokeFunction(row, "removeUnlinkedInputs",
            description = "Remove unlinked inputs",
            confirm = True,
            icon = "X")

#not so sure of what this does
    def getInputSocketVariables(self):
        return {socket.identifier : "element_" + str(i) for i, socket in enumerate(self.inputs)}

    def getExecutionCode(self, required, input_circuit): 
        try:
            #here I want to apply the function  input_circuit.h() at all the input indexes and then return the circuit.
            for index_input in self.inputs[1:]:  #I don't want the first input to be tanken into account since it is the input circuit 
                input_circuit.h(index_input.data)
            createOutputCircuit = self.outputs[0].getFromValuesCode().replace("value", input_circuit) #don't know if I'm using this right
            return createOutputCircuit
        except:
            return

#not so sure of what to do with those functions
    def edit(self):  
        emptySocket = self.inputs["..."]
        origin = emptySocket.directOrigin
        if origin is None: return
        socket = self.newInputSocket()
        socket.linkWith(origin)
        emptySocket.removeLinks()

    def recreateSockets(self, inputAmount = 2):
        self.clearSockets()

        self.newInput("Node Control", "...")
        for i in range(inputAmount):
            self.newInputSocket()
        
    def newInputSocket(self):
       #the user can add as many indexes as he wants 
        socket = self.newInput("Integer","Qubit Index")
        socket.dataIsModified = True
        socket.display.text = True
        socket.text = "Qubit Index"
        socket.removeable = True
        socket.moveable = True
        socket.defaultDrawType = "PREFER_PROPERTY"
        socket.moveUp()

#what does those two lines do?
        if len(self.inputs) > 3:
            socket.copyDisplaySettingsFrom(self.inputs[1]) 

        return socket

    def removeUnlinkedInputs(self):
        for socket in self.inputs[:-1]:
            if not socket.is_linked:
                socket.remove()
```
I still a bit lost in the animation nodes code, so I don't know which function to override and how to access the node's sokes data etc...

Any help would be welcome ! :)
Thank you very much in advance!

**Comment by OmarEmaraDev** [comment]
We need to understand the execution mechanism of Animation Nodes first.

# Execution Mechanism

Animation Nodes looks at the node tree, generates an equivalent Python code, and finally executes that code. To do that, Animation Nodes asks every node for its execution code, that is, the list of lines that the node would like to contribute to the full code of the node tree. The way that Animation Nodes asks a node tree for its execution code is as follows. First, Animation Nodes looks at the return value of the `getExecutionFunctionName` method. This function is defined in the base class as follows:

```python
    def getExecutionFunctionName(self):
        return "execute"
```

Meaning that if the node doesn't define this method, `execute` will be returned. Then, Animation Nodes look in the node for a method by that name, if a method with that name was found, this method is assumed to be the execution function of the node, and Animation Nodes contributes a single line of code that executes that method passing the inputs of the node as arguments and assigning the return value of the node to the node outputs.

For instance, lets look at the following example node definition:

```python
    def create(self):
        self.newInput("Quantum Circuit", "Input Circuit", "input")
        self.newInput("Integer", "Qubit Index", "qubit_index")
        self.newOutput("Quantum Circuit", "Output Circuit", "output")

    def execute(self, input, qubit_index):
        input.h(qubit_index)
        return input
```

The node doesn't define an `getExecutionFunctionName` method, so the return value will be `execute`. Animation Nodes checks if there are any method named `execute` in the node, which it finds. So a single line is contributed to the full execution code of the node tree, which is as follows:

```python
output = self.execute(input, qubit_index)
```

Typically, if your nodes have multiple modes of operations, you would define multiple execution methods and choose between them in the `getExecutionFunctionName` method. For instance:

```python
    def create(self):
        self.newInput("Quantum Circuit", "Input Circuit", "input")
        self.newInput("Integer", "Qubit Index", "qubit_index")
        self.newOutput("Quantum Circuit", "Output Circuit", "output")

    def getExecutionFunctionName(self):
        if self.someOption:
            return "executeSomeOption"
        else:
            return "executeSomethingElse"

    def executeSomeOption(self, input, qubit_index):
        # Do something.

    def executeSomethingElse(self, input, qubit_index):
        # Do something else.
```

In this case, Animation Nodes will contribute either of the following two lines depending on the value of `self.someOption`:

```python
output = self.executeSomeOption(input, qubit_index)
```

```python
output = self.executeSomethingElse(input, qubit_index)
```

Okay. What about the case when the return value of `getExecutionFunctionName` doesn't corresponds to any method in the node? For instance, if `getExecutionFunctionName` is not defined (Meaning the return value will be `execute`) but no `execute` method exists in the node. In this case, Animation Nodes assumes the node defines a `getExecutionCode` method and that the method will take charge of contributing the execution code to the full node tree code itself. The following node definition is identical to the one above, except it uses the `getExecutionCode` method:

```python
    def create(self):
        self.newInput("Quantum Circuit", "Input Circuit", "input")
        self.newInput("Integer", "Qubit Index", "qubit_index")
        self.newOutput("Quantum Circuit", "Output Circuit", "output")

    def getExecutionCode(self, required):
        yield "input.h(qubit_index)"
        yield "output = input"
```

The node doesn't define an `execute` method, so the output of the `getExecutionCode` method is contributed directly to the full execution code of the node tree. Notice that this method is a python generator of strings, meaning it should yield the lines of code as strings, as can be seen above. The `getExecutionCode` code doesn't take the inputs of the node as arguments, it only takes a single argument `required` as input. `required` is a set containing the identifiers of all outputs that are linked. That mean the expression `if "output" in required:` is True if and only if the output is linked to something in the node tree. `required` is usually used to conditionally contribute code only when certain outputs are actually used.

If `getExecutionCode` doesn't take the inputs as arguments, then how do we access the inputs of the node? In the method above, you can see that we accessed the inputs through some variable, but how do we know the variable names of the inputs and outputs? The answer lies in the two methods `getInputSocketVariables`, `getOutputSocketVariables`. Those methods define the mapping between the variable names in the execution code and the inputs of the node. Those methods are defined in the base class of the node as follows:

```python
    def getInputSocketVariables(self):
        return {socket.identifier : socket.identifier for socket in self.inputs}

    def getOutputSocketVariables(self):
        return {socket.identifier : socket.identifier for socket in self.outputs}
```

They both return a dictionary, whose keys are the identifiers of the sockets (The identifiers are the third argument in your `newInput` call, or the second argument if the third is not provided) and the values of the dictionary are the variable names of the sockets. If those methods are not defined, the variable names will be the identifier names, hence why we use the identifiers as variable names above. But we can change those variables names by defining either functions:

```python
    def create(self):
        self.newInput("Quantum Circuit", "Input Circuit", "input")
        self.newInput("Integer", "Qubit Index", "qubit_index")
        self.newOutput("Quantum Circuit", "Output Circuit", "output")

    def getInputSocketVariables(self):
        return {"input" : "inputQuantumCircuit", "qubit_index" : "quantumQubitIndex"}

    def getOutputSocketVariables(self):
        return {"output" : "outputQuantumCircuit"}

    def getExecutionCode(self, required):
        yield "inputQuantumCircuit.h(quantumQubitIndex)"
        yield "outputQuantumCircuit = inputQuantumCircuit"
```

This should cover the basics of how one can define node execution code.

# Your Code

Your first method is:

```python
    # Not so sure of what this does.
    def getInputSocketVariables(self):
        return {socket.identifier : "element_" + str(i) for i, socket in enumerate(self.inputs)}
```

Hopefully, it should be clear what this does now. It will let you reference the input data using the variable names `element_0`, `element_1`, `element_2`, and so on. However, notice that the first input `Input Circuit` is now assigned to the variable name `element_0`, which is probably not what you want. So we can change the method to account for this:

```python
    # Not so sure of what this does.
    def getInputSocketVariables(self):
        socketMapping = {socket.identifier : "element_" + str(i) for i, socket in enumerate(self.inputs[1:])}
        socketMapping["input_circuit"] = "inputCircuit"
        return socketMapping
```

---

Your second method is:

```python
    def getExecutionCode(self, required, input_circuit):
        try:
            #here I want to apply the function  input_circuit.h() at all the input indexes and then return the circuit.
            for index_input in self.inputs[1:]:  #I don't want the first input to be tanken into account since it is the input circuit 
                input_circuit.h(index_input.data)
            createOutputCircuit = self.outputs[0].getFromValuesCode().replace("value", input_circuit) #don't know if I'm using this right
            return createOutputCircuit
        except:
            return
```

As we said, the `getExecutionCode` function only takes `required`, so `input_circuit` shouldn't be in the method header. Moreover, the code need to be yielded as strings instead, so the full function should be something like:

```python
    def getExecutionCode(self, required):
        yield "try:"
        for i in range(len(self.inputs) - 1)
            yield f"    inputCircuit.h(element_{i})"
        yield "    output_circuit = inputCircuit"
        yield "except:"
        yield "    self.raiseErrorMessage('Failed to do Quantum operation.')"
```

Make sure you get the indentation right when writing the strings. Also notice that the variable names are as we defined above in `getInputSocketVariables`.

---

Your next method is:

```python
    def edit(self):  
        emptySocket = self.inputs["..."]
        origin = emptySocket.directOrigin
        if origin is None: return
        socket = self.newInputSocket()
        socket.linkWith(origin)
        emptySocket.removeLinks()
```

The `edit` method of a node is executed whenever the user connects something to the node. This node uses a special input socket type called "Node Control", this socket is the transparent one you see in the node. This socket is never connected to something, but when you try to connect something to it, a new socket is created and the connection goes to that socket instead. And that's exactly what the `edit` method above does. The method does the following:

1. It gets the Node Control socket by its identifier `...`
2. It checks the value of `directOrigin`. This value contains the output socket that was connected to this input. Or None if no output was connected.
3. If `directOrigin` was None, nothing happens and the method returns.
4. Otherwise, a new socket is created.
5. The new socket is connect to the `directOrigin`.
6. The original link to the Node Control socket is removed.

---

Your next method is:

```python
    def recreateSockets(self, inputAmount = 2):
        self.clearSockets()

        self.newInput("Node Control", "...")
        for i in range(inputAmount):
            self.newInputSocket()
```

This method is probably not needed in your case. So it can be omitted. However, you still need to create the Node Control somewhere. In this case, you can define the `setup` method, which is only called once when the node is added:

```python
    def setup(self):
        self.newInput("Node Control", "...")
        self.newInputSocket()
```

Additionally, we also create one new socket, but you can omit that if you don't want any inputs initially.

---

Your next method is:

```python
    def newInputSocket(self):
       #the user can add as many indexes as he wants 
        socket = self.newInput("Integer","Qubit Index")
        socket.dataIsModified = True
        socket.display.text = True
        socket.text = "Qubit Index"
        socket.removeable = True
        socket.moveable = True
        socket.defaultDrawType = "PREFER_PROPERTY"
        socket.moveUp()

#what does those two lines do?
        if len(self.inputs) > 3:
            socket.copyDisplaySettingsFrom(self.inputs[1]) 

        return socket
```

The method is called by the `setup` and `edit` methods to create a new socket and set some of its properties, some of those properties are straightforward, other are dependent on your socket type. Let me know if you want me to elaborate on one of them. Aside from the obvious, I actually have no idea what those two lines do. It is probably legacy code.

# Recommendations

I think the easier approach would be to create an Integer List instead and just loop over its elements in an execute method. Or do you have a specific use case for your current approach?

**Comment by LaurineCapdeville** [comment]
> We need to understand the execution mechanism of Animation Nodes first.
> # Execution Mechanism
> 
> Animation Nodes looks at the node tree, generates an equivalent Python code, and finally executes that code. To do that, Animation Nodes asks every node for its execution code, that is, the list of lines that the node would like to contribute to the full code of the node tree. The way that Animation Nodes asks a node tree for its execution code is as follows. First, Animation Nodes looks at the return value of the `getExecutionFunctionName` method. This function is defined in the base class as follows:
> 
> ```python
>     def getExecutionFunctionName(self):
>         return "execute"
> ```
> 
> Meaning that if the node doesn't define this method, `execute` will be returned. Then, Animation Nodes look in the node for a method by that name, if a method with that name was found, this method is assumed to be the execution function of the node, and Animation Nodes contributes a single line of code that executes that method passing the inputs of the node as arguments and assigning the return value of the node to the node outputs.
> 
> For instance, lets look at the following example node definition:
> 
> ```python
>     def create(self):
>         self.newInput("Quantum Circuit", "Input Circuit", "input")
>         self.newInput("Integer", "Qubit Index", "qubit_index")
>         self.newOutput("Quantum Circuit", "Output Circuit", "output")
> 
>     def execute(self, input, qubit_index):
>         input.h(qubit_index)
>         return input
> ```
> 
> The node doesn't define an `getExecutionFunctionName` method, so the return value will be `execute`. Animation Nodes checks if there are any method named `execute` in the node, which it finds. So a single line is contributed to the full execution code of the node tree, which is as follows:
> 
> ```python
> output = self.execute(input, qubit_index)
> ```
> 
> Typically, if your nodes have multiple modes of operations, you would define multiple execution methods and choose between them in the `getExecutionFunctionName` method. For instance:
> 
> ```python
>     def create(self):
>         self.newInput("Quantum Circuit", "Input Circuit", "input")
>         self.newInput("Integer", "Qubit Index", "qubit_index")
>         self.newOutput("Quantum Circuit", "Output Circuit", "output")
> 
>     def getExecutionFunctionName(self):
>         if self.someOption:
>             return "executeSomeOption"
>         else:
>             return "executeSomethingElse"
> 
>     def executeSomeOption(self, input, qubit_index):
>         # Do something.
> 
>     def executeSomethingElse(self, input, qubit_index):
>         # Do something else.
> ```
> 
> In this case, Animation Nodes will contribute either of the following two lines depending on the value of `self.someOption`:
> 
> ```python
> output = self.executeSomeOption(input, qubit_index)
> ```
> 
> ```python
> output = self.executeSomethingElse(input, qubit_index)
> ```
> 
> Okay. What about the case when the return value of `getExecutionFunctionName` doesn't corresponds to any method in the node? For instance, if `getExecutionFunctionName` is not defined (Meaning the return value will be `execute`) but no `execute` method exists in the node. In this case, Animation Nodes assumes the node defines a `getExecutionCode` method and that the method will take charge of contributing the execution code to the full node tree code itself. The following node definition is identical to the one above, except it uses the `getExecutionCode` method:
> 
> ```python
>     def create(self):
>         self.newInput("Quantum Circuit", "Input Circuit", "input")
>         self.newInput("Integer", "Qubit Index", "qubit_index")
>         self.newOutput("Quantum Circuit", "Output Circuit", "output")
> 
>     def getExecutionCode(self, required):
>         yield "input.h(qubit_index)"
>         yield "output = input"
> ```
> 
> The node doesn't define an `execute` method, so the output of the `getExecutionCode` method is contributed directly to the full execution code of the node tree. Notice that this method is a python generator of strings, meaning it should yield the lines of code as strings, as can be seen above. The `getExecutionCode` code doesn't take the inputs of the node as arguments, it only takes a single argument `required` as input. `required` is a set containing the identifiers of all outputs that are linked. That mean the expression `if "output" in required:` is True if and only if the output is linked to something in the node tree. `required` is usually used to conditionally contribute code only when certain outputs are actually used.
> 
> If `getExecutionCode` doesn't take the inputs as arguments, then how do we access the inputs of the node? In the method above, you can see that we accessed the inputs through some variable, but how do we know the variable names of the inputs and outputs? The answer lies in the two methods `getInputSocketVariables`, `getOutputSocketVariables`. Those methods define the mapping between the variable names in the execution code and the inputs of the node. Those methods are defined in the base class of the node as follows:
> 
> ```python
>     def getInputSocketVariables(self):
>         return {socket.identifier : socket.identifier for socket in self.inputs}
> 
>     def getOutputSocketVariables(self):
>         return {socket.identifier : socket.identifier for socket in self.outputs}
> ```
> 
> They both return a dictionary, whose keys are the identifiers of the sockets (The identifiers are the third argument in your `newInput` call, or the second argument if the third is not provided) and the values of the dictionary are the variable names of the sockets. If those methods are not defined, the variable names will be the identifier names, hence why we use the identifiers as variable names above. But we can change those variables names by defining either functions:
> 
> ```python
>     def create(self):
>         self.newInput("Quantum Circuit", "Input Circuit", "input")
>         self.newInput("Integer", "Qubit Index", "qubit_index")
>         self.newOutput("Quantum Circuit", "Output Circuit", "output")
> 
>     def getInputSocketVariables(self):
>         return {"input" : "inputQuantumCircuit", "qubit_index" : "quantumQubitIndex"}
> 
>     def getOutputSocketVariables(self):
>         return {"output" : "outputQuantumCircuit"}
> 
>     def getExecutionCode(self, required):
>         yield "inputQuantumCircuit.h(quantumQubitIndex)"
>         yield "outputQuantumCircuit = inputQuantumCircuit"
> ```
> 
> This should cover the basics of how one can define node execution code.
> # Your Code
> 
> Your first method is:
> 
> ```python
>     # Not so sure of what this does.
>     def getInputSocketVariables(self):
>         return {socket.identifier : "element_" + str(i) for i, socket in enumerate(self.inputs)}
> ```
> 
> Hopefully, it should be clear what this does now. It will let you reference the input data using the variable names `element_0`, `element_1`, `element_2`, and so on. However, notice that the first input `Input Circuit` is now assigned to the variable name `element_0`, which is probably not what you want. So we can change the method to account for this:
> 
> ```python
>     # Not so sure of what this does.
>     def getInputSocketVariables(self):
>         socketMapping = {socket.identifier : "element_" + str(i) for i, socket in enumerate(self.inputs[1:])}
>         socketMapping["input_circuit"] = "inputCircuit"
>         return socketMapping
> ```
> 
> Your second method is:
> 
> ```python
>     def getExecutionCode(self, required, input_circuit):
>         try:
>             #here I want to apply the function  input_circuit.h() at all the input indexes and then return the circuit.
>             for index_input in self.inputs[1:]:  #I don't want the first input to be tanken into account since it is the input circuit 
>                 input_circuit.h(index_input.data)
>             createOutputCircuit = self.outputs[0].getFromValuesCode().replace("value", input_circuit) #don't know if I'm using this right
>             return createOutputCircuit
>         except:
>             return
> ```
> 
> As we said, the `getExecutionCode` function only takes `required`, so `input_circuit` shouldn't be in the method header. Moreover, the code need to be yielded as strings instead, so the full function should be something like:
> 
> ```python
>     def getExecutionCode(self, required):
>         yield "try:"
>         for i in range(len(self.inputs) - 1)
>             yield f"    inputCircuit.h(element_{i})"
>         yield "    output_circuit = inputCircuit"
>         yield "except:"
>         yield "    self.raiseErrorMessage('Failed to do Quantum operation.')"
> ```
> 
> Make sure you get the indentation right when writing the strings. Also notice that the variable names are as we defined above in `getInputSocketVariables`.
> 
> Your next method is:
> 
> ```python
>     def edit(self):  
>         emptySocket = self.inputs["..."]
>         origin = emptySocket.directOrigin
>         if origin is None: return
>         socket = self.newInputSocket()
>         socket.linkWith(origin)
>         emptySocket.removeLinks()
> ```
> 
> The `edit` method of a node is executed whenever the user connects something to the node. This node uses a special input socket type called "Node Control", this socket is the transparent one you see in the node. This socket is never connected to something, but when you try to connect something to it, a new socket is created and the connection goes to that socket instead. And that's exactly what the `edit` method above does. The method does the following:
> 
>     1. It gets the Node Control socket by its identifier `...`
> 
>     2. It checks the value of `directOrigin`. This value contains the output socket that was connected to this input. Or None if no output was connected.
> 
>     3. If `directOrigin` was None, nothing happens and the method returns.
> 
>     4. Otherwise, a new socket is created.
> 
>     5. The new socket is connect to the `directOrigin`.
> 
>     6. The original link to the Node Control socket is removed.
> 
> 
> Your next method is:
> 
> ```python
>     def recreateSockets(self, inputAmount = 2):
>         self.clearSockets()
> 
>         self.newInput("Node Control", "...")
>         for i in range(inputAmount):
>             self.newInputSocket()
> ```
> 
> This method is probably not needed in your case. So it can be omitted. However, you still need to create the Node Control somewhere. In this case, you can define the `setup` method, which is only called once when the node is added:
> 
> ```python
>     def setup(self):
>         self.newInput("Node Control", "...")
>         self.newInputSocket()
> ```
> 
> Additionally, we also create one new socket, but you can omit that if you don't want any inputs initially.
> 
> Your next method is:
> 
> ```python
>     def newInputSocket(self):
>        #the user can add as many indexes as he wants 
>         socket = self.newInput("Integer","Qubit Index")
>         socket.dataIsModified = True
>         socket.display.text = True
>         socket.text = "Qubit Index"
>         socket.removeable = True
>         socket.moveable = True
>         socket.defaultDrawType = "PREFER_PROPERTY"
>         socket.moveUp()
> 
> #what does those two lines do?
>         if len(self.inputs) > 3:
>             socket.copyDisplaySettingsFrom(self.inputs[1]) 
> 
>         return socket
> ```
> 
> The method is called by the `setup` and `edit` methods to create a new socket and set some of its properties, some of those properties are straightforward, other are dependent on your socket type. Let me know if you want me to elaborate on one of them. Aside from the obvious, I actually have no idea what those two lines do. It is probably legacy code.
> # Recommendations
> 
> I think the easier approach would be to create an Integer List instead and just loop over its elements in an execute method. Or do you have a specific use case for your current approach?

Waouh! Thank you so much, I wasn't expecting such an answer! 
We do have a specific use for our approach, but maybe it's not in the spirit of how nodes work. We want to add logical gates to a circuit of bits (qubits here but it's not very important), so we thought it would be more intuitive for the user to choose on what bit of the circuit to put them.
Here is a more visual illustration :
![GateY](https://user-images.githubusercontent.com/58808393/104822240-5fe69e80-5841-11eb-8148-ffeef54ff744.png)
The idea is to have a circuit whit multiple qubits and bits and add multiple logical gates to this circuit.
But I don't want to take any more of your time so I will study a little more the already existing nodes and your great answer to figure out the best approach.
Thank you so much again and have a good evening!

**Comment by OmarEmaraDev** [comment]
I see. That's a very interesting project. Let me know if you need anything else.

Closing this for now, but feel free to reopen or create a new issue if needed.
