### ISSUE TITLE
Random Matrix node

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1643]
![random matrix](https://user-images.githubusercontent.com/64368228/104828834-4cbae980-58a8-11eb-9b3e-3796e5d1ecaf.gif)

this is a demo version, i don't know this node is necessary.

**Comment by Gerstmann-Bradley** [comment]
Firstly, Thanks for making this node!

Here are some suggestions/proposals, and my own design about such kind of node. There is also an attached video demonstration of its design. It's your and Omar's decision to think how far to take these.

1. Location has two level of controls. One is like "your radius" that expand equally in all direction. Another is a "factor" control that determine the expansion in each axis. If the factor is 1,1,1, then all axis expand equally, if the factor is 1,1,2, then Z axis will expand 2X more than the other with "radius". Indeed, when certain factor turns 0, then there is no expansion in location on that axis.
2. I used a different variation method in scale. Basically I set a "average", and then use a "percentage" of that average to set that range. The advantage of this method is I can easily scale up all objects using just 1 parameter (the "average"), instead of 2 parameters (both minimum and maximum). This way it's more easy. This is also kind of what C4D does. I also have a secondary control for the axis. Similar to what I have done to locations.
3. For rotation, similar to the other two, I have a general control to all axis, and a secondary control to each axis specifically on the top of general control to all axis.
4. I have added evolution for location, scale & rotation each.
5. In the newest version of my design, I have hidden the secondary control of rotation and scale to keep UI cleaner and node small.
6. Same as "distribute matrices" node, I have vector output. I also output each component, in order to simply the workflow with "close packing" node in extranode. This way I easily avoid intersections.

https://user-images.githubusercontent.com/55994236/104834784-ace16980-586f-11eb-9c57-d8dc13ba0245.mp4

**Comment by Gerstmann-Bradley** [comment]
Also to add, perhaps you can put this node as a "Random Mode" within "distribute matrices". Or maybe not, Since I am proposing to add other output components. Either way, this is not my decision. At the end, thanks again.

**Comment by OmarEmaraDev** [comment]
I feel like the node would end up identical to a compose matrix node with three random or wiggle nodes for each transformation component. Sure, the user would need to add couple of extra nodes, but the functionality would stay the same and will probably be more selective and efficient. But cramming all of that in a single node is a bit too much in my opinion. What do you think?

**Comment by Gerstmann-Bradley** [comment]
> I feel like the node would end up identical to a compose matrix node with three random or wiggle nodes for each transformation component. Sure, the user would need to add couple of extra nodes, but the functionality would stay the same and will probably be more selective and efficient. But cramming all of that in a single node is a bit too much in my opinion. What do you think?

It's true that functionality is somehow the same. But considering C4D has 1 random effector to cover these functions and even beyond, I think the necessity to add some extra nodes makes a difference for users who want to achieve a quick effect.

Either way I have my own subprogram for what I specifically need. Even If this node doesn't come into AN I am still fine with it. This is developers' call. I am always thankful to you guys' contributions!

**Comment by kdsin23** [comment]
@OmarEmaraDev yes, i also have this feelings, i think the only benefit is that the performance is better than the nodes by manual. 

the more i want to do is that make a random effector node , can do more things like the funcitons @Gerstmann-Bradley suggestions.

**Comment by OmarEmaraDev** [comment]
Essentially, if we want it to be sufficiently flexible and useful, we would need to extend it to be similar to @Gerstmann-Bradley's subprogram. But then that node would be gigantic, bigger than any node we have at the moment. So I don't think such a node would be a good idea.
