### ISSUE TITLE
Character Properties Output not updating for render

### ISSUE THREAD

**Issue by stephenthomas0** [JacquesLucke/animation_nodes#1662]
I have a project file using Animation Nodes that spans several scenes, each node tree is associated to a particular scene, but they all use the Invoke Subprogram node which is in its own node tree in the first scene. After adding the third scene, the 'Character Properties Output' stopped updating when rendering the animation (it's being used to change the Material Index for some characters). It worked fine with only one or two scenes. The issue only occurs when the viewport is in rendered mode and you move through the timeline frame by frame or if you render the animation. Playing the animation with the viewport in rendered mode works and so does rendering single frames.

[Here's](https://www.dropbox.com/s/axna4y3yko7s0si/text-screen-recording.mp4?dl=0) a video recording showing the issue in action, [here's](https://www.dropbox.com/s/57703v8ie4zhxvw/system-info.txt?dl=0) my system-info.txt and [here's](https://www.dropbox.com/s/tod31eyhhvz72r1/text.blend?dl=0) the blend file.

This is using the latest version of animation nodes (2.2.2) on macOS Big Sur (11.2.1).

Let me know if you need anything else. No rush on my end for this as I've created a workaround, but I imagine it would be quite nice to squash this bug.

**Comment by OmarEmaraDev** [comment]
This is probably not a bug, but rather an ambiguity in the order of execution of nodes. The problematic part of the node tree is this one:

![20210214-215005](https://user-images.githubusercontent.com/25300994/107887340-1ce61c80-6f0e-11eb-9d43-e835cd2a0bc0.png)

Those nodes don't dependent on each other, and you gave no indication of which node should be executed first. So Animation Nodes makes an arbitrary decision and executes them in any order. It happened that during rendering Animation Nodes made a different decision that produced unexpected results. That's why in Animation Nodes, if you will use multiple output nodes on the same object, you should connect the nodes in serial not in parallel. That's why all output nodes have their input as an output, to allow you to connect them in series.

In this case, you do three things, 1) Write the text to the object. 2) Set the material index for the first character. 3) Set the material index for the last character. It is very important that (1) executes before (2) and (3) because we can't set the material index to characters that haven't been written yet. The order of (2) and (3) is probably not important in this case. In conclusion, your node tree should be as follows:

![20210214-220043](https://user-images.githubusercontent.com/25300994/107887541-7e5abb00-6f0f-11eb-8fd8-6f958cbac0f5.png)

Great first bug report by the way, and nicely organized node tree. :+1:

**Comment by stephenthomas0** [comment]
Ah, that makes sense, thanks Omar, have made the change and can confirm that it now works. I'm quite new to Animation Nodes so I'm still figuring these things out.

Thank you, glad you like it. Needed to organise it well so I could keep track of what's happening where. Really like what you're doing with this, really really nice tool 😊
