### ISSUE TITLE
Question: Triangles in Plexsus effect.

### ISSUE THREAD

**Issue by dwizor** [JacquesLucke/animation_nodes#1701]
Hello,
I want to create plexsus effect with triangles like on this reference:
![Plexsus_Ref](https://user-images.githubusercontent.com/68112419/115080921-c3956c00-9f03-11eb-94e2-5f42686826bb.png)
I have setup like this with lines and spheres, but i dont have idea how to achieve these traingles. Combine mesh requires polygon indices but i dont have idea from where i can get them.
![Plexsus_Setup](https://user-images.githubusercontent.com/68112419/115081518-b2992a80-9f04-11eb-8f6e-85ae42ce1970.png)

**Comment by Gerstmann-Bradley** [comment]
There's a tutorial about that: https://youtu.be/R9vFKAHYik8?t=1062
The basic idea is to generate triangle. You either generate a triangle by your own, or use "unity triangle" node. (using later method is definitely better), and use their edge indices and polygon indices.
So how to get points?
You generate KD tree. Within the loop, get random point, and find closest 3 points. and overwrite original triangle vertices data. Output the mesh. Since it's looping. you can generate as many triangle as you want.

Details are all answered and shown in the tutorial.

**Comment by dwizor** [comment]
Oh nice, this will be helpful(btw i love your tutorials for AN!) Before I asked this question, I checked tutorials for plexsus effects in AN, I dont know how I missed this ;o Thanks a lot ^^
