### ISSUE TITLE
Simultaneous Dynamic and Animated on Physics properties is not working simultaneously

### ISSUE THREAD

**Issue by Netzahualcoyotl** [JacquesLucke/animation_nodes#1754]
Issue 
If you select the physics properties of the cube on Settings Box Dynamic and simultaneously select the box Animated the Animation nodes module does not pass to the same time of global simulation the result of Dynamic and Animation

[https://gitlab.com/Internetza/blenderanimationsscriptphysicsrender/-/blob/master/AnimationExample.blend](url)

**Comment by OmarEmaraDev** [comment]
I am not sure what you mean exactly. Can you clarify?

**Comment by Netzahualcoyotl** [comment]
Hope this video can explain a little better
https://youtu.be/jhJELGC8Syk

**Comment by OmarEmaraDev** [comment]
As far as I know, this is an expected behavior. When Animation is enabled, the physics engine no longer updates the object, and it starts updating again when it gets disabled using the previous known velocity and angular velocity of the object. This is only possible if you have keyframes.

**Comment by Netzahualcoyotl** [comment]
The problem is:
    Supouse you have the transformation of translation used by the animation then the physics is not updating the position of the object. but when the transformation end, the physics need to start calculating from that point to the next future points.
  But the boxes of physics and Animation need to stay selected because the functions of the animations starts and finish on any time. and when finish one function of animation the physics need to start.

**Comment by Gerstmann-Bradley** [comment]
Since this is more of blender's issue about its physics.
To me this more seems to be a blender proposal, you may need to go to right-click select instead.

Nevertheless to solve your particular problem within that particular blender file.
You may create another object without physics, but has constraint to the one that has physics.
For example it may copy transform from the rigid body object, while retaining its own ability to rotate.

Indeed, this is just a workaround and doesn't solve problems in all imaginable cases,
but again you should talk with blender dev instead.
Also I wonder how other software, such as Autodesk, C4D, Houdini, handles this question.

**Comment by Netzahualcoyotl** [comment]
The module Animation Node manage the time when one function of Animation Node start and end and when one function of Animation Node ends need let the function of physics start, that manipulation is made of Animation Node not by blender.

**Comment by Gerstmann-Bradley** [comment]
But the core issue stems in Blender design of its physics.
Whether you are using AN or not, you are having the same problem. This issue isn't unique to AN but blender itself.
Also, the previously mentioned workaround is still applicable, by creating an addition object that doesn't involve physics.

**Comment by Netzahualcoyotl** [comment]
Did you can made your alternative at the file please?

**Comment by Gerstmann-Bradley** [comment]
[AnimationExample SHOWN.zip](https://github.com/JacquesLucke/animation_nodes/files/6773405/AnimationExample.SHOWN.zip)

This is using your file.

**Comment by Netzahualcoyotl** [comment]
Ok, thank you for your alternative, I am simulating it, but when the box spinning is down the box does not continue moving about the friction on the floor, is that as supposed?
https://youtu.be/kcPJkPjsgFg

At the end of why a want that functionality is to make conveyors like is made here 
https://www.youtube.com/watch?v=yOXUph9W5Oc&list=PLkjy3Accn-E59daIG9X87pRAb5trbUPYZ&index=10
https://www.youtube.com/watch?v=uO_tuoM5JOU&list=PLkjy3Accn-E59daIG9X87pRAb5trbUPYZ&index=20
I can not find the way how to replace bge using Animation Nodes.

**Comment by Gerstmann-Bradley** [comment]
Sorry, I'm not sure what you did in your example and what you want to do exactly with your examples.

But as mentioned earlier:
> Indeed, this is just a workaround and doesn't solve problems in all imaginable cases,
but again you should talk with blender dev instead.
Also I wonder how other software, such as Autodesk, C4D, Houdini, handles this question.

I can only tell that if you want "**animate and simulate at the same time**",
I think this is really a blender issue instead of AN.
you should rather talk with blender dev about it.

**Comment by Netzahualcoyotl** [comment]
Ok, gracias
