### ISSUE TITLE
Latest build refuses to install in Blender 3.0 alpha from 02/08/2021 in Macos

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#1770]
So I got a MacOS build for Py39, tried to install it on Blender 3.0 alpha, and it gives me this error:

![image](https://user-images.githubusercontent.com/20524718/128011560-7e5f030b-46ed-451e-81d3-2fff95833a80.png)

I'm not MacOs BigSur 11.4, in a MacBook Pro M1.

**Comment by OmarEmaraDev** [comment]
Is that an ARM Mac?

**Comment by juangea** [comment]
Yep, the M1 is the ARM processor

**Comment by OmarEmaraDev** [comment]
The builds we have now are x86, so they will not run on the M1 Mac. Arm support was added in #1753 but we currently don't have any builds because our cloud pipeline doesn't have M1 Mac runners yet. So, unfortunately, you will have to build AN yourself, run Blender under rosetta, or wait until we prepare a build for the M1 Mac.

**Comment by juangea** [comment]
Ok, no problem, I was suspecting this, thanks!
