### ISSUE TITLE
Cycles Material Output Node Doesn't Have a Material Input

### ISSUE THREAD

**Issue by DaMisterBoss** [JacquesLucke/animation_nodes#1863]
I'm not sure why, but the cycles material output node forces you to manually choose a single material to edit instead of allowing for node input. Other nodes allow for an input into the material field, but this one doesn't. I'm assuming this was just an oversight, but it makes it impossible to change cycles material properties (or custom material properties) in different materials without making individual nodes for each of them, which is very tedious and seems to be an easy fix. Hopefully this can get fixed, I'm not sure if there's a limitation preventing this feature.

**Comment by OmarEmaraDev** [comment]
This is by design due to limitations on how the node works unfortunately.
The user needs to select a certain node and socket inside the material, and since materials may not necessary have the same nodes and sockets, the material itself can't be dynamic inside the node tree.
The alternative is to use an expression node and set the value you need manually.
