### ISSUE TITLE
A node that could split an Object List into the several lists that contains

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#187]
It will be very usefull to have a node that could do the same work that the Attribute Input Node does with one object, with a list of objects.

For example when you plug a list of objects on the left you should obtains three lists containing all the locations, all the rotations and all the scales of such list of objects.

Inspired by you work and from others on the forum as o.g. I ´ve started to learn python but I don´t feel confident enough to create such a node by myself. However I´ll give it a try.

**Comment by JacquesLucke** [comment]
I find it very cool that you want to learn python now. Programming is such an empowering skill to learn! :)

About your question:. Yes of course this would be helpful but I like to implement something like that in a more generic way, because I don't want to create each node twice. One for a single object and one for multiple objects. For that I reason I implemented these loops with which you can create the same node you ask for with a few existing ones and with much more control.
This will (hopefully) be even easier after I finish my refactor project but this will still take a while because there  is an extremely large amount of areas I have to work on so that everything can nicely work together with a decent performance and relatively good usability. 

Nevertheless I think creating this node will be a very good learning experience for you! So I think you should do it. Ask me if you have questions.

**Comment by YorsLosilla** [comment]
Well what I was trying to do is to create a list of vertex positions based on a list of objects positions after they have been manipulated inside a node. Which I think it is impossible now because while the list is inside the loop you have to iterate trhoug the list.

The idea is for example be able to create a dinamic spline which points are connecting a set of objects which have been animated inside a loop.

I´ll try to post you a sample file.

**Comment by JacquesLucke** [comment]
This is totally possible by using multiple loops. I have to admit that it is not very easy to manage muliple loops atm but it is possible.

Maybe you can even do it in just one loop but I'm not sure about that

**Comment by og76** [comment]
If a node itself makes sense or not, it does not matter. The exercise is very useful in itself.
I did this starting with the debug node, mostly exploring node, sockets, ui etc, no operation ( #145 kind of on hold ) and then moved to some more useful stuff.

As I would do it:
1.Make a node tree to do what you want. (I think is very possible) That will structure your math/logic and give you the inputs/outputs you need. Matter of design and concept
2.Make a dummy node (no math operations or simple in = out) to deal with ANnode, sockets, buttons etc
3.Put the operation/math/logic in the node, for the real thing...

1+2 are different issues: 1 is operation/logic 2 is nodes/ui. and I think is interesting to explore them as separate issues.

ps
I refrained from scripting till got the AN, that makes it more simple than an addon. Digging into this helped me learn some py script, but also some blender structure. So, keep up..

**Comment by og76** [comment]
oh, and when you make a new node (dummy or not) start by copy an existing one and mod ...
and look into the other nodes that logically are related (as sockets or as math)

**Comment by JacquesLucke** [comment]
Yes I also think you should do it. And of course this node is useful! I just wouldn't put it into master for the reasons I already mentioned.

@o.g.: you might want to take a look at the node code in the refactor branch. I had to change the API a bit to make it more future proof. In my opinion the node code is also much cleaner now, but decide for yourself :)
Keep in mind the the refactor branch has no execution system atm. So downloading it doesn't make much sense for you. For me it is quite helpful because I can fully concentrate on UI first

**Comment by YorsLosilla** [comment]
Thanks for your advices. I´ll give it a try.

**Comment by kmeirlaen** [comment]
Now that the work with sub programs is stable, I think you can easily do it this way:

![image](https://cloud.githubusercontent.com/assets/4618798/10372086/9376263a-6de6-11e5-801e-0e0e59bd6ce5.png)

I hope I understood your question correctly.
