### ISSUE TITLE
groups and loops should have separate node trees (simulating blender groups)

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#189]
**#173 with the refactor and loop/group remodel, should we do this too?**
it is very possible, out of my small research (as follows), but I'd like to know how you see this

**reason**
the problem today is that people connect things inside outside loops and groups. but also, especially in loops, it is not obvious that is forbidden
**with normal grouping that will never happen + the concept will be very clear**

*alternative:  we monitor the network as belonging to the group/loop and do not allow connection
this implies slow (links and sockets..) and may be confusing*

-
### **real groups and loops**

here's a mokup for groups switch (consider loop too)
[AN real groups 2.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsM3FfZS1pbk1CbEk/view?usp=sharing)
it just switches trees as tab would do...
the green/ upper button should replace the tree name 
![g](https://cloud.githubusercontent.com/assets/11709974/9253723/0db3539e-41e8-11e5-89d7-83d630e84ab4.jpg)

the trees names should take priority, as today node do

to have them tied to respective group/loop for refresh and for switch (tab) that is the nice part
[fake in the blend, cause of direct links, but easy to do, I could even try it myself]

**the main issue is manage /monitor the naming and renaming (how does blender group work)**
- in materials when you make a group named Group, a tree with the same name is created. they are tied, bidirectional
- if u go in compositor and create a group named default Group, the tree above gets renamed to Group.001, and also the respective node (callers)

_this means blender might rename the group/loop trees (tested)_
and that blender revolves around the tree name (in AN it's the group input/loop start that matters)

-
### **Structural logic as I see it:** (i'll talk groups, but same for loops)

1. Group creation:
BL default : from menu or ctrl+G . Implies selection. moves those nodes to the group and creates in/out
AN today: add group input/output, consider the tree type as group etc, manual in/out
Proposal : 
> we could use selection (it's like cut-paste), but we could create empty groups also from menu (from caller node also?)

2. Group deletion (ungroup, explode)
BL default : from menu or alt+G . Copy those nodes to the original tree. Keep the group with the nodes inside, eventually it deletes, but I cannot follow ...
AN today: delete the group input, del the group (name) and the tree is not group type
Proposal : 
>copy nodes to original tree, keep the group as is

3. Edit Group (Tab):
BL default : tab in out. the grouptree does not appear in the tree list. graphics with green back etc
(it doe allow multiple input/output nodes, a bug)
AN today: same tree, different tree, does not matter
Proposal : 
>tab in out, also button on the caller/ inside group to switch
caller will ref the group tree along with the group
from inside group, refer the last caller tree that opened the group edit

4. Specific tree behavior:
BL default : 
the group tree is never listed in the trees (no manual renaming)
the group does not appear in manu list when in self 
copy paste self in self (or subsequent children) gives warning [cannot copy Group in tree NodeGroup]
has group input/output nodes (it does allow multiple input/output nodes, a bug)
AN today: works with tree network type group
for output is way better ux
[can by mistake connect things inside/outside group (everybody does it with loops)]
Proposal : 
> allow only 1 in/out nodes, that cannot be deleted. may allow many outputs as today..
group should not appear in menu list when in self
the tree list (header should be replaced by the exit / tab out button)
monitor groups/trees with ANparent attribute (bl does something internal) warning for copy paste self in self tree

**Comment by JacquesLucke** [comment]
Thanks for all these thoughts. 
Making the separation of node networks clearer is definitly a primary goal for the refactor.
Personally I don't want to force the user to put loops, groups etc into their own nodetrees (although they can do that if they want to!) 
I think a single nodetree should be able to contain everything for a whole project. (Makes it also easier to share screenshots)

I totally agree that the separation is unclear atm. My favourite idea to solve that is to use colors. So that every network has its own color which the user can choose.
Removing forbidden links between different network types is for technical reasons much more complicated than it seems to be, so this won't work soon.
I cannot explain my whole vision now because I'm writing on my smart phone and it would take me ages. 

Also I want that the 'future user' can create loops or groups much more easily. Also small loops which contain only one node or so. I think you saw the idea to have a node like a Attribute node just for a list of objects. I plan to implement a operate called Loopify (maybe I find a better name :D) that automatically creates a loop for this and other nodes. This will result in many small networks and it would be ugly to have soo many mini node trees. So if you have multiple larger node trees in a .blend file you cannot easily differentiate them from all the small helper trees.

Btw.I cannot open your blend file atm because I'm still on vacation.

**Comment by og76** [comment]
thanks for the response.
I like the color idea, like today I use frames to "color" a network (but it took a while to know what I'm doin). I was also looking for color ways in the #145 (at the end) remote nodes

however, this loop/group design, **we should discuss further in the other issues like #173**

this one was specifically for tree separation. And I thought it's worth establishing if the case.  I'm not very keen to groups as separated trees cause it's a bit blind approach, but it's familiar ui

ps.
blend does nothing. just has buttons to switch from a tree to another (as arrows show, black to green)

**Comment by og76** [comment]
and have a nice vacation;)

**Comment by og76** [comment]
and this is the other aspect of separate node trees #190 ...
