### ISSUE TITLE
Viewer Issue

### ISSUE THREAD

**Issue by HenryK-codes** [JacquesLucke/animation_nodes#1905]
Hello.
What is happening. I just added up a Read MIDI File node on my node tree. When I move it around, this happens.
https://user-images.githubusercontent.com/106451458/218286735-4379c045-7c75-47c7-9e92-34e81a6b1fc3.mp4
This happens for any kind of viewer node.

Blender version 3.4.1 and Animation Nodes version 2.3.0 is being used to report this bug.

**Comment by OmarEmaraDev** [comment]
I can't reproduce the issue. Does this happen with factory settings?

**Comment by HenryK-codes** [comment]
Somehow it does. I don't know what has been going on.
Does it have to do with my settings? Is this a bug?
If it's not a bug, how is it possible to fix this?

**Comment by HenryK-codes** [comment]
I almost forgot, I am using Windows 11 to report this bug.

**Comment by OmarEmaraDev** [comment]
I can reproduce the issue by changing `Preferences > Interface > Line Width` to Thick. Not sure yet what this is supposed to control.

**Comment by HenryK-codes** [comment]
Turns out that was the reason why the issue was happening. I was able to change the Line Width from Default (Thick) to Thin. It helped, now the issue doesn't happen anymore. :)

I'm not going to close this issue because I don't know if the bug will be fixed for that case. If it won't, then I'll close it.

**Comment by OmarEmaraDev** [comment]
The issue is due to [D15961](https://archive.blender.org/developer/differential/0015/0015961/index.html) and a fix is probably similar to [D15961](https://archive.blender.org/developer/differential/0015/0015961/index.html). Though a similar patch changes the UI scaling in AN in some parts, so I will delay submitting that until I am sure what needs to be done.
