### ISSUE TITLE
Expose node seed as input (maybe optional input)

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#209]
I have this simple node group:
![image](https://cloud.githubusercontent.com/assets/13521338/10122351/b452e66e-6516-11e5-940b-f7d24177def3.png)

But problem is, that every time I use this group , its random vector node seed is the same. I wish I could randomize it too. So I would like to have 'node seed' as available as input. For vector randomize, and number randomize too.

**Comment by JacquesLucke** [comment]
You aren't the first one proposing it but I decided against it because this should not be in the scope of this node. Sometimes you may even need 3 seed inputs sometimes 4 etc. It would be bad design to expose all these seeds as inputs. I think the random number node is even faster with this static node seed value.
![node seed](https://cloud.githubusercontent.com/assets/5881326/10122419/8c52a304-6519-11e5-9f6f-ea3aaeecf94a.PNG)
In the example you have two values which both influence the seed. 
Maybe we find a better way to do this in the future but using the node seed as input is not the way to go imho

**Comment by JoseConseco** [comment]
OK, i can see why it may be redundant. But your example gave me idea how walk-around this problem.
