### ISSUE TITLE
Colors were reset to [0.5 0.5 0.5] when refreshing Group Call

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#210]
Just tweak a bit on the not-very-outdated subtitle importer :laughing: , I found one strange thing: When hitting the refresh button on Group Call node, the colors were reset to mid-gray.

Blend file:
http://pasteall.org/blend/38279

**Comment by JacquesLucke** [comment]
Yes this definitly shouldn't be that way but I don't support the current master anymore as I reworked everything in the refactor.
The problem shouldn't happen in the refactor branch.

**Comment by LeonCheung** [comment]
I see. No problem. Just one little suggestion: Could we have more properties supported on Text Output  node? Specifically **Depth** in my case...  :P

**Comment by JacquesLucke** [comment]
It's already there. Just hidden by default.
![text object output](https://cloud.githubusercontent.com/assets/5881326/10123939/3e0d213c-6547-11e5-87f5-5bc40b5a0fff.PNG)

**Comment by LeonCheung** [comment]
Ah, refactor... OK. I think it's time for me to follow it now...  :)

**Comment by LeonCheung** [comment]
Just tested with the refactor branch, it still happens.

Blend file:
http://pasteall.org/blend/38281

BTW, I think I did translate everything from the master version, but the whole thing seems not working... Can you figure out why?

**Comment by JacquesLucke** [comment]
I cannot find out exactly yet what doesn't work here but here are a few nodes:
- In Loop_SRT you create a new list but you are using the old way that was a bit like a hack. You can use a generator output instead to create a text list: http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2942969&viewfull=1#post2942969
- One expression sais "".join(textList); Instead you can now use the "Join Texts" node
- Also the Loop_SRT subprogram. It doesn't get executed because you set Iterations to zero. I guess you wanted to use go through each line individually? Then create an iterator input (string list as type)
![generate text list](https://cloud.githubusercontent.com/assets/5881326/10125055/2c1f2220-6567-11e5-9cf1-2b9d03b87799.PNG)
 for the loop and not a parameter.

After seeing you node setup I'm still thinking about remove the object list socket... It should be used very rarely because it requires much more thinking from the user side to make sure that all types are correct. Maybe I will limit them a bit. Will see how that can work...

**Comment by LeonCheung** [comment]
Thanks for the guide.  This an improved version totally based on your advices:

http://pasteall.org/blend/38294
(Those contained in frame are the changes)

Good thing is, it finally works. However, I got error:　**name 're' is not defined**  :(

**Comment by JacquesLucke** [comment]
Please take care that you have an eye on the *advanced node settings* panel on the right side. I suggest you put it at the top. Many nodes have some more options there.
For the expression node you can define which modules are needed.

**Comment by LeonCheung** [comment]
I always did, just didn't figure out the new module defining mechanism. Now I think I'm getting closer. :) However, new problems arise:

The old master trick **"".join(textList)** can generate a single text without **["** and **"]** while keeping **\n** sign, but in refractor branch, either the new Join Texts node or the join(textList) trick cannot get rid of them, and lost **\n**. I'm not sure whether this is intended behavior. Just wanna make sure it is not sort of bug.

Master:
![master_join](https://cloud.githubusercontent.com/assets/494788/10135342/a5b2b62a-661f-11e5-8f4c-3fe783491a57.jpg)

Refactor:
![refactor](https://cloud.githubusercontent.com/assets/494788/10135348/ad76cafe-661f-11e5-9106-791be6fcb46c.jpg)

**Comment by LeonCheung** [comment]
PLUS: I can see these **\n** in the Debug node, but I cannot split it by the **Split Text** node with **\n** delimiter in Regexp. It seems regex doesn't work there?

One more thing:

When trying to debug by textblock, I got error:

![text_block](https://cloud.githubusercontent.com/assets/494788/10135532/6f308210-6621-11e5-8d91-727529ed77ba.jpg)

**Comment by JacquesLucke** [comment]
I think this node is a bit unnecessary in your setup und causes the problems with **[ ]**
![append list error](https://cloud.githubusercontent.com/assets/5881326/10135587/80fda13a-65ef-11e5-81ce-7bc84c1e674e.PNG)

**Comment by LeonCheung** [comment]
Definitely right!! And the suprise is that the initial problem (value reset issue) in this report has really gone. Big big thanks to Jacques!

**Comment by JacquesLucke** [comment]
Alright, Then lets reopen and close this again for fun haha

**Comment by LeonCheung** [comment]
Agree. hehe :beetle:

BTW, I played with the new Text Sequence Output node, I think I should make another version based on it. However, the official VSE text strip needs arming a lot. It currently doesn't support font, bold, italic, advanced animation, and a very very simple shadow... 

But let's keep some faith anyway, shall we?  :P

**Comment by JacquesLucke** [comment]
Hehe yes. The idea for the text sequence output node is by Gottfried Hofmann :)
I guess these other features will come within the next few blender releases when people start to use it.
