### ISSUE TITLE
Idea on Subprogram

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#220]
Again, in the case below, you can see that after switching the subprogram preset,  I have to manually switch the text block too. So I was thinking that whether we could control that automatically by kinda logic or switch node, which is very useful to set default/preset values for any subprogram when calling it. For example:

use **SRT_test.txt** if **current_subprogram = SRT to VSE** else use **SBV_test.txt**

![loop input](https://cloud.githubusercontent.com/assets/494788/10239471/9072028c-6900-11e5-8db4-8e341b16d5fd.jpg)

Perhaps the old topic "any data from name" is a bit related?
![name](https://cloud.githubusercontent.com/assets/494788/10239500/246e828a-6901-11e5-820c-dff383b598da.jpg)

 (just kidding :laughing: )

**Comment by JacquesLucke** [comment]
Hmm not sure how this can work.
Maybe you can add another abstraction layer in your node tree. I mean I add another group that does this decision.
Maybe you can even save some nodes by doing so because currently you have many things twice in your node tree. You should maybe make a group that is only responsible for parsing the one type and another group for parsing the other type. Both can share the same nodes to set the texts and colors on the sequences

**Comment by JacquesLucke** [comment]
Maybe we can solve that with a switch (if) node which either calls one or another subprogram. But this won't happen to soon. I will close this for now
