### ISSUE TITLE
"Data from Name" and "Data to Name"?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#221]
Based on recent discussion, I'm thinking a proposal from user side:

![string-socket](https://cloud.githubusercontent.com/assets/494788/10240879/07db6738-6914-11e5-8cc6-81e31f3c2fb2.png)

The new sockets can be hidden by default. Though I use Object data node as the example here, but it really should be more generic to adapt other datatypes such as scene, object group, textblock, sequence, particle system, etc.

**Comment by JacquesLucke** [comment]
The data input node is not the best way to go here because it just works like a reroute node with an input, there is absolutely no execution code inside this node.

I can see that a node that gets the object based on the name can be useful in many cases but that doesn't work for all types you mentioned. Especially the sequence input is different then the others because each scene has its own sequences and the names can appear more that once

**Comment by LeonCheung** [comment]
I see. Hmm, then we might turn to another workaround.

**Comment by JacquesLucke** [comment]
66ab50f5e81b899853cb6eab190eaef91d2ce5a6

The type is fix after creation, but this should not be a problem at all.
![blend data by name](https://cloud.githubusercontent.com/assets/5881326/10244467/b50095e2-68ff-11e5-856b-415e71cdc3e8.PNG)
