### ISSUE TITLE
Custom Props Failed to Update

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#222]
Please see [this](http://pasteall.org/blend/38380) file, the refactor version of the dynamic parenting mentioned at #214 (but let's just ignore the rendering issue here). I really don't know what is wrong in it. Thanks.

**Comment by JacquesLucke** [comment]
I guess its a typical misuse of generic sockets. You should always try to use the appropriate socket types.
![generic socket misuse](https://cloud.githubusercontent.com/assets/5881326/10262107/d1d886a0-69ba-11e5-8dc6-308ce5a583ef.PNG)

The problem here is in the switch node. If the condition is True the correct vector will be the output. But is it is false you will get None. Because the default value of a generic socket is None. Instead you should use a vector switch node here
![correct use of generic sockets](https://cloud.githubusercontent.com/assets/5881326/10262137/a023ecb6-69bb-11e5-8b71-368907a9b172.PNG)
If the condition is False here, the default vector will be used and not None

I just found that whenever you have a convert node that converts to Generic, you are doing something wrong..

**Comment by LeonCheung** [comment]
I used the convert nodes here as intended, because I only wanna record the if True value in this case. This maybe a bit hacky, if it is a bug, then it is a really nice one lol. But it did work sometimes, even in refactor version...

**Comment by JacquesLucke** [comment]
As long as the condition is true or the attribute you want to output excepts None this can work, otherwise not.
I mean if you goal was to raise an error in the attribute output node thats fine but normally you don't want that :D

**Comment by LeonCheung** [comment]
Haha, yes, that error was a friendly one this time.

[Here](http://pasteall.org/blend/38382) is the previous setup, it is an almost-working one I should say (at least visually). But the problem is the children didn't stay at the ID Key transformation when on initialization frame (Frame 1). I'm gonna pulling my hairs off... :sob:

**Comment by JacquesLucke** [comment]
Quite impressive that you dot so far anyway. I mean you are trying to do something that is definitly not in the scope of this addon, because it is more simulation than animation (the current frame depends on the frames before)....

**Comment by LeonCheung** [comment]
Animated parenting is really useful as you can see. I just thought it would be possible with AN. (Anything is possible, right? :P ) . There is an addon called [Dynamic Parent](http://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Animation/Dynamic_Parent) can do this pretty well. The mechanism is simple, which is by setting keyframes and constraints. I did try to translate it into AN, but finally gave up, because I found the "Set Inverse" button **Child Of** constraint needs to be upated everytime when switching parents. I just didn't find a proper way to do that. That's why I have to try the boring matrices here.  :)

**Comment by JacquesLucke** [comment]
Unfortunally only everything but simulation is possible..

**Comment by LeonCheung** [comment]
OK. You win....

**Comment by JacquesLucke** [comment]
...
