### ISSUE TITLE
debug line number in script node

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#223]
I wish error message in script node, could display line number when.

**Comment by JacquesLucke** [comment]
Maybe we can get this somehow. The problem here is that the core of animation nodes takes your script and modifies it internally to make it work with everything else.

![modified script](https://cloud.githubusercontent.com/assets/5881326/10281193/032182b6-6b73-11e5-97b2-cf7a9bc2a424.PNG)

In theory I can compute the original line number somehow but  I'm currently doing something different

**Comment by JoseConseco** [comment]
ok. How about printing line code with error as string itself?

**Comment by JacquesLucke** [comment]
Just found a way to find where the error is (although it's not very nice^^)
1. In the advanced settings of the script node disable debug and interactive mode
2. When an occures the node tree stops to work now but you will get an error message with line number in the console
3. Click on the script node, hit spacebar and search for "Print Execution Code"
4. Look for the line number that was printed in the error message before.

**Comment by JoseConseco** [comment]
heh, thanks. Seems to work

**Comment by JacquesLucke** [comment]
I didn't find a nice solution for this one yet. I'll remove it as v1.5 target for now

**Comment by JacquesLucke** [comment]
we have this now
![screenshot from 2017-04-21 23-19-59](https://cloud.githubusercontent.com/assets/5881326/25296543/1532bb22-26e9-11e7-8cb3-7b21b5973dca.png)
