### ISSUE TITLE
[Suggestion] Adding Bounding Box Center Output

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#268]
It is sometimes useful to know where the bounding box center is. Can we have one?

Currently I have to generate it by a bunch of nodes:
![bboxcenter](https://cloud.githubusercontent.com/assets/494788/10464959/05971c24-721f-11e5-8853-e24a0ff24159.jpg)

**Comment by og76** [comment]
What center are u looking for? 
- the *object center* is the very location of the object as obj transforms in or matrix in (loc)
- the "middle of the box" *u can get by point* 0/6 (the opposed corners of the bbox)

![bboxcenter](https://cloud.githubusercontent.com/assets/11709974/10465956/3d36cc1c-71fa-11e5-98c3-131e3a94fa42.PNG)

**Comment by LeonCheung** [comment]
Thanks for the tip! Though I think it's even better to put it as a simple socket...

**Comment by og76** [comment]
yes, but then there are lots of other info, like center of the faces, dimensions etc 
u can get them like above..
(well, actually object dimensions is object.dimensions in attr (world space, transforms included) it's also precalculated)

the trick with bbox is that it's precalculated by B, so for a complex mesh you don't need to calc again the min max xyz of  10 000 verts, maybe several times.

I also proposed in #262 to have option for local/world, because you can then compare the original (mesh) sizes with the transformed one. Very useful for align and scale ..

**Comment by LeonCheung** [comment]
Yeah, Min / Max is very useful indeed.

**Comment by og76** [comment]
min xyz = point 0 xyz,  Max xyz =  point 6 xyz
(in object/mesh space once the world off option will be there...)
