### ISSUE TITLE
[Suggestion] "Create from Selection" Extension

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#289]
Allow "From Selection" for Spline List node and Object Group List node, just like what is done to Object List.

P.S.: For the latter one, I've no idea what's the best way to pick group from selection: Is it enough by only selecting one object from each group? Or have to select all objects in all groups? And what if a object is in more than one groups?

**Comment by JacquesLucke** [comment]
https://github.com/JacquesLucke/animation_nodes/commit/ae0760bef2d2b18291053c3948f6413412cc5926

Support for 'object groups from selection'.
Also minor workflow speedups so that you don't always have to go into the advanced settings to use the 'from selection' operation when there is now input socket yet.

(I don't want to have this button there the whole time...)

**Comment by LeonCheung** [comment]
Tested, promising. :+1:
