### ISSUE TITLE
Euler Math?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#294]
![euler math](https://cloud.githubusercontent.com/assets/494788/10869050/cddc1ccc-80dc-11e5-8b73-7aecab22a414.jpg)

When doing math for euler, it seems we have to use quite a bit of converters.
Maybe there is way to make it looking a bit more compact? An Euler Math node or mode, perhaps?

**Comment by JacquesLucke** [comment]
yes. Euler Math seems to be the way to go here..

**Comment by og76** [comment]
Already done. But besides +/- there's not much to it. I will explain later.
But yes, is needed.
The Quat math is another thing ... way more interesting

Dum, 1 nov. 2015, 15:18, Jacques Lucke <notifications@github.com> a scris:

**Comment by JacquesLucke** [comment]
ok. Can you please test if the node works in all cases or if some operations are missing?
I didn't reimplement operations that only make sense with vectors. If you need these you should convert to vector.

**Comment by JacquesLucke** [comment]
![euler math](https://cloud.githubusercontent.com/assets/5881326/12401377/4051737a-be26-11e5-8d18-20b3533cd366.PNG)

**Comment by og76** [comment]
1.
Yes,  there is an issue with *multiply and divide*

For these we need to convert back and forth radians and degrees, so that the visual feedback of the euler socket corresponds to the expected operation:
- if you mul 90 with 2 you expect 180, but now radians will mul pi/2 with some 0.00xxx 
- to figure that out, the user needs to know how this works
- to solve that you have to add extra nodes. Always

So, to solve this, I added 
- a useDegrees prop that by default is True
- convert to degrees, multiply , convert to rad
- an advanced button (with and operations with degree type so that only appears for these two)
that should stay always on. But if someone in this world is using radians input as a preference in blender, that should be off to get back to the normal op

in the pic you can see the difference with the proposal above (and useDegree stuff) and old below
![euler math](https://cloud.githubusercontent.com/assets/11709974/12406788/08554216-be59-11e5-9918-3d0ba0930663.PNG)

-

2.
I don't see why you use vector / euler conversion 2 times each, it does not really help besides + and - and adds unnecessary float ops to the node.

So *I propose a direct mathutils.Euler variant*, that otherwise in code style/ lines efficiency is pretty much the same. I think it matters as this is a node prone to be used in loops and many times.

Please correct me here if I'm wrong.

-

3.
Sorry delayed this node that much, this issue would have been clear in the beginning
However, I think the eul math should go in the menu under euler, as there is also a quaternion math
Not a big deal now, as there is more to this menu, especially for quaternion. 

On principle those are in my working test branch, but they are not for 1.5 and I have to see how updated they are to propose them too.

**Comment by LeonCheung** [comment]
Nice guys!

**Comment by og76** [comment]
and the variant for current master, it's so basic it should just be there
no need to wait for 1.5 or push people into using that while giving examples

please test, I did, but who knows ..
(the only difference is @keepNodeLinks)

**Comment by JacquesLucke** [comment]
I merged it. The advantage of using keepNodeState instead of keepNodeLinks is that the first one also tries to keep the values the sockets had previously.
E.g. previously the the socket values int the math node were reset to 0 and 1 when you change the operation.
I hope we don't get merge conflicts later -.-

**Comment by og76** [comment]
**And the brother quaternion math, for master version**
I guess for 1.5 the diff will be just same as euler math .. and not doing another issue ..


Some explaining:
- this also includes inverted and conjugated (only -xyz) that I wanted as separated nodes, but there is no point now
- this is a bit more abstract as quaternions are for direct manipulation. This leads to some functions that seam very much the same, or ther result is not always quite as expected. You have to **look at it as in between eul and matrix**
- the + and -  have some similar friends in combine rotations and rotation difference, still I left all ops in place
 - *Combine (quat * quat) works very much like matrix * matrix*
 - *Rotational difference is probably the really useful one here* it gives a better rotation - rotation and u can further use it as quat, eul etc
- cross is a bit weird, not always quite like vector cross
- normalize and scale, well quat has also a length, so it's not like euler scale ..
- invert and conjugate differ as conj keeps W and only negates xyz, wich may prove more controlable

**Comment by og76** [comment]
ok, so for the conflicts,
I'll propose for master and should pull from there and change in 1.5? hm

**Comment by og76** [comment]
and a complement of the math 
**quaternion combine list**
this works very much like the matrix combine node, for quat, 
(actually using the same  q*q *q in inverse order)

-

don't mean to pollute this, but that's about it with the rotations ops, eul/quat stuff

**Comment by JacquesLucke** [comment]
so I merged some of your pull request, only one had a small typo that should be fixed first.

I also merged the master branch into AN-v1.5 again and resolved the merge conflict. It was only the single line as expected :)

**Comment by og76** [comment]
what typo?

+ see #367 to finish with rotation stuff (for now)

**Comment by og76** [comment]
ok, sorry, quaternion blind ...
