### ISSUE TITLE
Break loop failed partially

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#300]
Hi, just wonder why it failed on one of them.

[Example File](http://pasteall.org/blend/38941)

And, I want to have them stop at y=10, but still failed with such setup. Why? Thanks.

**Comment by JacquesLucke** [comment]
Well, the loop does stop but only after all other (non-loop-specific) nodes or executed. 
But I agree, it is still a bit hard to see when the loop will stop exactly ..
Problem is that the normal nodes have to execute first, because the "Loop Break" node depends on them .I cannot simply put it in the middle of execution.

**Comment by LeonCheung** [comment]
So can I imagine it like the gun-bullet situation? You mean one can stop pulling the trigger, but cannot stop the bullet in the air. Right?

**Comment by JacquesLucke** [comment]
yes, sounds like a correct, but strange, explanation :D

**Comment by LeonCheung** [comment]
Alright. Get it. -_-
![bg](https://cloud.githubusercontent.com/assets/494788/11324494/30da66c0-916e-11e5-9bd5-d449a0387087.gif)

**Comment by LeonCheung** [comment]
Hi Jacques, just want to confirm if the attached case shows is the same problem here?

http://pasteall.org/blend/40078

In the file I tried two ways for the same result for comparison.

**Comment by LeonCheung** [comment]
Hi Jacques, could you confirm it? Thanks!

**Comment by JacquesLucke** [comment]
ah sry, I missed this one.

Yes it's the same problem. Each loop is executed at least one time.. in your case this means that one loop will overwrite the other.
