### ISSUE TITLE
"Get Spline Samples" not work for many segments

### ISSUE THREAD

**Issue by Leroy-X** [JacquesLucke/animation_nodes#316]
![1](https://cloud.githubusercontent.com/assets/13515498/11031986/3e7417f0-8713-11e5-9c18-c4a8fded5685.png)

you can see, the "Get Spline Samples" only sampled for one segment, but the spline include three circles, only one have sampled. hope you can fix : )

**Comment by JacquesLucke** [comment]
Well, this is intended. If you hover over the spline input the tooltip sais that only the first spline on the curve object will be used. You will have to use the splines from object node + three get spline samples nodes + one combine vector list node (or use a loop with a generator output..)

Btw: you can speed up your nodetree dramatically by taking the get spline samples node out of the loop. Currently the spline is sampled 200 times. You will have to create a new "Vector List" parameter for the loop then (can also use iterator, depends on your goal)

**Comment by Leroy-X** [comment]
thanks your replay, use the splines from object node + three get spline samples nodes + one combine vector list node , it worked good, but if have many segment will not hand for use, so I test others way, like flow image, I don't know where wrong , only worked for index 1, the loop is very strong, very hard for me :);

other way, create list from selection is lost....don't understand for https://github.com/JacquesLucke/animation_nodes/issues/289

![3](https://cloud.githubusercontent.com/assets/13515498/11033754/c3530938-8720-11e5-9322-ebe81b5fd62c.png)

**Comment by JacquesLucke** [comment]
Let me try to explain what you node tree does:
1. Create a list with 36 instances
2. Create a list with 3 splines
3. Iterate through both lists simultanously -> the problem here is that both lists should have the same length, otherwise the loop will be executed n times, with n being the smallest length of an iterator input (n = 3 in your example)
So the loop will be called 3 times with the following inputs:
First time: Index = 0; Object = Cube1; Spline = spline1
Second time: Index = 1; Object = Cube2; Spline = spline2
Third time: Index = 2; Object = Cube3; Spline = spline3
End, because there is no spline left over.

As you can see the other 33 objects aren't moved at all, thats way they are still at their original location.
Also you notice that the 3 objects that were moved have slightly different positions on the spline. That is because the index was 0 for the first object and 1, 2 for the others.

Does that help?:
![sample multiple splines](https://cloud.githubusercontent.com/assets/5881326/11033922/937ad3a0-86e7-11e5-8e21-748d0f036211.PNG)

**Comment by Leroy-X** [comment]
WOW, I see why I am wrong , it is one for one, very thanks your explanation, and I don't know the Vector List could extend to out of the loop, much more clear than before, thanks your screenshot, the image is much more easy to see than the text(My poor English) :+1:

**Comment by JacquesLucke** [comment]
Great :)
So if you don't have more questions you can close this issue :)

**Comment by Leroy-X** [comment]
Thanks :)
