### ISSUE TITLE
[Feature Request] Debug Length

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#321]
When debugging lists, it would be cool to show its length as well. (Sort of a length info feature? Or maybe a switch or a separate node?)

I found sometimes it is a bit boring to add many many Get List Length nodes first, just to know what's the lengths are...

**Comment by JacquesLucke** [comment]
I work on that right now. 
It will be in the Debug Drawer node

**Comment by JacquesLucke** [comment]
![debug drawer](https://cloud.githubusercontent.com/assets/5881326/11147586/41a46e32-8a17-11e5-9e4f-02439eacff5c.PNG)

**Comment by LeonCheung** [comment]
Cool! How did you know that I have been waiting for the show indices button as well? Thanks a lot for the fast work!

**Comment by JacquesLucke** [comment]
haha I wanted them as well. But they didn't fit into the 'design' before. No everything should work like charme. Tell me if something is broken still.

**Comment by LeonCheung** [comment]
So far so good. :)
Btw, since there are several debug nodes commonly used, maybe we could list more debug node on the pie?

**Comment by JacquesLucke** [comment]
I prefer it like it is now because having multiple 'debug directions' in the pie would be a bit overload for such a simple operation. And putting two buttons at the bottom isn't so nice as well because it takes longer to insert them because you have to move the mouse more carefully.
Also in most cases the simple algorithm that chooses which debug node the user might want should be good enouph in most cases.

**Comment by LeonCheung** [comment]
Yep.
