### ISSUE TITLE
[Suggestion] Keep space character when using Separate Text Object

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#323]
For cases like setences, it should be kept. Currently we lost it.

**Comment by LeonCheung** [comment]
Oops, I think I can see why. :)
However, just wonder is there any easy way to arrage several words on a spline while keeping the word space, similar to what the "Text on Curve" feature does:

![an text arrange](https://cloud.githubusercontent.com/assets/494788/11151261/12b87fa0-8a67-11e5-9335-533339526432.jpg)

Now I can think of a workaround, but not an "easy" one...

**Comment by JacquesLucke** [comment]
Hmmm yes. This is quite a bit more complicated than it seems first -.-
I will come back to this suggestion later.

**Comment by JacquesLucke** [comment]
I also don't know an easy way to do that atm..

I have a workaround that kind of works (the spacing is better, but still not perfect)

**Comment by LeonCheung** [comment]
Hmm, yes, I can see it could be difficult, unless a specific functional node, but that's another topic, I'll close it for now, thanks!

**Comment by og76** [comment]
this is the way to do exactly that:
[text_on_curve1.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsaXpuOHN2TUtaVFE/view?usp=sharing)

fwiw, I think this should not go inside separate node (already too many things there)
because it can also be about arrange on curve based on object dimension etc, not just text

**Comment by LeonCheung** [comment]
Oh, right. it seems cool! Thanks o.g. :D
