### ISSUE TITLE
Custom Attribute metadata

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#324]
Just wondering if this is actually possible with AN at the moment: assigning user own custom attribute that gets carried around.

Let say a Point in a Mesh. We create our own custom Vector Speed maybe call it vspeed. Can I then create a node that continue to caculate vector acceleration?

I was referencing Houdini in this case.

Also, with current node sets, is it possible to Set Vertex Color per polygon face? I tried using Set zvertex Color but it seems to work on an object only?

**Comment by JacquesLucke** [comment]
Sounds a bit like you want to do a 'simulation'. AN isn't really made for that. 
The execution at a specific frame should never depend on the frames before. It is also hard to realize that. AN is very deterministic in that regard.

Nevertheless, you can use custom properties of objects to store custom data over time. To access them use the 'Object Attribute Input/Output' nodes.
Later you can maybe even use the ID Key system for that. It is already capable to do that but the node interface is still missing.

As I wrote you in the mail, vertex colors are kind of difficult... There is no easy way to do this yet.

**Comment by og76** [comment]
Yes u can have that in a way. And it's not always simulation.
(The issue with simulations is where you need to play all frames to get to that, just like particles etc. and I did that too but it's no cache like particles etc.)

-

However, for velocity, I showed several ways in the examples of *distance traveled to wheel rotation* and there is no simulation there.
It does imply that you have keyframed motion or spline based motion, so that we have the whole motion to evaluate without moving the scene to each frame.

here's an example:
for keyframed, it's important to see advanced panel for object transforms input
[speed_and_look_ahead_keyframes.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsYnhad0hVckd0ZmM/view?usp=sharing)

for splines it's even simpler, and could be driven by AN too (I use the constraint here)
[speed_and_look_ahead_spline.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsZnZKcVhSdkxWOFU/view?usp=sharing)

-

for custom props per vertex or other not obvious items, you should build a list with respective props or pair of index and props etc. That list can be saved in a custom prop per obj /scene etc
I'll give you examples of that if u want.
(And yes, even a vert velocity can be calculated sometimes..)
