### ISSUE TITLE
New possible nodes for dealing with materials

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#326]
1. Material Input
2. Material List
3. Material by Name
4. Filter Material List by Name

And, new input sockets should be added for that:

![new socket](https://cloud.githubusercontent.com/assets/494788/11201975/51437f4a-8d1e-11e5-8d10-229a2e8f6e9c.jpg)

All above could bring far more possibilities on material animation control. (if it wouldn't crash Blender :smiling_imp: )

**Comment by JacquesLucke** [comment]
while this is possible for the viewport color node, the cycles material output is a bit more difficult because not all materials have the same nodes.

**Comment by LeonCheung** [comment]
True, it would mainly be used for very goal-oriented control, such as multiple materials with the same (or nearly the same) setup, but want to control one or some of them to bring variations.

I think this one could a bit related to what I'm talking about in my last issue report. Maybe I should try to bring cases to show the importance of making single user for materials on each object (text or mesh).

**Comment by LeonCheung** [comment]
All in all, they should be aimed at changing material datablock(s) itself. Imagine this case: during frame 1-50, we use mat_water for the object (on material slot 1 maybe); during frame 51-100, we change it to mat_gold, and so on, and so on. This cannot be simply done by using tricks like object index. It needs a replacement on the material slot.

**Comment by og76** [comment]
for the example above we have character properties that replaces material by slot index. 
(So you have to first assign all 5 materials to a slot (01234) and then swap by index)

but then there is the issue of user/fake user for all 5 materials, when u close Blender...

**Comment by LeonCheung** [comment]
Yep, but it only works when all materals has already been assigned to the object, it's a swap behavior, not replace. What I mean is a way to replace material of specific slot.

**Comment by og76** [comment]
I agree that some material nodes should be there, I just wonder how they should be.
- the material index, in the case of a mesh would be equivalent to set material on polygon (instead of character..), the opposite of polygon material index in poly info.

- also setting a material may go for creating a slot and assign to it, cause sometimes there is no slot there for instances or so.

- there is always the issue of user/ fake user for materials not used . If u assign them to slots they are used. But yes, it's not the most convenient for all cases.

(as for switchin water, gold etc you can always have 5 setups in the same cycles tree and just switch some mix)

I still think that we have this problem cause cycles does not allow other per object props. (That's why for simpler graphics without realism I use BI that has per object color..)
