### ISSUE TITLE
[Long-term Feature Request] MIDI-driven Animation

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#332]
I think it would be extremely fantastic to create MIDI driven animation with help of AN, which will surely rock the whole community, again.

A few similar ideas to explain what I'm talking about:
[BA thread 1](http://blenderartists.org/forum/showthread.php?195434-MIDI-Driver-music-driven-animation-creator)
[BA thread 2](http://blenderartists.org/forum/showthread.php?378208-Add-on-AddMIDI)

I decided to call it "long-term", because it is not very likely to happen in a short period (or not?). But I can see it can be highly possible to implement (or not?). Anyway, just throw it up here. FYI  :)

**Comment by JacquesLucke** [comment]
Yes this is more long term...
You aren't the first one asking for this.. Unfortunally I don't know that much about MIDI
Can you maybe create a small mockup how a node system can possibly look like when it is implemented?
Beside that it seems so that I will need an external library for midi..

**Comment by LeonCheung** [comment]
Well, ideally it hasn't to be midi acturally. The reason I'm talking about midi is that it may easily provide "markers / dots" (sort of a list?) to tell Blender's animation editor (such as NLA) when to put pre-made actions on the track for performing (or say, to automatically generate or repeat unit action strips on the track based on music rhythm, instead of manually puting them on one by one, which can be a horrible work).

For example, we made two actions, one is hit_drum_a, another one is hit_drum_b. You can imagine how convenient the "marker" lists can be generated by reading from midi. But for wave data, maybe we can generate two lists with help of your [Audio to Markers](http://blenderartists.org/forum/showthread.php?367920-Addon-Audio-to-Markers) addon (hopefully), (manual part). Then AN can arrange / repeat the two actions on different nla tracks, based on the two lists.(procedural part).

Of course we need to allow setting frame offsets. I mean, the hit_drum actions should start performing "raising hand" part before we hear "bang". (for other kind of instuments it may depend.)

Imho, the key is **how to effectively generate ready-to-use marker lists for each note of instruments**.

That's my 2 cents, very primary idea by now. :)

**Comment by enzyme69** [comment]
I like this idea a lot, I have similar thought the other day actually.

If you happened to have an app like Auxy or iDS10 on iOS, there is this kind of interesting MIDI concept that might be able to be implemented using AN.

We can start simple. Let say, normally, in MIDI, we have BEATS. Let's do 8 or 16 BEATS maximum.

MIDI can have multiple layers of [0,1,0,1,0,1,0,1].

So the beat basically keeps on LOOPing. AN is already doing that using "Repeat Time" LOOP.

MIDI is really "simple". Just a matter of ON and OFF, and putting beat on the 8 slots or 16 slots. 

DURATION is probably something that is more tricky.

Anyways.... I actually made a setup the other day, out of curiosity, just something like this:
1) I have an object
2) I want that object to move into 8 different positions in my premade 8 XYZ position in space.
3) I use LOOP and I manage to make AN to drive that object to move like this:
A > B
B > C
C > D
D > E
F > G
G > H
H > A
... and so on.

You got the idea. Since this is simpe, in a way, the object go from A to B, and the next is from B to C, the pop is not visible. 

I actually use LOOP and the duration was set the same for ever beat. I tried "Random" Duration and that is sort of working.

BEAT > PAUSE / NO PAUSE > NEXT BEAT.

BEAT and DURATION and the LIST what animator can worry.

If the beat is 8 in total, or 16, or more or less depending on user preferences, users can then simply supply LIST that they can LOOP.

LIST of ANIMATION can be from MDD cache. That is what I have in mind. I talked a bit in my latest Blog Article.

Blender's Action... I am not so familiar with. Actually if the NLE works with Animation Nodes, it would save energy and complication having to learn another concept.

**Comment by enzyme69** [comment]
So... in summary the elements needed:
1. Main Time Looper (probably Blender Playback Time Line)
2. Each object needs it's own Time Loop 
3. ON and OFF BEAT (maybe Animator wants to turn of certain action)
4. LIST of ANIMATIONS as BEAT
5. DURATION of Animation, per BEAT

I think Animators are mostly thinking in term of keyframing and anim curves / f-curve. Making animation into animation Block or NLE is already a headache for some animators.

In procedural animation, on the other hand, we tend to just work on elements like XYZ positions. Well, at the very basic anyway. We could draw Anim-Curve, but like I asked Jacques a while ago, it's not easy to imagine how to connect Curve A, Curve B, Curve C, and make it into a single animation.

AN can already do looping offset animation for instances, which is cool. But I think Multiple f-curves and animation keyframes for each controls.... are a big headache.

If you happened to jump into Fully Node Based software like Houdini, it has MIDI in mind, and it goes really weird and complex very quickly. It's not very animator friendly =_=

With AN, however, I believe it was built to be Animator Friendly (right?).

**Comment by enzyme69** [comment]
I was quickly reading this and got really interesting... It has such a big potential. I use iOS app a lot and sometimes I wish I can really utilize this iPhone for Blender :p 

http://www.jpfep.net/pages/addmidi/

Anyway, thanks Leon for pointing to this.

What is the easiest way now that AN can receive keyboard or MIDI input?

**Comment by Clockmender** [comment]
Hopefully his thread is not dead yet!

So on the assumption that it is not.... There was a script for Blender 2.49 that converted MIDI to a series of points on a time-line that one could use to drive animations - I used this to drive Empties. Having run the script in 2.49, and assigned each note to an empty, I then saved the file and opened it in latest Blender - this gave me F-Curves for the Empties that I could then use to animate Keyboards, Drums, Guitars and even a Violin!

The original script is here http://blendit.xaa.pl/index.php?p=middrv&l=eng

along with the manual, screenshots, etc. I have downloaded the script if anyone wants it.

I used it for various projects including this one:

https://blenderartists.org/forum/showthread.php?378659-The-Patent-quot-Clockophone-quot-Erkinator-amp-Honey/page2

In posts 29, 51 & 105 there are videos of my progress. I don't know if there is a chance of someone looking at the script and seeing if it could be used in AN - it uses no external libraries as far as I can tell. there are lots of post in which I have described how I did the animation from the Empties as animated by the script in Blender 2.49.

Maybe this would provide a route to  answer...

Cheers, Clock.

PS Nive to know others want this feature!

**Comment by LeonCheung** [comment]
@Clockmender Nice try. You called it "Musimation", maybe you are the fan of the legendary [Animusic](http://www.animusic.com/), too?  :)

**Comment by Clockmender** [comment]
^^ Exactly!

So I had an idea - if we can write a script, or take the bits out of the one I posted, that makes a list like this from the midi file (I think one channel for now):

[1,0] [10,1] [15,0] [21,1] [30,0].......

Where the bit in each brackets is an item in the list and is the frame number and value, separated by a comma. 1 represents "Note On" 0 represents "Note, Off" for each note played in the midi file.

So this note is off until frame 10 then on until frame 15 then off until frame 21.... you get the picture!

It would be good to know the beat timing of the midi file so we can set the frame rate to fit it - that way notes always go on or off on a frame.

We then need a script that looks at the frame number from the "Time Info" node and looks at the first item in the list (search index is 0) - it get a 0 as the value so the note is off, it also looks at the next item in the list and sees that the frame is 10 - when it gets to frame 10 it increases the search index by one - so now it is comparing item 1 with item 2. It also looks at the value and sets this to 1. It now sees the next frame change is 15, so when it gets to frame 15 it increases the search index by 1 and sets the value to 0. Am I making any sense here? The output value will be used to drive an object representing the key. We will need a list making for each note played in the midi file. I think we should stick to one instrument first, keeps it simple. We then need in Blender to match the list against the note from the piano to get the right key playing for each list.

A refinement would be to make these lists into a list of lists (the "Midi Note List") where there are always 88 items, each representing the keys on the piano. The script would not process any list that just has one item; [1,0] in them (list count is 1) - this would set that note to be unplayed the whole song. The script would then only process the sub-list if it's list count was greater than 1.

I tried to do this with Animation Nodes, but created a loop - D'Oh it don't work!!!!! So can someone write a script to do this? Then I can test this on a made-up list before we try to get the overall list made from the MIDI file. The output from the script needs to be note index value and note value (0 or 1) on a per frame basis. So it could operate more than one note on any given frame.

Anyway to demonstrate how it might work, I made this blend file using a Sound Bake as the input rather than the Midi Note List - I put Empties in for all the spectrum, but just a few keys, there are two animation node systems to run these two sections, plus a setup group.

Here's the Blend file: 

[anim-test_7.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1308480/anim-test_7.blend.zip)

I am very happy to explain this further if anyone wants to take it on. I think we could try a simple approach and see how it works. I can write out a full description of the scripts requirements if you need it, just contact me so we can do this by email - not sure how to do this on here...

Cheers, Clock.

**Comment by Clockmender** [comment]
Then I had an even better idea - get the "MIDI Bake" node to make a series of Empties for each note played in each track - then generate an F-Curve for each empty, based upon the MIDI on/off positions and use that to animate anything!

I shall post a blend file with a set of empties generated using the old 2.49 script and AN only to get the animation of the 88 key keyboard. Yes, I have already done this, but no, it is not ready to post yet and I am away for 12 days in Russia! So, if they let me out, I will finish the file and post it. It is the first guitar solo from Comfortably Numb, with backing instruments. I played it all on my TMK88 keyboard plugged into my iMac through an iRig and recorded in Reason (https://www.propellerheads.se) - then I added the other instruments, the bass is my own electric bass played into a Reason Audio channel) - then I got silly with the effects and produced the sound and MIDI files. I loaded the MIDI file into Blender 2.49 and used the old script (it's a bit flaky, so I have to clean the F-Curves up a bit) to get the driver empties - these just move up 1 unit in Z when the note is on. I saved the file and opened in in 2.79 to do the rest.

I then mapped these notes to the 88 keys on the keyboard, using their name (all driver-empties are named a3, g6, etc. and all keys are named a3_key, g6_key, etc.) and all the rest is done with AN. I had to write my second ever Python script to do the mapping. Hopefully we can get a Node that produces the Empties automatically from a MID file....

The process needs a little refinement and optimising, but I am getting there with a method of integration that caters for **any** type of MIDI driven animation. I don't like the two object lists I had to make as seen below, but the mapping tool will allow me to use "object groups" to select the notes and keys groups so they don't have to be in the same order - what the script does is to tell the node Tree the index of each note played on the keys list, so they map correctly. I noticed that the order of groups of objects changes sometimes when you quit the project, or Blender, then re-open it...... grrrrrr!

Here's a picture, I like pictures:

![screen shot 2017-09-19 at 17 19 37](https://user-images.githubusercontent.com/29657804/30603240-d6645d1e-9d5e-11e7-8396-74d2a4ad7bd9.png)

Cheers, Clock.

PS. Let me know what you think to this please.

**Comment by Clockmender** [comment]
If anyone is still reading this..... I have written a script in Blender that reads a MID CSV file - yes I have to convert the file to CSV format, but there is a nice little programme here:

http://www.fourmilab.ch/webtools/midicsv/ that does that so simply.

The advantage of doing this is that Python reads the CSV file **easily** without vast amounts of code to read the generic MIDI file, and it is easy to understand the format once in this form.

My script reads the file and creates a set of control empties that move up one unit in Z when there is a Note-On event in the MIDI file and back to Z = 0 when the Note_off appears. It generates a set of empties for all notes played in the midi file per track, so I have taken into account multi-track files. All other events are ignored for now - can't see where I would need them and it does not use the note velocity - yet, I will add that later after further testing. These empties fit into my MIDI AN Node Tree for the animations.

The script is version 1.0 (Prototype) at the moment and needs more error checking, optimising, etc.

Cheers, Clock.

**Comment by unity2k** [comment]
I would love for you to make a thread about music syncing in Blenderartists.org and post a video showing your workflow. Not only could others benefit but I'd have a better place to follow this particular development within AN.

**Comment by Clockmender** [comment]
Hi, I am not so good on doing videos - I end up losing my way and swearing, but I will happily open a new thread in Animations on BA, or hijack my own new one here:

https://blenderartists.org/forum/showthread.php?438780-Sound-Bake-Animation

And add a detailed description of the workflow and processes. As an aside, could you point to a good resource to make an Animation Node for this MIDI script? I have never tried this before. I guess I need a button to select the MIDI file, then some parameter boxes, like "Use Velocity" (I have now added this to the script, so the piano keys go down a smaller amount if the note velocity is lower, my keyboard, a StudioLogic TMK88, passes how hard/fast I press the keys through to Reason DAW and hence into the MIDI file), the Easing value - this slopes the F-curves so the notes go on over a small frame amount - I can use fractions of a frame in my script. there may be one or two more, I need to develop this a little. then an Execute button to run the script - this generates the Control Empties that I use to drive the animations.

I think that trying to read a MIDI file direct will be a real pain and a huge amount of coding - someone has already kindly done the MIDI to CSV work, so I think I would like to use  that, it keeps my script simpler.

Next on my list - getting my Robot to play guitar and drums from MIDI - I did this with keyframes (before AN), etc but it would be nice to do this with AN. There are videos on my Youtube channel of this work. I think this is the URL:

https://www.youtube.com/channel/UCfOCIvThm1sCoG0NqZkgaAg?view_as=subscriber

Cheers, Clock.

**Comment by enzyme69** [comment]
Interesting conversation that probably can be brought to live using Sonic Pi 3 with IO MIDI and Python Sonic OSC.

MIDI and OSC has been in my mind for quite a while.

**Comment by OttoDan** [comment]
Dealing with a similiar situation that contains midi triggered drum animations, it's perfect to see Clockmenders AN-Nodes repository, This conversation is indeed helpful :)

**Comment by virtualturtle** [comment]
@LeonCheung I've been working on an NLA based midi-animation system. I'm not too advanced in python, but I was able to make an animusic based animation using it! https://github.com/virtualturtle/midilleman

**Comment by LeonCheung** [comment]
@virtualturtle Cool! I think NLA has to be the solution, since normally you have to blend between actions. Will look into it. Thanks for the info.

**Comment by virtualturtle** [comment]
@LeonCheung https://youtu.be/Dtil3sURVis
