### ISSUE TITLE
BA Thread Quality Posts Collection

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#333]
@JacquesLucke  I hope [this Sheet](https://docs.google.com/spreadsheets/d/1rdgMpl_wRl1eTrY1CmmHAMq429HEKSL5tpqejhADfzk/edit?usp=sharing) can help new guys and old guys to learn AN more quickly than going through nearly 100 pages of 1800 posts (so far). I'll try to keep it up-to-date in future. Maybe we can put it in your initial post? :)

**Comment by JacquesLucke** [comment]
Hey very cool that you took the time to make this table! 

Yes I will insert it in the first post tomorrow.

**Comment by LeonCheung** [comment]
Haha, it did take me almost half day to gather them around. I think somebody gonna do it anway. Just never expect I was the one...

**Comment by kopias** [comment]
Although I though about doing such
a alist, I always new You would do it ;]

**Comment by gabrielmontagne** [comment]
very useful. Thanks so much! I guess effort to collate this and keep it up
to date will only grow with time. Why don't we open up a mailing list? Or
insist on posting to something like stackoverflow instead? Some threaded,
automatically indexed and searchable space for all these conversations? And
point away from then BA thread I guess the sonner the better, as this
project gets more and more popular.

**Comment by JacquesLucke** [comment]
I just inserted a list a link to this spreadsheet in the first post on BA.

Yes I know, BA is not the best place to discuss different questions. That's why I sometimes say people they should ask their questions here on github. Maybe BA will become a better place when cgcookie finally switches from the old forum software to discourse.
Nevertheless I agree that a thread is never really useful to answer many questions.

Personally I don't like mailing lists.. but I do like stackexchange.
Maybe we can somehow create a new tag on http://blender.stackexchange.com/ named "Animation Nodes".
People who are interested in helping can just subscribe to this tag then so that they get an email whenever a new question about animation nodes is asked.

**Comment by YorsLosilla** [comment]
That's exactly what I was thinking about. Maybe #AnNodes  or #AN would be suitable tags. I'll post a question later on

-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎22/‎11/‎2015 12:15
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: Re: [animation_nodes] BA Thread Quality Posts Collection (#333)

I just inserted a list a link to this spreadsheet in the first post on BA.
Yes I know, BA is not the best place to discuss different questions. That's why I sometimes say people they should ask their questions here on github. Maybe BA will become a better place when cgcookie finally switches from the old forum software to discourse.
Nevertheless I agree that a thread is never really useful to answer many questions.
Personally I don't like mailing lists.. but I do like stackexchange.
Maybe we can somehow create a new tag on http://blender.stackexchange.com/ named "Animation Nodes".
People who are interested in helping can just subscribe to this tag then so that they get an email whenever a new question about animation nodes is asked.

**Comment by JacquesLucke** [comment]
Leon Cheung already created the tag on stackexchange :) 
http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2971093&viewfull=1#post2971093
http://blender.stackexchange.com/questions/41928/what-is-animation-nodes-addon-used-for/41931#41931
