### ISSUE TITLE
Failed to remove shape key data

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#355]
When toggling Deep Copy on Instancer node, it will successfully duplicate shape key data, which is expected. However, when toggling it off, those data are still there and cannot be removed.

**Comment by og76** [comment]
but [deep copy] / [no deep copy] it just means it uses the same mesh (obj.data) in all instances or makes copy of mesh (data) for each.

The mesh data (original) contains the shapekeys. So why would it delete it?
If I understand it right ...

**Comment by LeonCheung** [comment]
This is what I'm talking about:

![shapekey](https://cloud.githubusercontent.com/assets/494788/12133612/ce49b972-b461-11e5-93ca-48e1c2b7ad17.gif)

**Comment by og76** [comment]
yes, but I guess that is the blender way. (user, fake user, orphaned data)

*I tried manually (shiftD) copy the object, then del the copy, then copy again ...
I see the same behavior. So __it's not specific to AN or instancer__ .*





ps:
if save /reopen it will be all gone
(after del the objects, the shapekey user still references that mesh name (see user))
I guess the shapekeys are also referenced separately (and may have other users ?) cause they have a dedicated dope sheet part, so maybe if they are referenced there... whatever.

**Comment by LeonCheung** [comment]
But why AN can completely remove instanced mesh data?

**Comment by og76** [comment]
seams so, 
(not the case in manual copy)

**Comment by JacquesLucke** [comment]
It removes mesh data because I told the node to do so :D

![remove mesh data](https://cloud.githubusercontent.com/assets/5881326/12278731/f03c311a-b982-11e5-980f-c521bef8a42a.PNG)

I don't know yet how to remove shape key data..
https://www.blender.org/api/blender_python_api_2_76_2/bpy.types.BlendData.html#bpy.types.BlendData.shape_keys
it is just a bpy_prop_collection... the other data lists in bpy.data have remove functions (like bpy.data.objects.remove) but not for shape keys..

**Comment by LeonCheung** [comment]
Hmm, my coder friend also failed to remove this data. I think nothing we can do for now. Thanks.

**Comment by LeonCheung** [comment]
Hmm, my coder friend also failed to remove this data. I think nothing we can do for now. Thanks.
