### ISSUE TITLE
Suggestion: Poly Rotation Node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#357]
Rotating polys inside a mesh is a very common task on motion design. To do this in an accurate way is very important to have the ability to change the pivot point of the poly according to the orientation of the poly.

See this video from second 0:11 https://vimeo.com/44790478

This is possible somehow on AN but require a lot of trickery. Like here: http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2906449&viewfull=1#post2906449

The idea is to have a node able to rotate a poly changing his pivot point. A correct approach would be to have the ability to rotatate it setting its pivot point on an specific vertex or in the middle point between to vertices. 

If you join this to an effective method to compare faces according to its normal, as I asked here on Stack Exchange:  http://blender.stackexchange.com/questions/43985/how-can-i-compare-normals-in-an-with-python. We will have the ability to create some amazing things.

**Comment by og76** [comment]
I agree in a way that is a bit tedious, but I suspect is the matrix operations that are rather confusing here. 

However, so far the transform polygon has the use center feature already (in comparison to the older post where I was demonstrating that). So the rotation is mostly the one left to deal with. For that is the dir to rotation node, that has quite an operation as you know...

I'll look into it, but I don't see an immediate solution now. you still have to
- * inverted matrices, 
- do your stuff,
- * matrices

and that *with trans and rot in a certain order* ...
so even having a "polygon matrix" or "polygon rotation" is not gonna help much. would mostly replace the dir to rot node with a similar poly one.

-

ps: I will also answer the stack question later, as that is a tricky thing and needs a well composed answer. And I think there is more than one answer. One could be tempted to go for angle, dot or rotational difference, but matrices as in the dir to rot are the key. Well, not as far as dir to rot...

**Comment by LeonCheung** [comment]
Inspired by o.g.'s BA solution, I tried to control the order by per-face weights. If this is acceptable.

![ttt](https://cloud.githubusercontent.com/assets/494788/12134623/0ebcb3f6-b46c-11e5-9d60-8bbe5efe33eb.gif)

**Comment by og76** [comment]
Essentially you need a poly matrix, loc and rot combined. 
(not just the rotation, as the use center works for certain cases, but can complicate things further)
And your job happens:
- matrix invert (move+rot at world origin with zx as the world)
- do stuff
- matrix (move+rot back in place)


The basic poly matrix goes like this with today's tools:
![polygon matrix](https://cloud.githubusercontent.com/assets/11709974/12135103/7c0383e0-b43f-11e5-8385-efb8803b43f6.PNG)

- where normal is Z and verts 01 show X 
(but then, you could choose other edges than v01)

 - note that I do not use here poly center from the transform poly node
 - I use one of the v0, v1 as the center for rotation and v1-v0 as the direction (X)
 - using use world object in mesh will give expected results

of course, you may use other points, or an edge from another poly etc
or various sorting like @LeonCheung keeps providing for months in BA and here

**Comment by og76** [comment]
Also, if you'd like to ask this question also in the stack, maybe the answers will have more visibility there. (the comparison one does not really cover this.)

However,still thinkin if there is a simple and efficient way to do this in a node.

**Comment by LeonCheung** [comment]
[This addon](http://blenderartists.org/forum/showthread.php?307784-unfold-transition) aims to do this, the final result is pretty nice, and it uses bones as controller. fyi

**Comment by YorsLosilla** [comment]
Thanks to all for your answers. It seems to me that the latest method provided by o.g. it´s easier than the previous one. 

I also know that addon but I think it´s better to do it with AN due to the control that you can have on the animation.

However I still think that some type of premade solution will be very handy

**Comment by JacquesLucke** [comment]
Yeah, I agree that more options for the Transform polygon node would be useful!
It's also related to this one: #336 
In fact it should be too difficult. what makes these mesh manipulations so difficult is to give you a lot of control and providing a relatively good performance at the same time.

Other problems are that the transform polygon node only changes the vertex locations in the polygon but does not update the area and all the other properties..

**Comment by og76** [comment]
The problem here is ux / method
For example, in the above I suddenly do not use poly center option because
- it interferes with the setup in an unwanted order
- it only provides matrix * vector (and I need here also the inverted first)

Now, for this parenting / changing pivot to make some sense to the user, the complete set of matrix ops should be either *completely visible* (in other nodes, as above) or *completely hidden*.
But hidden will limit the use cases. Like the center poly does now.

-

*How I see it so far:*
I'm thinking of having 
- a [polygon matrix] node that reads the matrix like the above frame 
- a general [change pivot] or [transform with pivot] that does the matrix combine part (inverted,stuff, not inverted)

Poly is easy to implement, without the complete dir to rot algorithm and the more general pivot will work for other cases than poly.

*But even here, the order of some inverted/not inverted matters, or being able to ignore loc, rot or scale*

-
ps.
I've started writing some "guide" like stuff for these vector matrix, rotation and respective interactions especially to explain such. In a way, could be more helpful than easy, but limited, feature.

And I think is a big gain for the user to get how these work a bit while a hidden operation can be more confusing when you try to add another matrix or so.

**Comment by LeonCheung** [comment]
A very cool [C4D addon](http://code.vonc.fr/?a=59) to create unfolding fx, a bit off-topic, but really worth to have a look. :)

**Comment by JacquesLucke** [comment]
Look here: #336
