### ISSUE TITLE
List Mask node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#369]
This is a bit like the image mask concept:

Here are two normal ways I can think of:
![masks](https://cloud.githubusercontent.com/assets/494788/12449556/21964138-bfb9-11e5-9743-dfb0ab51e5d3.jpg)

Further thought:

For number/color lists, I'm not sure if it would be extented to kind of "List Mix", which means to allow values other than 0 and 1.

Anyway, just leave it here. That's one of the things I mentioned on BA. :)

**Comment by og76** [comment]
Ah, ok, I see

I was exploring this and yes can do. (useful in another part too)
but, I was thinking of a more generic compress list (or filter list?) One list and one 01 mask 

![compress1](https://cloud.githubusercontent.com/assets/11709974/12454918/2b838118-bfa2-11e5-988b-3f7ed9046922.PNG)

But your idea keeps the index intact and maybe the list len

-

How should it behave if lists are uneven? 
- zip is cutting to the shortest, is that the way?
- here I would use zip_longest to preserve the longer one, with an (extra fallback), like images do if a smaller one is on top of a bigger pic, is that the way?
- Or should it be clear what list is canvas and brush, so we preserve the canvas length?

About the float/color or any other mixable item, you mean
 mix a, b in zip(A, B, mask) is like   a mix b factor m?
Hm, doable in loops with any mix node or animate I guess ..

-

On the other hand I wonder about the use of it
U can use loop to filter for many conditions instead of the mask 01 list. 
Creating a 01 mask list is probably gonna be exactly that loop ( as you show there)

**Comment by LeonCheung** [comment]
I didn't expect it to use the longer one, because I don't know how :relaxed:  ... But yes, both are needed among cases, right?

And sure, value mix can be done by loops. I think I mean if we can modularize it into one node for convenient. (Again, AN tree can become complex very easily. The less node we use, the beautiful tree it is.)

Yes, the mask list is better to be a condition list.

**Comment by JacquesLucke** [comment]
When you said "List Mask" I also thought more about the thing o.g. showed in the image. (maybe it should be an Boolean List as mask instead of a integer list?)

**Comment by LeonCheung** [comment]
Totally agree.

**Comment by JacquesLucke** [comment]
Maybe it would help (for your first idea) to extend the switch node, so that it can have an integer input to select between more inputs. This would be like a combination of the "Create List" and "Get List Element" nodes.

**Comment by og76** [comment]
+1 for 01 input for boolean switch 
or a convert integer to bool (<=0 is 0, >= 1 is 1), blender supports that normally in props etc

the trick that Leon is doing is
1. preserving the list length/indices, while with compress, I "slice" in an arbitrary way
2. replacing some elements with the el from the other list
3. that reminds me that is more like a set list element that is workin for a list or a map?
4. could be that you provide listA, listB(3-4 values), index list hthat shows where the 3-4 values should be set in the list A. I'm goin too far here..


boolean list and integers should be an option

**Comment by JacquesLucke** [comment]
There is a Mask List node now.
