### ISSUE TITLE
Suggestion: Add a between option in the compare node 

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#377]
The idea is to evaluate if a certain value is contained between two values. It would be also cool for vectors. For example to know if a rect could be traced from point a to point b, which passes trhough point C.

**Comment by og76** [comment]
It's **doable** using 2 [compare], < and > and one [logic - and] like this:

![compare logic between](https://cloud.githubusercontent.com/assets/11709974/12820568/52c97b8e-cb68-11e5-8316-0de0f297a101.PNG)

and with many more options, like the opposite etc

I'm not sure if we should make a specific node for this...
You can always make a group of it.

ps: and I should answer such on stack exchange ;) 

----

**for vectors specifically**, there **will be** a node that allows such comparison, indirectly 
(when I will correct some issues I have in those geometry nodes I have to propose ...)

mostly giving *a factor* like the reverse logic of mix node ( lerp factor ) and a distance so that we know the point is on the line or not.
*If factor in between 0-1 and distance to line is 0 (or < 0.0001) then you are in on the segment.*

![vector on segment](https://cloud.githubusercontent.com/assets/11709974/12821347/af08ac3c-cb6b-11e5-805d-948e0bed5d01.PNG)
