### ISSUE TITLE
Update Rotation socket in Particle info node

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#378]

**Comment by og76** [comment]
also 
previous rot 
angular veloc
prev angular veloc

**Comment by og76** [comment]
should we do this for **master too**?
I still don't think that many people used such besides my extreme experiment, although on some issues here particles are a subject #372 

I know it breaks the very principle I supported, but **it's very tempting** (so that I can further make more examples already with the rot included) and also cause **it's kind of a mistake to have that socket and explain** conversions etc

**Comment by JacquesLucke** [comment]
Yes ok. Can you make another patch for that?

**Comment by og76** [comment]
I guess it's exactly the same. 
How about conflict when merge into 1.5? considering is the same.

**Comment by JacquesLucke** [comment]
I think when you make the same path for the master branch we won't get any merging conflicts...

**Comment by og76** [comment]
Same path as euler proposal? there is also the older hair commit. Should I try to propose both same as they were for in 1.5?

sorry, git still holds  a lot of mistery to me :blush:

**Comment by JacquesLucke** [comment]
Just do what  you want :p (as long as it makes sense ^^)
Merge conflicts aren't nice but if they occure I will just solve them.
