### ISSUE TITLE
How to batch remove custom props?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#386]
Just wonder if there is any way to remove custom props. Once they are defined for a large number of objects, removing them by hand can be a huge work.

**Comment by JacquesLucke** [comment]
I have a small present for you :D
Just quickly wrote a small addon just for removing custom properties:
https://github.com/JacquesLucke/custom_props_edit

I hope this does what you want. Otherwise you can create an issue in the other repository :)

![custom props editor](https://cloud.githubusercontent.com/assets/5881326/13179281/78c80244-d723-11e5-9064-d5f91c7e37f9.PNG)

**Comment by LeonCheung** [comment]
Sweet addon! Exactly what I want. Tiny yet useful! Thank you so much!
