### ISSUE TITLE
Node Control?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#389]
Documentation needed! :scream: 
![node_ctrl](https://cloud.githubusercontent.com/assets/494788/13194557/b0183acc-d7d0-11e5-9268-739f1d568331.png)

**Comment by JacquesLucke** [comment]
haha, well this is a special socket type that doesn't carry any data. Normally a socket draws itself in a draw function and this is independent of the node that has the socket. The Node Control socket doesn't draw itself instead it calls the node for drawing.

This socket type is used everywhere were I needed sockets that are specialised for specific nodes. eg the "New Parameter" socket that also has the plus button.
Maybe I should filter the socket type list so that it isn't shown there.
