### ISSUE TITLE
Once Per Frame cache fails

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#396]
Result looks the same as One Time type.

[example file](http://www.pasteall.org/blend/40782)

**Comment by LeonCheung** [comment]
And Once Per Input too... or I didn't get it well?

**Comment by JacquesLucke** [comment]
Maybe you understood it wrong.
Caching doesn't help in this example file.

If you enable caching in the invoke subprogram node it stores the output of the subprogram and uses it when a certain condition is met. This way the node doesn't have to execute the subprogram which results in a speedup.

So chaching is only useful when your subprogram outputs data that took a long time to compute.

**Comment by LeonCheung** [comment]
Yes this is a very simple setup. However I tried with some very complex loops anyway, it seems the output value is all the same while frame changing. Or can you provide an convincable example?

**Comment by JacquesLucke** [comment]
Does this work for you:
http://www.pasteall.org/blend/40788

**Comment by LeonCheung** [comment]
Yes. I can see that it can be very useful in such case. I also want to improve cases like the Archimator. But now I feel that I can hardly understand why sometimes I was not allowed to use it by first understanding what "hashable" and "storable" mean.

**Comment by JacquesLucke** [comment]
hashable means that I can call the Python hash function on the data:https://docs.python.org/3/library/functions.html#hash

This is needed so that I can compare the old input data with the new inputs.
Some socket types support this and others don't, mostly lists don't support the hash function.

storable instead is a property determined by Blender. eg I cannot (or shouldn't) store references to objects over a longer period of time because it can cause crashes when you try to access the object, although the user deleted it already.

The hashable property is important for the input values and the storable property for the outputs.
Also the inputs only need to be hashable if you chose "Once Per Input" as cache type.

You can see the storable and hashable property for each socket type in their files like here:
https://github.com/JacquesLucke/animation_nodes/blob/master/sockets/object.py#L13-L14

**Comment by LeonCheung** [comment]
Ah much better :D thanks a lot for the answer! I need to experience more on this feature....
