### ISSUE TITLE
rendering animation needs nodetree 'always' auto execution

### ISSUE THREAD

**Issue by kopias** [JacquesLucke/animation_nodes#398]
Win7x64 blender 2.76  animation nodes 1.5 branch

I setup my nodetrees mainly on frame change auto execution but this have issue of not rendering (only opengl still frame works). Having 2-3 nodetrees to change to 'always' auto execution is not a huge work before rendering (and change back afterwards) but one can imagine what this could mean for larger scenes. 

Any ideas/tips?

Mine is to have option/checkbox that will temporary set all nodetrees to always auto execute before running animation rendering (including opengl animation) or maybe do this always.

Some simple examle scene meant to render with opengl animation (than scaled down becouse there is no aa when vieport ao is enabled, but this is not important).
[an trail1.zip](https://github.com/JacquesLucke/animation_nodes/files/147894/an.trail1.zip)

**Comment by JacquesLucke** [comment]
Ok I found the problems in your file. I've to admit, it was a bit tricky.

1. A small cleanup thing. You had two node trees and both of them contained the same loop. It is better to have the loop only once (maybe in a separate tree) and then call it using two Invoke Subprogram nodes. In fact one loop in your file wasn't used at all. Both invoke subprogram nodes called the same subprogram.

2. You enabled "Copy Full Object" in the instancer node, which is fine, but you forgot that this also copies the animation data. Most of the time you don't want this. The Instancer node has a "Remove Animation Data" checkbox in the advanced settings to remove the fcurves. (I'm thinking about turning this on by default now, what do you think?) This is also the reason you only see one object in the render, when "Always" is disabled. Blender evaluates the fcurves before rendering and sets all instances at the same location. If "Always" is turned on this location is overwritten by AN afterwards.

3. I think you accidently connected wrong sockets in the loop. In your file you are reading the location of the instance and not of the controler object. That seemed to work because the instances had the same animation. But not anymore. Instead you have to read the location of the controler object (you already had the parameter input set up for that).

So in the end it looks like so:

![correct animation](https://cloud.githubusercontent.com/assets/5881326/13350038/e7a5e640-dc7d-11e5-9ed8-de1bb21f9ba5.PNG)

**Comment by kopias** [comment]
totally right
this makes perfect sense now i admit that i had too little sleep for a couple of days (promise to not do that again)

thx for investigating - best support ever

the reason why i mostly use separate node trees is because of easy way of turning on/off things via overview panel
