### ISSUE TITLE
Create Object Node Reports Error

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#410]
Located at Object > Utils

PS: Not just this one. Basically for all "xxx by Name" nodes.

**Comment by JacquesLucke** [comment]
Well the Create Object node was more or less a test case for nodes that should not be used with auto execution (because you can very easily destroy your scene with it)
I think I can improve this but it doesn't have high priority for me... It's not an important node atm.

I wonder why you say that these "... by name" nodes don't work. I don't have a problem with them, can you make a screenshot?

**Comment by LeonCheung** [comment]
there are several similsr nodes like that, just search keywords “by name” in Ctrl A list.

**Comment by JacquesLucke** [comment]
Here, I inserted the node, but I don't get an error. Not sure if we are talking about the same thing
![by name - no problem](https://cloud.githubusercontent.com/assets/5881326/13548333/3f8c7af6-e2ee-11e5-9fb3-777b65d967cb.PNG)

**Comment by LeonCheung** [comment]
Yes. But very strange that you did't get error, which I met for quite long time... Currently I cannot get my PC running. Will check more tomorrow.

**Comment by LeonCheung** [comment]
Ahh maybe my bad, the By Name nodes is not reporting error indeed... sorry for that misreport. Just that single node...

**Comment by JacquesLucke** [comment]
Oh ok. np

I'm thinking about removing the Create Object node until we have a better idea how it can be used. What do you think?

**Comment by LeonCheung** [comment]
Agree.
