### ISSUE TITLE
Invoke Function?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#418]
When clicking the X icon on every List nodes to remove all inputs, I got a "Invoke Function" pop-up. What's that mean?

**Comment by JacquesLucke** [comment]
this is just a confirmation popup, you get this in some other places too where you have buttons on sockets or nodes. (most of them are rarely used)
they all show the same text in the confirmation popup because in the backend they use the same operator.
I might change this text later today to make it more clear
