### ISSUE TITLE
Interpolation in Map Range node?

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#422]
I know, some time ago my decision was not to use an interpolation socket in that node because that would make it too similiar to the Animate Float node.
But maybe I'll have to change my mind, because it can be quite useful a some cases.
Maybe make it optional? Or or hide it by default? Or leave it out?

What do you think?

**Comment by YorsLosilla** [comment]
It will be ultracool!!!

-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎11/‎03/‎2016 14:26
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: [animation_nodes] Interpolation in Map Range node? (#422)

I know, some time ago my decision was not to use an interpolation socket in that node because that would make it too similiar to the Animate Float node.
But maybe I'll have to change my mind, because it can be quite useful a some cases.
Maybe make it optional? Or or hide it by default? Or leave it out?
What do you think?

**Comment by og76** [comment]
cool to have. 
the animate is always limited/clamped to 0-duration

if optional can bring some speed (to linear) by not performing the interpolation math, then option it is
just the socket is not enough..

**Comment by JacquesLucke** [comment]
Yes, not using the interpolation can be faster indeed, but I'm not sure if it will be noticable. I have to test that. Another thing is that it only works when the clamp option is turned on.

**Comment by og76** [comment]
about speed, if it's in a loop with 1000 it might matter ..
about clamp, seams logical, it will work between min/max

**Comment by JacquesLucke** [comment]
yes, but 1000 iterations aren't uncommon if you do mesh generation or something similiar.

**Comment by og76** [comment]
exactly, that is why I brought up performace

**Comment by JacquesLucke** [comment]
ok, I think I will just make another checkbox to turn Interpolation on and off when clamp is turned on.
