### ISSUE TITLE
Distance node improvement / Distance Effector

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#424]
Hi,

It would be really useful to get not only radial distance from one vector to another, but also distance from one object/group/list to another object based on it's local axis or even mesh normal. 
Also, mapping output value with a curve all in one node would be cool.
I know this can be done with a script, but an artist friendly node would be priceless timesaver for many.

Here is a mockup for this node and an example situation
(not completely accurate, but I hope you will understand the concept):

![an_distance_effector_proposal](https://cloud.githubusercontent.com/assets/17803543/13726177/e9b1acc8-e8c4-11e5-834c-3ff768a08628.jpg)

Karlis Stigis
-------------------
www.hypnosis.lv
https://www.facebook.com/hypnosisgroup

**Comment by YorsLosilla** [comment]
Very cool idea.


-----Mensaje original-----
De: "karlisstigis" <notifications@github.com>
Enviado: ‎13/‎03/‎2016 1:43
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: [animation_nodes] Distance node improvement / Distance Effector(#424)

Hi,
It would be really useful to get not only radial distance from one vector to another, but also distance from one object/group/list to another object based on it's local axis or even mesh normal. 
Also, mapping output value with a curve all in one node would be cool.
I know this can be done with a script, but an artist friendly node would be priceless timesaver for many.
Here is a mockup for this node and an example situation
(not completely accurate, but I hope you will understand the concept):

Karlis Stigis
www.hypnosis.lv
https://www.facebook.com/hypnosisgroup

**Comment by og76** [comment]
makes sense, though I doubt it will go like this, on the objects.
( I would have 2 rows with +x+y+z and -x-y-z so you can check +y and/or -y ..)

as a single node like this, we'll have to think of a way that does not limit to just that. or maybe more than 1 node.

The problem here is that you are actually dealing with object location, vectors (a grid) and not the objects/instances as a list. You have to have the original positions / fixed positions of objects or to store them as ID key or keyframe or so in order to have the object list workable. 

Point is, once I move an object, relation to the empty changes. So the relation has to be to a fixed / original location of the cubes.. 
So the above would be dealing with a list of Vectors not original objects. 

-

however, at this point, for soon to be v1.5, we are gonna have a sort list thing that should take care of most of the problem here. (distance to / direction etc) Making such way easier.

also a node related to distance to object/surface and inside/outside volume is almost there (for more free form than above..)

we'll see how that goes in relation to the above

-

ps: is doable without scripting at this point, just maybe too big of a noodle soup
but yes, this is one of the preferred features so it should go for a simpler/friendlier way

**Comment by karlisstigis** [comment]
Yes, you pinpointed the problems in there very precisely.
It's good to hear that you know how to solve it and that it's already planned! 
I can't wait to get my hands on it!

**Comment by JacquesLucke** [comment]
Maybe this can work too?
![vector plane distance](https://cloud.githubusercontent.com/assets/5881326/13729300/dfd1335a-e931-11e5-8961-2e51a1739d1a.PNG)

For radial effects we can also implement a "Distance Vector to Line" node.

Note: I made the "Distance Vector to Plane" node just now, so you'll have to update your version.

Does someone have a better name for these new nodes? "Distance Between Vector and Plane" is too long.
I took the current name from here: https://www.blender.org/api/blender_python_api_2_77_0/mathutils.geometry.html#mathutils.geometry.distance_point_to_plane

**Comment by karlisstigis** [comment]
Will try!

**Comment by karlisstigis** [comment]
I am trying and something is happening, but I don't exactly understand how you got vectors from object group or list there..? Is there a node to automatically get all vectors from grouped objects? Because when I try, AN is making a "Get List Element" node..

**Comment by YorsLosilla** [comment]
You need to create a loop with those objects. An perform the calculations inside the loop.


-----Mensaje original-----
De: "karlisstigis" <notifications@github.com>
Enviado: ‎13/‎03/‎2016 22:17
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Distance node improvement / Distance Effector(#424)

I am trying and something is happening, but I don't exactly understand how you got vectors from object group or list there..? Is there a node to automatically get all vectors from grouped objects? Because when I try, AN is making a "Get List Element" node..

**Comment by karlisstigis** [comment]
Well, yes, but how to feed vectors from many objects in loop?
My setup:

![screen shot 2016-03-13 at 23 34 16](https://cloud.githubusercontent.com/assets/17803543/13731534/3787e03e-e974-11e5-80a0-774dfa347131.png)

**Comment by JacquesLucke** [comment]
I used the "Grid Arrange Objects" template as basis in the above node setup

**Comment by JacquesLucke** [comment]
In your example it would be better to just use the Object as iterator in the loop. And then use the Object Transforms Input node to get the location of the individual objects

**Comment by YorsLosilla** [comment]
Yeah. That's was mi idea. Sorry for not being specific.


-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎13/‎03/‎2016 22:41
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Distance node improvement / Distance Effector(#424)

In your example it would be better to just use the Object as iterator in the loop. And then use the Object Transforms Input node to get the location of the individual objects

**Comment by karlisstigis** [comment]
Guys, I love you!

![screen shot 2016-03-14 at 00 33 27](https://cloud.githubusercontent.com/assets/17803543/13731851/726c0e70-e97c-11e5-8716-2791d0e2f193.png)

**Comment by YorsLosilla** [comment]
It will be nice to have 3d grids options on the grid node. But that's maybe another issue.


-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎13/‎03/‎2016 22:39
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Distance node improvement / Distance Effector(#424)

I used the "Grid Arrange Objects" template as basis in the above node setup

**Comment by YorsLosilla** [comment]
You are there!! When you understand the power of loops anything can be possible.


-----Mensaje original-----
De: "karlisstigis" <notifications@github.com>
Enviado: ‎13/‎03/‎2016 23:34
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Distance node improvement / Distance Effector(#424)

Guys, I love you!

**Comment by JacquesLucke** [comment]
We have a template for 3d grids,
the main problem is that you get a lot of objects very quickly which slows down your scene.
