### ISSUE TITLE
Concurrency Sorting

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#448]
As discussed in #149, "Multiple items share a single ID" can be somtimes wanted. To be hornest I don't know how to describe or name it better... But please check my last post there to get better point.  Thanks!

**Comment by og76** [comment]
Let me see if I get it right now:

I've looked into [New Order](https://drive.google.com/file/d/0B1ojv5B6Lb-3ek1KQ2VDR0FTNEE/view) 
there are 2 operations here:

1. **List of locations** y, sorting the locations by Direction y, some keys are same 
 this is not the deal here.. The sorting happens by set() really. So yes, it is sorted.
 ( that is achievable with Direction Sorting, today, as sorting. 
 the objects where key (in pair) has same value will retain the previous sort (stable sorting)
 Like if u sort (a,b,c,d,e) with keys (3, 0, 0, 8.2, 1.5) => (b,c,e,a,d) , so b,c retain prev order )

2.  **New order** are the **index of List of locations as set()**, or otherwise same sorted value for same key
 so that u use the New order for the scale value

If It's like above, then 
 - New Order is actually a set of values, that if plugged into the sort by custom key list, will give you correct sorting. Not the deal here. But some values are same
 - _**what you are looking for is creating that list, with same values for same key**_

I understand this as a **Sort by Keys and Group by Same Key** feature. 
So what is missing here is **Group by Keys** or **Group List by Values**

Just as a note, there is a big** precision/float error issue here** when comparing the value, lookin for that element in a set. So some elements may not be grouped cause they are actually 0.99999xxx instead of 1.0. This means the values (if floats) should be `round(value, 4)` before goin into the set, preferably right when created `[ round(i.location[1], 4) for i in x]`

that would be like 

-

The way you use it further is the same as I would use the Sorted Index output that I have in my var of sort node. That is the main purpose, in a way, not to sort the obj, but to use a virtual sorted list of it

Only that these are not Sorted index, but **Grouped by values Index** or **Index of Groups in Grouped by values** .... doh. ok, call it Concurrency :)

-

conclusion:
_I think it is a way of sorting, and a very necessary one. And a smart one, ok. That is why I asked your give on sort node :)
You normally don't need sorting for this case of scale by distance as you can use the x value and map range etc.
The smart part is that you don't use the distance but the order of things_

I don't know if it should be a separate node, or depend on a separate one. I don't think so. 
i'll think of it more as how it could go into sort.

The only similar trick I was thinking, was of having a **Direction + zig-zag** variant of sorting, that would group objects in groups of say 0.5 on y and then sort those groups. Like having a very loose precision, of 0.5 here.
That would add sorting like a grid, objects that are almost like a grid.
You can do today by using the snap Vector math on the location values and then sort ... but the zig zag kinda implies sorting 2 times, one on X, with snap, then on y with snap.


I was thinking about grouping parts like sublists, as you would go from a flat list to a polygon indices one, but that may complicate things and should be left for mesh area. 

-

as a side note, I would not index(element) as it gives error if not finding it (see precision issue also)

**Comment by og76** [comment]
ah, the name? Group by Same Sorted Value or so ..

**Comment by og76** [comment]
![sort concurrency](https://cloud.githubusercontent.com/assets/11709974/14070217/71929754-f4ac-11e5-9fb1-c95c5235c7af.PNG)

**Comment by LeonCheung** [comment]
haha maybe name like that, quite a long one  though. :D   And true about the precision issue, that's why I suggest a threshold option for that, working like snap or round. (it would be ok for string/name sorting though). The MotionTool way is by kinda pre-assignment, something like defining as custom IDs. Whatever, this is really useful feature, which should be well investigated. IMHO. (Grrr... I hate typing on a 5' screen!!...@#$&)

**Comment by LeonCheung** [comment]
Finally got my PC back in hand (sounds wierd...)
@og76 Yes, Using script can be much cleaner like that. Btw, I prefer snapping since it allows more flexiable tweaking.

![grouped](https://cloud.githubusercontent.com/assets/494788/14163338/e86a6e52-f726-11e5-9cea-15daeaef5198.png)

And this is just for numbers, what about strings?

About the name, some candidates:

- **Group by Values** (I just feel that the word "Group" may cause confusion with the object grouping feaure.)
- **Identify by Values**
- **Level by Values**
- **Get Concurrency Order**
- **Get Grouped Order**
- **Get Identified Order**
- **Identify**

**Comment by LeonCheung** [comment]
Things here can be generally solved by the new ID Key sorting feature implemented to the current Cython branch, I think this issue can be closed for now. However, for things like Element Sorting (instead of Object Sorting), either there should be a ready-to-use node for that, or there could be exist as a template setup.
