### ISSUE TITLE
[Suggestion] Implement regex for Replace Text Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#462]
How cool will that be?  :)  A ready-to-use feature like this might be not bad.

**Comment by clankill3r** [comment]
@JacquesLucke I could look into it. Seems easy and a nice way to get some practise. And I do agree this could be usefull.

**Comment by JacquesLucke** [comment]
yes you can try it and make a pull request then. I'll comment on your code there. thx

**Comment by clankill3r** [comment]
@LeonCheung 

I made a really simple one for a start:

![regex](https://cloud.githubusercontent.com/assets/738650/14299531/47129106-fb8b-11e5-96c9-7514f12d79f6.PNG)

It's only a long time ago I have used regex so i'm rusty as...

I want to make a enum list with operartions so it can be used for more then a replace.
There are also operations like match, fullmatch, search, split, findall etc.

Some could return a list of strings (if possible), or a boolean, the number of matches etc.

Anyway, (still @LeonCheung) could you provide some user case examples? That would really help me with testing.

(Also I want to make a node to read data from a text file (different then [text block reader]))

**Comment by LeonCheung** [comment]
Hi @clankill3r , really appreciated for your effort. It looks cool! About the enum list idea, do you mean kind of below?

![protot](https://cloud.githubusercontent.com/assets/494788/14302955/d633251a-fbd8-11e5-9d04-980cca416686.png)

I have to say that there can be too many cases!!! Generally it can be commonly used for text processing, or replace data path related strings, or simply replace a matched parts within one or more texts, so that we don't have to use combine string list or expression like "str + str + str" to do that.

For testing, try [this](http://pasteall.org/blend/41331), or [this](http://www.pasteall.org/blend/41333). Focus on those yellow nodes in both file.

**Comment by clankill3r** [comment]
I meant like this:
![enum](https://cloud.githubusercontent.com/assets/738650/14307687/43717c1a-fbd1-11e5-8d48-9c2ec1c9998e.png)

But I like your idea as well (it only won't be 2 columns cause that is not possible as far as I know)

**Comment by LeonCheung** [comment]
Interesting.  :)

**Comment by JacquesLucke** [comment]
Leons node should be possible but I prefer the way clankill3r did it, because it is closer to the python function.
Also I'm not sure if it is good to have a node for regular expressions. Maybe it'd be better to have regex as option in the other text nodes like in the Split Text node.

In this example we could have an checkbox in the Replace Text node to enabled Regex.
If regex is enabled we should have the sockets: Text, Pattern, Replacement (maybe we can find a shorter term for this?), Count (this one can be hidden by default); in that order.
The output is the new text and the amount of replacements.

https://docs.python.org/3/library/re.html#re.subn

What do you think?

**Comment by clankill3r** [comment]
(I'm tired!)
Well, I have to spend more time to make a good decision about that. What I prefer about your way is that the workflow sounds quicker. Instead of adding a regex node and change the operation to slit you can just add the split node directly. It also saves a lot of time swapping nodes in and out when changing from regex to non regex or the other way around.

So yeah, I look into that. Also, i'm really touching the waters at the moment. I haven't really programmed with nodes in a few years. And AN is different in quite some ways compared to ICE which also something I have to get used to.

**Comment by JacquesLucke** [comment]
Yeah sure, no problem, take all the time you need!! No hurry :)

And I'm tired too haha; I just came back home after two days ^^
