### ISSUE TITLE
Input and Output names really confusing with AN

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#469]
This is not nitpicking. I think the names Input and Output are really confusing with AN.
And after 2 months or so, I still can't get used to it. It's like convincing myself left is right and right is left.

Lets say I have an object and I would like to know it's rotation. Logically I would assume I want the output, so [Object Transforms Output]. But no, I need  [Object Transforms Input].

I think it would be much more clear if things where named like:
 [Set Object Transforms]
 [Get Object Transforms]

(and the like)

**Comment by JacquesLucke** [comment]
I understand the problem but I think we won't change this anymore because:
1. It would break pretty much every file that exists so far
2. Everyone has to relearn how the nodes are called. (It was already hard enouph to rename individual nodes like the Object Instancer)
3. While Get/Set might be better in some cases, Input/Output are better in others. I will try to stay consistent with how 'Input' and 'Output' is used though 

In general "Input" means that you want to get data into your node tree.

**Comment by clankill3r** [comment]
I think you accidently switched names for [Object Transforms Input] and  [Object Transforms Output] then.
