### ISSUE TITLE
[Suggestion] String Input for Sort Element Key

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#471]
![sort_](https://cloud.githubusercontent.com/assets/494788/14237062/44f6d002-fa51-11e5-95c8-83bf86968fe9.png)
A typical way is something like this, for more flexible control. Also possibly useful for switching sorting rules among multiple custom props. (I know it would be fine to use one or more switches instead, regardless performance)

Of course, an expression-like structure can be ideal imho, just brainstorming.  :)

BTW, If I get it right, shouldn't the "Key List" be called like "Key Mask List" or simply "Mask List" instead for easier understanding?

**Comment by og76** [comment]
the key lists float/int/string are intended for making it very easy and nodal in exactly these cases

so does this cover for it? (whatever the formulas)
![string sort](https://cloud.githubusercontent.com/assets/11709974/14242091/16d97588-fa58-11e5-81f5-d05cd2e92c3e.PNG)


+the key lists are not masking, they are sorting keys

what's wrong with this approach?

**Comment by JacquesLucke** [comment]
o.g. is right "mask list" would be the wrong word here. Do you understand what it does now or should I provide another example.

The expression field is not an input socket intentionally. Mainly for performance reasons. Because the way it is now I can do all syntax checking and compilation on compile time instead of running time. Otherwise it would be very slow. The "Key List" sorting type can do everything you can do with "Custom" but it is even more powerful. We have both because "Custom" is a bit faster and more convenient in simple cases (you don't need to create an extra loop).

**Comment by LeonCheung** [comment]
Got it. Thanks both.
