### ISSUE TITLE
Provide an end node required for exuction node tree

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#481]
This is probably to late down the road but I feel this is really important.
A node that is required for exucution of the code.

Max (from cycling74, not from autodesk) made the same mistake. The side effects this can have can be horrifying. Sometimes you don't want to use certain parts of the node tree anymore. If they still execute they can alter things you don't want without really noticing it. Also they slow down the application.

This is also the reason the node trees for shader, compositing, world and line style require an output node.

The tree executed could be depending on the output that was last selected, just like with the shader for example:

![1](https://cloud.githubusercontent.com/assets/738650/14298078/267a0ae4-fb83-11e5-8331-bfa04ca2eeb8.PNG)

![2](https://cloud.githubusercontent.com/assets/738650/14298080/2ad4d3e4-fb83-11e5-9bb9-edb59e931456.PNG)

Thinking about it, it shouldn't even be that hard to implement (from a programmers perspective, not from a I know the blender API pretty well perspective).

**Comment by JacquesLucke** [comment]
unfortunally this does not work because a node tree in AN doesn't really have an output as a shader or a compositor node setup.

If you don't want that certain nodes are executed you can put them into a separate tree and turn of auto execution, or make them into a group which isn't invoke, or disable all sockets/remove the object input.
