### ISSUE TITLE
Struct Socket

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#514]
**Basic Idea:**
It would be good to have a datatype that can contain multiple other datatypes.

**Advantages:**
- It makes it easier to manage many records. Currently you have to use either many lists or one Generic List, both of which have disadvantages. If you have many lists you need much more links and more sockets... they make the node tree much more chaotic. Using a generic list is also bad because you have to work around the data type system we have in AN. (see here #496)
- A subprogram can have multiple compound sockets as input. Each of them contains the data for a specific subtask of the subprogram. This can work as a way to separate the inputs of subprograms make a 'Divider' socket superfluous. (see here #463)
- Allows us to have a new set of nodes which work with records. E.g. a node that automatically parses an .csv file into a list of compounds.This makes it more straight forward to make data visualizations.

**Implementation Details:**
Two new socket types: ``an_CompoundSocket`` and ``an_CompoundListSocket``.
The data type that is carried through compound sockets is basicly a python dictionary within an instance of a CompoundType class. We don't really need this extra class yet (could just use a normal dict) but I prefer to have it if we want to add more functionality to it later.
The dictionary keys will be tuples containing two strings:

1. Data Type
2. Name

The data type will be one of the existing socket data types we have (like "Vector", "Float List", ... even "Compound" is possible) and the name will be choosen by the user.
There will be two main nodes which deal with compound types (please tell me if you have better names!):

1. Set Compound Elements: 
    - Inputs: Compound Socket and some sockets the user can create (like in the expression node)
    - Outputs: Just the Compound Socket
2. Get Compound Elements:
    - Inputs: Just the Compound Socket
    - Outputs: Custom sockets

Open problem:
How to deal with caching? Should it be allowed for all compound sockets? This can make AN instable when users start storing objects or other blender datatypes in the compounds. On the other hand it would be very useful to cache compound lists for large data sets. 
The best (but also the most complex) way to go is to check the data if it is cacheable during runtime,  but I personally don't like this.
I think it would be best to make the user responsible for using Compound Sockets correctly in this case.

Oh and please tell me if we should name the socket differently, maybe it sounds weird to a native english speaker. Maybe we can replace every 'compound' with 'struct'

**Comment by og76** [comment]
excellent!
Watching the exploration of string (csv) and generic in #496 I was thinking we maybe need a way to allow creation of custom classes or data types (like the polygon that actually carry several types of data). But that goes as far as my literacy goes.
So I guess this is the answer then.

1. bout names?
maybe **Composite** instead of Compound? or MultiSocket? Multi Data .. 
or **Zip** Data (I guess is really that, in a way) cause it also reminds of Zip archive that packs things

 Buss Socket or Subway (and nodes are Stations or Transfer Points :D)  - sometimes weird names are easy to remember
  or Rocket (+ docking station) airplane (+ land / take off)
 Macro, OpticFiber, MegaSocket, SuperSock, SpiderMan 
...ok, I'll stop before referring to nodes as genitals and data as DNA 

2. Would this allow us to have basic Dict? as data/ as sock?
 meaning with a way to call a specific value? not just items
 ```py
 dic = { "mimi" : 25, "gugu" : 32}
 myAge = dic[ "mimi" ] # I wish ...
# or
 dic = { "v1" : [], "v2" : [], "v3" : [], }
 for v in dic.keys:
     if v in interestingVs: dict[v].append(i)
 ```
 today i can use just generic + scripts, but hm. ok ..

3. Will it be able to transfer **parts of composite** data **only if requested**? If at the end is an isLinked?
 that would also go for polygon, vertex, where only certain data is transferred, not all the pack

 I know this is a tough one, considering subprograms especially, but I guess it could unload a lot
 And does not seam impossible with something like the tree info  links info today

4. cache? copy()?
 when I set the data, I use normal sockets/data types, 
 so the "composite" should "take a note" about what kind of data and cache possibility. Or maybe should behave as if there are n data types, treating them like n sockets (with known cache possibilities)

-

actually I was just looking again into the Adaptive with some bmesh in mind, so there we are again
And point 3 becomes really intresting

also was thinkin at a certain point into a way to have "Advanced Normals" in the bvh nearest. like the initial formula I had for is InsideVol. Cause the normals are not usable on some exceptions. And I thought how to get some extra data along with the bvh. but dropped it ..

also had some ideas on baricentric that would allow mesh cage/ lattice like deform etc. again lots of data needed

-

can't wait! :)

**Comment by clankill3r** [comment]
Really great @JacquesLucke !

Personally I don't like the word compound. Cause a group and a loop is also a compound.
I like Multi Data like @og76 mentioned. It could also be Multi Datatype.
Struct is also ok. (struct > compound)

About caching, this is really a must have for me. I often have to work with data files over a gig in size.
One of the reasons I move from processing to blender is cause I got sick of loading the data (since you need to compile after the changes..).

> I think it would be best to make the user responsible for using Compound Sockets correctly in this case.

Amen to that. We can always change it later. And we might have better caching for blender 2.8.
--------------

Thinking about it some more I'm getting doubts about the compounds node.

1. A node tree is like a diagram, using compounds makes it more verbose
2. If people start to make group or node loops that operate on a compound then a system becomes less dynamic and nodes become less usable. To re use a specific compound made you might have to wrap things in a compound now.
It reminds me of using libraries with java, where I have to use 3 different kind of libraries that all use their own type of vector for just storing an x, y and z. I keep converting a stupid xyz vector to another kind.
Or I have to build a wrapper on a wrapper on a wrapper...

Maybe it would be good to just make a mockup that doesn't work but can be connected and constructed like it works. Then we can make some pseudo node tree usages of the compound concept and evaluate the advantages over the disadvantages. This way minimal time is lost.

It's still an interesting concept to explore.

**Comment by JacquesLucke** [comment]
Thanks for the comments. I will go with "Struct" for now.

I work on this in the structs branch.

**Comment by LeonCheung** [comment]
Oh I must have missed something milestone-like... I don't know if the word Meta or Metadata is ok here, considering the usage of this word in Blender (metastrip for example).

**Comment by JacquesLucke** [comment]
The 'structs' branch contains a basic implementation of my concept.
I created the two socket types and the Set/Get Struct Elements nodes.

![structs](https://cloud.githubusercontent.com/assets/5881326/14568165/eb1c2da8-0337-11e6-97c7-b1b5bfa8797e.PNG)

**Comment by clankill3r** [comment]
Great, I wish I had more time this week.

Why does wrong name show a integer socket?
Why does Number not exist in the bottom right? And outputs an array?

**Comment by JacquesLucke** [comment]
The data type of the sockets is specified by the user (there is this little seach popup when you click on the plus icon). The socket types are completely decoupled from the data that is in the Struct.

As I explained above a struct is like a dictionary but it does not only store the name of the property but also the data type (this is one of the main benefits of using structs instead of generic stuff). So the Get Struct Elements node socket might have the same name but the output socket has the wrong type. This is why the *Number* does not exist. Only the key ``("Integer", "Number")`` is in the dict, but not ``("String List", "Number")``.
And when the key is not found the node will output a default value so that the nodes afterwards don't raise errors.

**Comment by LeonCheung** [comment]
Just tested, works really great! Now I'm just hoping that there could be an easier way to accelerate the current workflow. I mean, currently we first create the valid socket, then give it a valid name. How about create output socket(s) by selecting key(s) from a list that was prefetched from the input struct? Sounding like a two-click operation? :)

**Comment by JacquesLucke** [comment]
Not sure if we are talking about the same thing but I thought about a button in the Set Struct Elements node that automatically creates a corresponding Get Struct Elements node (and maybe the other way around too)

**Comment by LeonCheung** [comment]
Exactly the other way around :P That's cool for sure. In that case, one more concern: Does the word "automatically" mean to create ALL keys or specified one(s)?

**Comment by JacquesLucke** [comment]
I think it should create all keys in the new node. You can remove the ones you don't need quite easily.

**Comment by LeonCheung** [comment]
That's exactly the concern: considering removing 8 keys to keep 2 out of 10.

**Comment by JacquesLucke** [comment]
yep... that is how it will be most likely.. I can also make a little popup dialog in which you select which keys you want to have in the other node.

**Comment by clankill3r** [comment]
(I cant get myself to work...)

Concidering the remove problem. The same is for lists sometimes:
Having this terrible example:

<img width="403" alt="screen shot 2016-04-16 at 1 45 20 pm" src="https://cloud.githubusercontent.com/assets/738650/14580783/9475fc66-03d9-11e6-989d-4c063729b8d1.png">

I think it would be nice that the 'remove all inputs' would be first 'remove all unconnected inputs' and when all inputs are connected 'remove all inputs'.
This way one click leads to:

<img width="396" alt="screen shot 2016-04-16 at 1 49 16 pm" src="https://cloud.githubusercontent.com/assets/738650/14580794/0aeea780-03da-11e6-8bf7-5451328412bd.png">

And 2 clicks leads to:

<img width="414" alt="screen shot 2016-04-16 at 1 49 47 pm" src="https://cloud.githubusercontent.com/assets/738650/14580796/1c22540c-03da-11e6-94fc-e955ab8c4128.png">

**Comment by og76** [comment]
maybe there should be an indication that a certain data/ name key is not valid. 

and also a struct items (key[1] in dic.keys ?) would be nice, returning a (str) list of names 
along with a search struct/ get struct element (get value) that would have struct + mane > value
(I guiess that would be the dict like op, just the key is only the name ..)

**Comment by clankill3r** [comment]
I played some around with structs in the Array of Structures format (AOS).
(Instead of Structure of Arrays (which is still better I guess but hard to work with sometimes)).

I find it hard and inefficient to get the min and max x value for example (I know it would be the same problem with generics).
Is there a better way then I have now? I really don't like it constructs a new array. That will be horrible for speed and memory.

 (The solution should not be in the 'Create Structs' loop, cause it should be able to get the min or max from a subset of the structs as well).

<img width="860" alt="screen shot 2016-04-16 at 3 12 27 pm" src="https://cloud.githubusercontent.com/assets/738650/14581190/4e5935ec-03e6-11e6-8707-5384c264b851.png">

Would it be possible to have 'Get Struct **List** Elements'?

[venice_xxx-aos-1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/222195/venice_xxx-aos-1.blend.zip)

**Comment by JacquesLucke** [comment]
Yes I'll try to make a better error message later.

About the Get Struct List Elements node. Yes I think we can have this, not sure how much faster this will be but I can try to find the fastest possible way. I already had fun with finding fast ways yesterday haha:
4361e9bab17b81344591dd428c90ac58452e0405
890ce6cacadf5b56aed7097bdd6ee71e99473c6f

one problem is that this will introduce generic lists again in certain cases. Like when we have a list of integer lists.

**Comment by clankill3r** [comment]
> one problem is that this will introduce generic lists again in certain cases. Like when we have a list of integer lists.

Is there no way around that?

**Comment by JacquesLucke** [comment]
Well we could have more socket types, like lists of lists of lists etc.. but that issue will still occure

**Comment by JacquesLucke** [comment]
![get struct list elements](https://cloud.githubusercontent.com/assets/5881326/14583043/801cc80c-0416-11e6-8a44-639b21eadf6d.PNG)

**Comment by JacquesLucke** [comment]
The struct nodes are in the v1_6 branch now. I think I will continue to work on them but the general design works quite well :)

**Comment by LeonCheung** [comment]
It seems everybody hates generic stuff while I don't. :laughing:
