### ISSUE TITLE
file reader node

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#517]
We have a Text Block Reader, the problem with it is that the file has to be in the Text Editor of blender.
When I added a 140mb text file for example and saved the blender file the blender file got 270mb.
This is a good way to fill your SSD :)

I want to make a text file reader that reads directly from a file. Probably a buffered reader as well so it can deal more efficient with data files over a gig in size.

**Comment by LeonCheung** [comment]
Maybe a little off topic but you can always toggle Compress when saving file to zip it to very small size especially for the case here.

But! if you are talking about giga... good luck then. :pray:

**Comment by JacquesLucke** [comment]
yes we can have a text file reader node, shouldn't be used with auto execution though.
what exactly do you understand under 'buffered reader'?

**Comment by clankill3r** [comment]
A buffered reader reads the file in chunks. This is often needed with big files where simple file reading method fails.

**Comment by JacquesLucke** [comment]
How are these chungs specified? Specific amount of bytes, or aligned to new lines or how would you do it?

**Comment by clankill3r** [comment]
I don't know yet since i'm new to python. Often it is an amount of bytes in combination with a newline character. I think I start with a simple reader anyway that doesn't read it buffered.
Time will tell, i'm still looking around everywhere when it comes to AN to get more insight in AN as a whole.

**Comment by JacquesLucke** [comment]
I just implement a first version of a Text File Reader node.
It takes a path as input and outputs the text. Only text files are supported (this also includes .csv etc)

Internally the node does some caching to avoid reloading the file. It also checks the last modification time of the source file so that it can reload when the file changed.

![text file reader](https://cloud.githubusercontent.com/assets/5881326/14938877/0d73c1c0-0f33-11e6-9922-a702736a145e.PNG)

**Comment by LeonCheung** [comment]
Cool! Will it support reading UTF8?

**Comment by JacquesLucke** [comment]
I have not tested it but I think so. It just returns a normal python string. You can try out yourself :p

**Comment by LeonCheung** [comment]
Actually I tried, and failed it returns "Couldn't read file"...

**Comment by JacquesLucke** [comment]
thx for the feedback. will take a look later today

**Comment by JacquesLucke** [comment]
Can you try again?

![more encodings](https://cloud.githubusercontent.com/assets/5881326/14940937/c725d732-0f8a-11e6-96ad-f4f5e3462b75.PNG)

A full list of codecs can be found here: https://docs.python.org/3/library/codecs.html#standard-encodings

**Comment by YorsLosilla** [comment]
Will this allow us to read particle cache data?


-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎01/‎05/‎2016 0:24
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: Re: [JacquesLucke/animation_nodes] file reader node (#517)

I just implement a first version of a Text File Reader node.
It takes a path as input and outputs the text. Only text files are supported (this also includes .csv etc)
Internally the node does some caching to avoid reloading the file. It also checks the last modification time of the source file so that it can reload when the file changed.

**Comment by JacquesLucke** [comment]
No. particle cache data is most likely no text file.

**Comment by LeonCheung** [comment]
It works now :). However, just one thing odd: When trying to save a utf8 file to ascii file (which will cause some code missing), it still fails to read the new ascii encoded file. Not sure if this is critical.

**Comment by JacquesLucke** [comment]
can you send me an example file?

**Comment by LeonCheung** [comment]
updated.

**Comment by clankill3r** [comment]
Damn I really need to fix internet, I feel so disconnected lately :)
Once again, great work Jacques.

**Comment by JacquesLucke** [comment]
Thanks :)

@LeonCheung: hm the file looks a bit weird.. If I set the encoding to 'big5' it seems to work.

**Comment by YorsLosilla** [comment]
If I create some sort of scrip to retrieve particle position data from cache file and turn them into csv. Will this new node able to read that data and use to create a particle tracer?


-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎01/‎05/‎2016 14:01
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>; "Comment" <comment@noreply.github.com>
Asunto: Re: [JacquesLucke/animation_nodes] file reader node (#517)

No. particle cache data is most likely no text file.

**Comment by JacquesLucke** [comment]
Yes, I think that is possible, but will be slow if you have many particles

**Comment by LeonCheung** [comment]
@JacquesLucke Not just this file I'm afraid.
