### ISSUE TITLE
BS Wishlist for Animation Nodes 

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#599]
- [ ] Bounding Box node ala Sverchok (a quick way to get the pivot, dimensions)
- [x] AN Circle Node
- [x] Selection Masking (kind of like if we are inside the loop but only wanting to process just some parts of it. We could probably use list slice, but.... rather use VG.
- [ ] AN Spiral Node (kind of one that makes snail like spiral, and another one that generates spiral more like stair.
- [x] Emergency Hotkeys to halt the processing, turn off Auto Execution and turn off Always. I have many times experiencing this, and need to close Blender.
- [ ] UV transfer from Source to Target (because sometimes it lost it)
- [ ] Attribute Transfer and Solver node
- [ ] Set Vertex Color that actually works for Polygon Face, not just Object.

**Comment by og76** [comment]
I already made some variants for Circle. Please allow me to propose them first. 
This node seams simple but you'll see that there is way more to it. And a "brother" node...

Point is:
1. I make it as an Arc Creation rather than circle, with options for pie/bow ring poly approach, limits for 360 or more, subdiv per arc or fixed etc etc
2. I would have already proposed the above, but I wanna match the i/o with the ""brother" Arc Tool or Arc Formulas, or Arc From. This finds the appropriate center, radius, start, end from various data, points/lines/circles, the tangent cases. 
Combined they will allow a very user friendly approach in using objects, edges etc as base for creating circle arcs (much like the CAD apps use for entering an arc by 3 points, point and tangent, 2 tangents etc)
3. may seam like complicating, but actually is gonna make the usage way simpler imho.

Now to be clear, this makes the Arc creation node to go a bit over plain xy 2d, to a certain 2,5d or 3d ish approach with a normal or so (as the inputs are not always 2d). Have already 2 algos for this, but was still looking for the right (simple and clear) way to do it.

Issue is that I'm a bit out of time now and stalled this. But I'll ba back..

Thank you.
More if it's not clear ;)

**Comment by og76** [comment]
ps. spiral may be included above or at least derived..


ps2 bbox extra info, we should discuss what is to be included, 
not a big deal todo, but a matter of efficiency of the node
(dimensions of the obj are stored in blender, pivot? the obj location is given elsewhere etc etc)

**Comment by JacquesLucke** [comment]
Maybe we can add "Dimensions" as a output of the Object Transforms Input node.

I agree that the Circle Mesh node can have many different settings. However I'm not sure if they all have to be in the same node. At least it would be possible to have more nodes like Grid Mesh, Line Mesh, Circle Mesh, Cube Mesh, ...
They can have different modes of course. eg Circle can have a triangle fan as polygons or be an ngon.

I'd love to add emergency hotkeys to stop the execution. Unfortunatly this is very very hard. Maybe even impossible, I'm not sure yet. We need some kind of threading for that. 
I experimented multiple times with how "Always" can be turned of automatically when the execution time is too long, but I did not find a satisfying answer so far.

UV transfer isn't easy but should be possible in the future :)

What do you mean with "Solver" node?

**Comment by enzyme69** [comment]
Thanks for looking after this wishlist :8ball: Yes non of them is particularly urgent.

SOLVER node is kind of looping but has the effect of accumulation. Perhaps by any change AN Loop or iteration is kind of already doing it, I just have not explored it much.

Maybe O.G is displaying kind of "solver" behaviour with this simulation example.

But I am thinking a simpler case, for example, I have this idea of "transferring attribute" and "accumulating and caching the effect". I don't know if this involves BVH thing?

Perhaps, I have 1 object that uses the BVH. Then I want to kind of Cache the changes when attribute values got transferred from 0.0 - 1.0, or changing from False to True. 

 A little bit like what Dynamic Paint is doing.

http://www.tokeru.com/cgwiki/?title=Houdini#Point_and_attribute_transfer_with_lag_via_solver_sop

![prtscr capture_24](https://cloud.githubusercontent.com/assets/3952687/17913949/6f9ae078-69e1-11e6-9a03-0296fdcaf1fb.png)

I am going through the Houdini Tokeru Wiki and finding inspirations. Trying to see where Animation Nodes is at. And which node might be interesting to have :)
