### ISSUE TITLE
Append "Interpolation from Curve Mapping" node to a scene doesn't work

### ISSUE THREAD

**Issue by dr-brown** [JacquesLucke/animation_nodes#600]
If I append a node tree to a scene with a "Interpolation from Curve Mapping" node inside, the curve will not be loaded correctly. The curve is the default curve instead of the adjusted.

Blender 2.77
AN 1.6.0

**Comment by JacquesLucke** [comment]
ah damn, good catch. I did not thought about this.
The reason is that the Curve Mapping is actually a hack (the only one of this kind in AN). In reality the node displays the curve mapping of a material node which is in another node tree. (Blender does not support certain things like curve mappings, colorramps, .. in custom nodes yet)

Maybe I'll find a fix for that.. It will make the node even hackier -.-

**Comment by dr-brown** [comment]
A fix would be very nice. In our company several people work on one project with different tasks, so appending (even better would be linking) is essential.

**Comment by JacquesLucke** [comment]
I start to work on it now. May I ask where you work?

**Comment by JacquesLucke** [comment]
I uploaded a fix, can test it please and tell me if it works?
Oh, and you have to save the files again that you want to import.

**Comment by dr-brown** [comment]
In principle it works. With more than one ICM nodes there are however problems. I have two node trees. If I append the first, the related ICM node gets the values of the ICM node from the second node tree.
Node trees from the source file:
![source](https://cloud.githubusercontent.com/assets/4175186/18062974/59150ed6-6e29-11e6-8a53-55068e4bce6d.jpg)
Appended node trees:
![append](https://cloud.githubusercontent.com/assets/4175186/18062987/6aa42c40-6e29-11e6-96a4-88c6c5a54215.jpg)

**Comment by JacquesLucke** [comment]
ok thx! The problem was that these nodes stored the name of the curve mapping node. And sometimes there were duplicates.
Now I changed it so that the real curve mapping nodes get the identifier of the corresponding node as name.
To make this work for you, you'll have to copy the original nodes and only keep the copy. Remove the old one.

**Comment by dr-brown** [comment]
Now it works! 
Thanks for your quick help
