### ISSUE TITLE
[Question] Vectorization Thing similar to Sverchok?

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#604]
Dear AN Devs,

I was from the other room, Sverchok, we are questioning the elegant way or possibilities to "Vectorize" input and output. Kind of like in AN, when we turn bunch of nodes into group.

[https://github.com/nortikin/sverchok/issues/863](url)

Similar to previous question I asked about Array of Array of Array (Circle, being duplicated, each circle has different points, and I would like to instance objects based on points.)

I make the setup below for example:

Logically it should work and I should be getting "variations" or "vectorization" of the "Rays" group, but I didn't. I wonder why.

![prtscr capture_48](https://cloud.githubusercontent.com/assets/3952687/18311506/0b6e0b8a-7548-11e6-91ce-d1aee3270f53.png)
![prtscr capture_47](https://cloud.githubusercontent.com/assets/3952687/18311507/0b70e0da-7548-11e6-9060-0fe7d42551ea.png)

**Comment by enzyme69** [comment]
![prtscr capture_49](https://cloud.githubusercontent.com/assets/3952687/18311824/d7da4034-7549-11e6-8d10-5603e6222de5.png)

Somewhat I figured it out and it is possible... interesting.

**Comment by JacquesLucke** [comment]
Thanks for the link.
In fact im currently facing pretty much the same problem.

I think that the Loops I implemented in AN is the most generic solution to this problem. And for a long time I thought this would be enouph. I could easily "vectorize" some nodes but there were nearly no performance benefits over using a standart loop, it would just make the code more complex.

However, things are changing right now due to Cython. When I vectorize a specific node manually I can get up to 100x better performance now. This is of course more than a good reason to start vectorizing some nodes, even if it means that the code will become more complex.... 

I'm trying to find solutions to this problem that fits into AN for a few weeks now. 

"fits into AN" means in this context that it should not require more new datatypes etc.
AFAIK (and correct me if I'm wrong) in Sverchok there is only one vector socket. The data "in" that socket can be a single vector, a list of vectors, or even a list of a list of a list of vectors....
In AN, I don't want that. I want that the data type is clear by looking at the socket color. If you really need those complex lists you can either use complex lists but in general you should rethink what you are trying to do and find a way to do it with normal lists and Loops.

One of the main problems I'm currently have is how to implement the socket-type-change when the user wants to use the "vectorized" version of the node. The simple solution would be to implement checkboxes for many nodes that allows the user to change the node type for "normal" to "vectorized" or whatever. Personally I don't like this because it is possible that one node has different vectorized versions. (eg. all inputs are lists, or only a few are lists and some are not etc.) Also I don't like that the user has to switch this checkbox manually for each node.

It'd be better if the sockets automatically change. For example we could have the normal Line Mesh node with a `start` and `end` vector input. When the user connects a Vector List to `end` it should automatically create either a Mesh Data List, or only a single Mesh Data object with all generated lines in it. Performance wise this can be very very fast. Again, the main problem is not to write that code, but to write as less code as possible to give as this flexibility while still having good performance.

Another problem is this: How to communicate to the user that a socket is "vectorizable" (that he can plug a list into it although it is eg a normal vector input). 
There are a few options: 
- Change the socket name (eg from `Vector` to `Vector(s)`
- Change the socket transparency (eg. use 0.8 instead of 1 for a single vector input (lists always use 0.5))
- Change the border color of the socket. Note: this is not possible yet, but might be worth to implement it in Blenders Python API. A problem with that is that a light border color does not work with all socket colors. 

If you have more ideas, please share them!

A simple automatic vectorization function as proposed in the Sverchok thread does not work for me because this is basicly the functionality we can emulate with a loop. Also it is too slow when we want to benefit from Cython. And I want to benefit is much as possible from it.

I will not be able to work on AN as of monday for roughly 2 weeks because I'm not at home. I'll use that time to find solutions to as many of these problems as possible. The implementation afterwards should be much easier.

**Comment by enzyme69** [comment]
Thanks for writing a lengthy thinking thought for this situation~

I think as long there is a way around it to make vectorization works, then it is fine with me.

May ask other users opinion as well. Wonder how often really one needs to vectorize or make variations.

When generating mesh in Sverchok, yes I do think vectorization a lot. When in AN, I think of looping and index and seed. The fact that Object Instances cannot go inside the loop, that's one thing I always keep in mind. With Sverchok maybe that's monad thing :) 

Sverchok and Monad and Vectorization is another strange area. I guess AN does not have to work that way.

Changing node color when vectorizing maybe? Or any kind of special indicator.

I remember doing this with Line:
* [0,0,0] > start
* [ bunch of random vectors ] > end
And it gives me result. It assumes all the start is [0,0,0]. That's nice.

Will meditate a bit on this.

**Comment by enzyme69** [comment]
Ok hope you have good break after exam! 2 weeks holiday? When you visit Australia one day, let me know~

**Comment by enzyme69** [comment]
![screen shot 2016-09-10 at 19 21 01](https://cloud.githubusercontent.com/assets/3952687/18409502/e6b128cc-778b-11e6-90c7-fe3df6aaaa4e.png)

Another example, this is just simple worms wiggle.

It works as long I keep thinking to generate Mesh List for Object Instance.

**Comment by JacquesLucke** [comment]
I implemented a basic vectorization system into AN. It allows me to write vectorized sockets more quickly. By vectorized sockets I mean sockets that automatically change there type to List if necessary.

You can see the first tests of this system in this video:
https://www.youtube.com/watch?v=MDkPasOMehY

The *Object ID Key* and *Object Matrix Output* node use it.

**Comment by adamearle** [comment]
Wow this is awesome

Here a  video  about creating custom bevels in blender
https://www.youtube.com/watch?v=S0D8w49OF1c

Would be kool i this could have a faster work flow with animation nodes
something likfe using a levels curve that perhaps drive the curve input of
theh text bevel.

Mutiple text objects can be changed at the same time as well would be
amazing.

Freakn awesome what you have done so far.

Adam Earle

**Comment by enzyme69** [comment]
@JacquesLucke I am still using version 1.6, is this "vectorization" thing is in latest AN? And you are also using falloff stuff 👍 is this already available? Whooaa..

**Comment by enzyme69** [comment]
@adamearle Cheers for that video, I have not explored that area, useful!

**Comment by enzyme69** [comment]
Cannot find anything new in the release note. But waiting in anticipa....tion.

**Comment by enzyme69** [comment]
Will there be indicator for nodes that actually "auto-vectorize". Maybe slot color change?

Currently my workflow is to check the color slot. Transparent use Loop, when Get List Item/Element node suddenly appears.

**Comment by JacquesLucke** [comment]
thanks for the video link. Not sure how to implement this into Animation Nodes, we'll see

Please take a look into the BA thread, I gave some additional information there.
