### ISSUE TITLE
Suggestions for Separate Text Object

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#607]
Three possible new options:
1. Separate by word (quite intuitive, no illustration needed).
2. A few more advanced settings (as those for Object Instancer Node).
3. Generate dummy non-renderable object as sort of placeholder(s) for space, in order to be taken into account in some cases. Illustration:

![demo](https://cloud.githubusercontent.com/assets/494788/18734436/f90f961a-80a6-11e6-969f-00b8259397dd.png)

I know it sounds crazy, just notice that when making DOS typing effect. (for simulating the space typing action, a lot of work needed imho)

Besides, sometimes spaces (even tabs and breaks) are expected as real elements being taken into account in iterated animations (used in a loop, for example).

**Comment by JacquesLucke** [comment]
I'd love to do this but unfortunately it is not very easy due to the way Blenders text object works.. Separating the letters the way it works at the moment is relatively difficult as well. I hope to find a better way to do it at some point.

Instead of filling the object list with Nones, maybe we could also use the new Index ID Key to store the "real location" in the text.

**Comment by LeonCheung** [comment]
Ah, right, the new solution you suggested would be a nice option. Is it going to be a real position or kinda real ID (take spaces into account)?
