### ISSUE TITLE
Render layers 

### ISSUE THREAD

**Issue by adallafontana** [JacquesLucke/animation_nodes#611]
Seem there is not a possibility of use the render layers, I can't find a way to setup layer in the animation node instance.

Thank you.

**Comment by JacquesLucke** [comment]
You're right, we don't have nodes for render layers yet. This is mainly because i did not have the time and never really used render layers myself. I guess eventually we'll have a node for it'll take some more time.

You can only change the layer an object is on using the "Object Layer Visibility Output" node.

**Comment by adallafontana** [comment]
The "Object Layer Visibility Output" node is what I'm looking for.
I have to test it better but seem to works right.
Thank you.
![screenshot from 2016-10-10 16-23-01](https://cloud.githubusercontent.com/assets/8054856/19239581/f926d7c6-8f06-11e6-9d56-6149aabb1926.png)
