### ISSUE TITLE
Run without User Preferences

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#614]
More info: #612

**Comment by evilstreak** [comment]
I hit this issue trying to get headless rendering working using the addon. Here are the changes I needed to make: https://github.com/JacquesLucke/animation_nodes/compare/master...viddyozeapp:factory-startup-command-line-fixes

My approach for default preferences there is a bit of a kludge. My original plan was to instantiate the existing preference wrappers (eg `DeveloperProperties`) and pull out the defaults from there, but I couldn't work out how to instantiate them directly – they seem to be pretty tied to the context Blender creates them in.

If you're interested in merging in code that does this then I can spend some more time working on the way default preferences are handled. My plan would be to define all the defaults in a single data structure that can be returned when necessary and also access from the various Blender properties so that the defaults aren't duplicated.
