### ISSUE TITLE
Cannot uninstall Cython branch

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#616]
Just noticed that it cannot coexist with the current master version. It seems I have to uninstall the previous version first.

Besides, when I tried to uninstall cython branch, it seems that I have to first disable it, then restart blender, then it allows me to uninstall completely.

Win8.1 64bit

**Comment by JacquesLucke** [comment]
Having AN installed multiple times was always a bad idea.. I think that never worked correctly.
So yes, you always have to remove the previous version first.

Unfortunally you're right about uninstalling the cython branch. Not sure if this is fixable. The problem is that Blender loads these compiled modules, but once they are loaded the files cannot be removed. So there are two options: Remove the addon folder manually while Blender is closed, or do what you did.

I'll try to make this process more automatic in the future but maybe it is not possible. However this happens when we want to evolve from a little addon into a something like AN :D

**Comment by LeonCheung** [comment]
Agree, and it is a low priority one I bet.  :)
