### ISSUE TITLE
outputing both the new bmesh and the return value from an operator

### ISSUE THREAD

**Issue by mirlip** [JacquesLucke/animation_nodes#629]
I created a new node that does an inset:

```
import bpy
import bmesh
from ... base_types.node import AnimationNode

class BMeshInsetIndividualNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_BMeshInsetIndividual"
    bl_label = "BMesh Inset Individual"

    def create(self):
        self.inputs.new("an_BMeshSocket", "BMesh", "bm").dataIsModified = True
        self.inputs.new("an_PolygonListSocket", "Faces", "face").value = "bm.faces"
        self.inputs.new("an_FloatSocket", "Thickness", "thick").value = 1.0
        self.inputs.new("an_FloatSocket", "Depth", "dep").value = 1.0
        self.inputs.new("an_BooleanSocket", "use even offset", "even").value = True
        self.inputs.new("an_BooleanSocket", "use interpolate", "interpolate").value = True
        self.inputs.new("an_BooleanSocket", "use relative offset", "relat").value = False
        self.outputs.new("an_BMeshSocket", "BMesh", "bm")
        self.outputs.new("an_PolygonListSocket", "Created Faces", "created")

    def getExecutionCode(self):
        return "created = bmesh.ops.inset_individual(bm, faces=face, thickness=thick, depth=dep, use_even_offset=even, use_interpolate=interpolate, use_relative_offset=relat)"

    def getUsedModules(self):
        return["bmesh"]

```

The bmesh is correctly modified, but the list of faces that are stored in "created" (https://www.blender.org/api/blender_python_api_2_78_release/bmesh.ops.html?highlight=bmesh.ops.inset#bmesh.ops.inset_individual) are not in the node output. The debug node shows that only the string "faces" is outputed. Maybe because of a wrong socket type but I couldn't find a better one. Any help appreciated.

**Comment by JacquesLucke** [comment]
The only thing that looks a little wrong here is the second input, the Polygon List Socket does not accept a list of the type ``BMFace``. I suggest you use ``Generic List`` here again, or alternatively, you could create your own socket type.

Also I don't think that a PolygonListSocket has a property called ``value``. And definitly you cannot assign ``"bm.faces"`` to it.

btw: are you using the latest master version of AN? The method of creating sockets changed a little a few months ago. Instead of 
``self.inputs.new("an_FloatSocket", "Thickness", "thickness").value = 1.0`` 
you should write 
``self.newInput("Float", "Thickness", "thickness", value = 1.0)``.

**Comment by mirlip** [comment]
Hi Jacques,
Thanks for the quick answer. I was not sure if latest master was stable or not. Is it what will become AN1.7? Or is the cython branch the future 1.7?
If master is stable (from a coding point of view), I'll happily work on it :)

**Comment by JacquesLucke** [comment]
the master branch is always the stable branch you should use in production etc. The cython branch is my development branch, all the changes in it will be merged into master in a few months (once it all is stable, ..).

In general it is totally up to you in which branch you develop, the node API is mainly the same.
