### ISSUE TITLE
Limits for Subprogram Inputs

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#633]

**Comment by LeonCheung** [comment]
Thanks for open this . :)
Just a quick note about how I think it can help regarding performance:

![get list element](https://cloud.githubusercontent.com/assets/494788/19952955/158f6d06-a1a4-11e6-99c8-abe0ec611a21.png)

For example, in the setup above, I want to switch among diffrerent subprograms in this way. So no doubt that it would be reasonable that only one of them should execute per time, instead of all of them.

**Comment by JacquesLucke** [comment]
I think you posted this into a wrong Issue. However, I know what you mean.

**Comment by LeonCheung** [comment]
Oops!! seems I did... Sorry about that.  :p
