### ISSUE TITLE
Request: Polygon Islands Outputs for Object Mesh Data node

### ISSUE THREAD

**Issue by saigadot** [JacquesLucke/animation_nodes#643]
It would be helpful if we could operate on polygon islands the way we can individual polygons, as displayed in the latter half of this video: [Cube Ocean and Polygon Effects - Animation Nodes Addon for Blender](https://www.youtube.com/watch?v=19wRsmBIVBQ)

**Comment by JacquesLucke** [comment]
I know... I guess it will be possible at some point but some more stuff has to happen before that.

Eventually I'll have to implement another data type for meshes (maybe called AniMesh or something like this^^) . It will not replace "Mesh Data" and "BMesh" but will make certain types of things easier. You might ask, why yet another data type. The reason is simple, different data types make everything more performant because the algorithms can be more specialised. This new data type should also be able to store colors/weights/normals/... per polygon/vertex/..
I'm not sure yet which data structure will be best for that, I'll have to talk with some others about it to make a good decision.
