### ISSUE TITLE
Implemented the addon updating module

### ISSUE THREAD

**Issue by TheDuckCow** [JacquesLucke/animation_nodes#658]
Implemented the addon updater code [hosted by CGCookie](https://github.com/CGCookie/blender-addon-updater). This module allows the addon to check for updates and directly install them all within blender's interface, utilizing the github api. It also allows the user to install different versions of the addon, and automatically check for updates after an interval if desired (this feature not added with this commit, see comments below).

## Changes/implementation notes
Standard implementation followed [this tutorial process](http://theduckcow.com/2016/addon-updater-tutorial/). Some notes deviating from those steps:

- This addon uses a structure of registering all it's modules in a subfile. Currently registration of the updater happens in the __init__ file, to pass it to update in the `register_files.py` file, the bl_info param would need to be passed in accordingly. Tested and works.
- This implementation does _not_ add in a UI alert to any panels, which is the optional step 8 of the above tutorial. This could be added to any appropriate panel, but without this the auto-check for update code will never be triggered even if enabled in the UI (users would then only be able to explicitly press check for update to see status; likewise installing updates could only be done through the user preferences window).
- If this is actually to be included as a part of the animation nodes addon moving forward, it would be important to set the minimum version install to the current version at that time (ie 1.6.1 or higher)

## [See the implemented code on this fork](https://github.com/TheDuckCow/animation_nodes). If requested, I can make any modifications and submit a pull request

[See direct commit with changes](https://github.com/TheDuckCow/animation_nodes/commit/c27fba4d564e8f364567c2c7b89a4805652e6d1a) from master on the original fork.

**Comment by JacquesLucke** [comment]
Hey, thanks for your effort! Unfortunately I decided to not include this into the addon.

The main reason is that I don't believe that this is very future proof. Adding over 2000 lines of code for "simple" behavior like this should not be done in each addon. Instead I'll wait until someone (maybe me) develops an addon manager as a standalone addon. This would reduce code duplication accross many addons. As you know, duplicated code is always bad. 
I don't want that update-code is nested with all the other stuff. Also my guess is that until someone develops a standalone addon manager there won't be very much AN release. At least not enouph that it makes this addition really useful.
Furthermore I don't know yet how the addon will be distributed after the next release because I will have different versions for different operating systems.
Also the addon-deletion code has to be able to work without having Blender running (not sure if your code supports that already). The reason is that compiled Cython files can't be deleted while they are loaded in Blender (also they cannot be unloaded).

So in general I think your code is very useful for many addons but not for this one..
Thanks again.

**Comment by TheDuckCow** [comment]
I completely understand your stance. I specifically took the 5 minutes to do the integration just because I noted I had an outdated version and I wanted to play with it more :)

You are right that an overall addon manager would be ideal and a better solution, but with past and failed-to-be-adopted attempts, I worked with CGCookie to create this py module to be at least an intermediate solution until a more community wide implementation is supported. 

No harmed feelings for not including, your rationale makes sense. Perhaps at most the use could be for at least notifying users of an update without the one-click install, but this even also depends on your future release methodology. 

Cheers!

Patrick W. Crawford
Moo-Ack! Productions
www.TheDuckCow.com
youtube, twitter, facebook

**Comment by JacquesLucke** [comment]
Yes, too bad that the package manager project for GSOC was no success last year.. I thought about taking part myself but I currently prefer on my own stuff. And also because I did not know very much about networks etc at that point. Now I'm just finishing a module about it in university, so that gives me a good base. Furthermore I plan to add a little plugin manager into Animation Nodes itself. Maybe I'm capable of writing a general addon manager for Blender afterwards. We'll see.

I've read your comment on Blendernations; cool that you started trying out Animation Nodes ;D

**Comment by TheDuckCow** [comment]
Go for it! In addition to the GSOC, I would encourage you to also look at a previous attempt of putting it together - https://github.com/KoltesDigital/blender-addon-registry

I think the key piece that it lacked was A) community momentum behind it and B) no central line into the blender foundation or otherwise to manage it and keep it up to date, plus an over customized server side implementation (the registry listing). But tech wise, as is, it does a good job and has the networking down and a decent user experience workflow. 

Closing the issue for now, thanks for looking into it and loooking forward to whatever you put together next
