### ISSUE TITLE
Feature request: Interpolation chains

### ISSUE THREAD

**Issue by scorpion451** [JacquesLucke/animation_nodes#678]
It's a simple idea that's a little to describe:
I frequently find myself wanting to be able to combine series of interpolations into a single interpolation. 
Not mixed together like the mix interpolation node, but one after the other in a sequence.

A good example is the interpolation I made for a "ticking clockwork" type movement: it started with a back interpolation for the swing, and ended in an elastic interpolation for the sudden stop. I had to make this by hand using a curve-defined interpolation node, but it would have been a lot easier if I could have just chained together a back interpolation and an elastic node, and adjusted their start and stop values so they matched up in the right way.

**Comment by JacquesLucke** [comment]
Does not sound like a bad idea. Not too easy to match them up exactly though. Can you show me how the interpolation you describe looks like visually? (just to make sure that we are on the same page).

**Comment by scorpion451** [comment]
No problem, looks like this:
![ticking with notes](https://cloud.githubusercontent.com/assets/11708455/24519244/29b46772-154a-11e7-92f0-e70fd41225c5.PNG)
another important type of interpolation that this would make a lot easier to put together is the classic "whip cycle": an interpolation that starts and ends at the same place, with some waveform action in between.
![whip](https://cloud.githubusercontent.com/assets/11708455/24524202/540c30e8-155b-11e7-9705-90c1fa3758d3.gif)
![whip loop](https://cloud.githubusercontent.com/assets/11708455/24524462/39a0ac88-155c-11e7-9287-4e52eebade8f.PNG)
![chain breakdown](https://cloud.githubusercontent.com/assets/11708455/24524739/53097ac8-155d-11e7-9a7c-67263b40c626.PNG)

It's no so bad creating them manually when they're simple like this one, but when you start getting into complicated whips- say, motions involved in a walk cycle- it'd save a lot of time I currently spend poking at little dots.

**Comment by JacquesLucke** [comment]
Thanks for the images, that makes it clearer.
I think I will be able to extend the Mix Interpolations node so that it can do this as well.

I also already implemented a Mirror Interpolation node in the development branch.

![mirror interpolation](https://cloud.githubusercontent.com/assets/5881326/24525969/ac6a0e36-159c-11e7-9ab5-46fb9f5c67e7.PNG)

**Comment by JacquesLucke** [comment]
The Mix Interpolation node has a new mode now that should do what you want. Unfortunately it is not entirely easy to chain interpolations so that it looks good, but with a bit of trial and error you should be able to get the result you are looking for. One thing that I might have to improve in the future is a better smooth fade between the end of the first and the start of the second interpolation. 

![chain interpolations](https://cloud.githubusercontent.com/assets/5881326/24588005/95b3c2ce-17c0-11e7-9654-1df60ffef9c8.PNG)
