### ISSUE TITLE
Feature request: Group instancer and Group Transforms Output

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#679]
The idea is to have a more easy way to handle group of objects. This functionality can be achieved with loops and matrices but like offset this will give a more seamless way to handle and animate groups of objects and build real complex animations more easily.

**Comment by JacquesLucke** [comment]
Are you really talking about object groups or are object lists ok as well?

In the new version I already vectorized the Object Transforms Output node, so that you can easily set eg 100 objects to 100 different locations without a loop.
Doing the same thing with the instancer is much more difficult unfortunately. I don't really want to make this node more complicated, maybe we should have an extra node for this.

**Comment by YorsLosilla** [comment]
Objects groups. For examples rigs of objects that are group. You can have an animation for those objects inside that group, but in a lot of cases you may also want to sequentiate animations between sets of objects. I´ll post you an example of this type of animation which is pretty common. Wait for the renderfarm

**Comment by YorsLosilla** [comment]
This could serve as example: 

https://drive.google.com/open?id=0B9SDRZRP7NzVV1Q2cmoycnFva00

**Comment by JacquesLucke** [comment]
I understand what you mean. Can be useful indeed. I don't really have a good idea how to implement it atm. I guess we will get functionality like this at some point but not in the next release..

**Comment by enzyme69** [comment]
For now, I reckon just bake out the animation mesh totally and then use Alembic and AN to randomize the frame numbers.
