### ISSUE TITLE
Multiple Vectors for Offset Matrices

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#685]
Checking Cython branch now and looking into this video tutorial:
"Playing with Falloffs and ID Keys in Animation Nodes (work in progress)"
https://www.youtube.com/watch?v=s4wcSW-e_Pg

Jacques, can I actually plug Multiple Vectors data into Offset Matrices?

![screen shot 2017-04-12 at 19 27 14](https://cloud.githubusercontent.com/assets/3952687/24950977/30ce38be-1fb6-11e7-931c-56c0c370d25a.png)

**Comment by LeonCheung** [comment]
Yes, we can.

**Comment by LeonCheung** [comment]
Hmm, for the purpose shown by your image, I think you should use Random Euler instead?

**Comment by enzyme69** [comment]
![skeleton_rotate_reveal_001](https://cloud.githubusercontent.com/assets/3952687/24998911/0438be90-207f-11e7-84ec-e0d34dcf78e2.gif)

@LeonCheung Thanks man~ Seems to work although some skeleton seems to be showing the same rotation... 

Solution is like this?
![screen shot 2017-04-13 at 19 26 21](https://cloud.githubusercontent.com/assets/3952687/24998948/1b7ca9d6-207f-11e7-9a26-3cac5e7cde3b.png)

**Comment by LeonCheung** [comment]
Hmm, not sure what version you are using, but my Random Euler node will output list while the list button activated, thus I bet you won't need an extra loop, since you've already get a list with randomized eulers by activating that button, yes?
![a](https://cloud.githubusercontent.com/assets/494788/25000196/fe091ff8-2072-11e7-8661-6df81b06603e.png)
