### ISSUE TITLE
[Discussion] Should we always enable "Always"?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#704]
It turns that I have to disable "Always" eventually while the tree complexity grows and more targets involved. Not sure if others experience that often.

For majority of cases, IMHO it should be fairly enough to disable "Always" while enabling the other three buttons bellow it by default.

Of course, if this is considerable, updates for changes on mesh/spline/hair/f-curve/text blocks etc should be done somehow someway. Currently it can be manually done by re-enabling Always, clicking Execute Node Tree button, and change frame#, etc (Yeah, new result will eventually be previewed by playing animation, so it doesn't really matter here). Just wonder if there can be a possible automatic solution for that, for example, by monitoring any changes over the active Editor, or any changes on the active object (mesh, modifier, f-curve, particle etc), which means there could be a new type of "Something Changed" monitor to enable?

On the other hand, a nice CPU cooler would be needed ortherwise.  :laughing:  Believe it or not, summer is coming! You know what it means. :icecream:

**Comment by JacquesLucke** [comment]
I would do this if it were possible. Unfortunately it is impossible to monitor the whole scene without an extreme overhead.

Personally I always start with "Always" being on and turn it off once things get slow.

I think it is relatively important that as a beginner you can just take an Object Transforms Input node and view the location output change when the object moves in the 3D viewport. This would not be possible otherwise.

I was also thinking about the possibility that the user can set the default auto execution settings in the user preferences. But I'm not sure how to implement this nicely. I guess that would be the best solution.

**Comment by JacquesLucke** [comment]
Also check this link: https://developer.blender.org/T47811
The first point under "Open Topics" is kind of important for us.

**Comment by LeonCheung** [comment]
I see, no problem then.
