### ISSUE TITLE
[2.0 beta] Wrapping fails in Viewer

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#710]
Not critical for sure, just wonder why it occurs when dealing with CJK characters.

![wrap](https://cloud.githubusercontent.com/assets/494788/26136839/dd9c1462-3af0-11e7-8b2d-3cc5b6935fe2.png)

**Comment by JacquesLucke** [comment]
It would be good if you could send me a file whenever the problems are related to non latin characters.

**Comment by LeonCheung** [comment]
OK, try [this file](http://pasteall.org/blend/index.php?id=46639), be sure to toggle **International Fonts** in User Preferences setting.

**Comment by JacquesLucke** [comment]
The problem here is that I intentionally choose a monospace font in the viewer so that I don't have to calculate the with of every character all the time. Unfortunately those characters still have a different size.

It will take some more time to fix this, so I won't do this now. I'll leave this issue open though.
