### ISSUE TITLE
[Idea] Debug ID Keys in 3D View

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#713]
Basically I mean the Index, you know,to debug /view /display in 3D view. Curently there seems to be little way to do it for multiple objects, maybe it can be useful to implement?

**Comment by LeonCheung** [comment]
Or it can be extended to allow displaying any other per-object properties there?

**Comment by JacquesLucke** [comment]
Well I don't really want to display the ID keys for all selected objects im the panel because that would not scale very well with many objects. A better approach would be to display the id keys directly in the viewport -> There can be a small number next to every selected object that shows the index.

Not sure if you described the same thing in your first post... Anyway, I think that is a good idea.

**Comment by LeonCheung** [comment]
Yes, that is what I meant, in the viewport, as the title said. :)
