### ISSUE TITLE
Suggestion: Number List Math (Extended)

### ISSUE THREAD

**Issue by Waffle-SS** [JacquesLucke/animation_nodes#715]
Although a list math node already exists, its rather limited and rarely useful for actual list math because it only does single number output operations, such as Min, Max, Avg, etc.

What would really be useful for lists is having the ability to perform **math operations per element**: outputting an altered list. For example, multiplying every element in the list by a number, or multiplying two lists together.

This could be useful for manipulating things such as polygon indices, which can be converted to integer lists. Currently a custom loop is required to achieve this affect for each individual operation.

**Comment by JacquesLucke** [comment]
In the AN v2.0 beta version you can get from graphicall.org  you can do exactly this using thr normal math node. I think you will love it :D 
Besides that the Create Polygon Indices node has been improved as well.

**Comment by Waffle-SS** [comment]
@JacquesLucke Thanks, works just as expected! What's the general timeline for moving down to stable build?

**Comment by JacquesLucke** [comment]
I don't really know.. All big changes are done. Mostly some small improvements here and there are needed. Unfortunately I have not that much time atm due to university and other things.
Maybe I'll align the release with the release of Blender 2.79 so that I can make sure that they work well together.
