### ISSUE TITLE
Automatically insert Get List Element node?

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#728]
I was thinking about if the automatic Get List Element node insertion is actually a good thing. I found it annoying sometimes and I think often it is not what you actually want. Automatic node insertion should only happen if we are fairly confident that this is what the user really wants.

My suggestion is to remove this automatic insertion but I wanted to get some feedback on this first.

**Comment by LeonCheung** [comment]
Do you mean it is not easy to make it smart enough to get what user really wants? Or could you give an example on the pain?

**Comment by JacquesLucke** [comment]
I think most of the time someone connects a list to a single element socket now is to check whether it is vectorized or not. Or he does not know what he is doing, making it even more confusing.

Having a Get List Element node is just not what you want in most cases. That is my experience at least.

**Comment by LeonCheung** [comment]
To be honest I'm not so sure about that, since to me I used to check the "vectorizablility" by simply taking a closer look at the socket transparency. But since a thorough vectorization is on the way, I agree that it indeed lead to some confusion. 

But I do think it's kinda pity to give up such a time-saving feature somehow. Not sure if we can think of any workrounds here to keep both happy. Just wonder if it is possible to deal with combo key action, e.g. to keep it working by holding Alt key while linking or something. Otherwise, grant it a mercy killing.  :)

**Comment by JacquesLucke** [comment]
Unfortunately, afaik, there is no way to know if any key is pressed while inserting a link.

I think the thought "now I want to continue with only one element although I have a list" should be explicitly made by the user before using a Get List Element node.

I'll remove it for now. If you have any other idea on how we can get the best from both worlds, let me know.
