### ISSUE TITLE
Python3.6.2 compile AN?

### ISSUE THREAD

**Issue by Dragon-Bytes** [JacquesLucke/animation_nodes#748]
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
error: command 'gcc' failed with exit status 1

Fedora 26 ships default 3.6.2

Edit: i have tried these commands

sudo -H pip3 install cython
unzip -d . ~/Downloads/animation_nodes-2.0.zip
cd animation_nodes-2.0
python3 setup.py --nocopy --export --noversioncheck

But it ends with this two lines above is it succesful ? i have no experience in code

Cheers

![terminal](https://user-images.githubusercontent.com/29342448/28587458-8e376206-7177-11e7-8c47-ff331a7b9f4b.png)

**Comment by JacquesLucke** [comment]
Can you check which python version your blender build uses?
In general Blender 2.78/79 should use Python 3.5, but that is not always the case. If Blender uses python 3.5 you should setup an environment for that.
I personally use anaconda, because it makes it very easy. There are other ways as well but I can't really help you with these.
Checkout the windows guide, it should help to compile AN on linux as well: http://animation-nodes-manual.readthedocs.io/en/latest/dev_guide/setup/windows.html

**Comment by Dragon-Bytes** [comment]
3.6.2, I have installed and set up anaconda all gone fine however after i install this zip its still having same issues but little different, Anyways i'm going to do something else than 3D modding not decided yet what ,Sorry for waste of time. Have a great day 👍
