### ISSUE TITLE
Q / How to perfectly loop a wiggle?

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#754]
I have been having this question for quite a while, but finding no answer.

Basically I wanted to have a nice smooth looping motion. With Wiggle, one can easily have a nice somewhat natural motion object. However, I have issue making it looping.

Looping in a way that is not like Bounce or popping.

A --> B --> C ---> back to A at some point, but somewhat nicely transitioning.

In Sverchok, I usually cheat like this: Circle Points (already looping shape) + Noise actually gives a looping result, if I just simply go through the value in the list.

How about Animation Nodes? And especially with Wiggle?

I know one trick at some point, kind of a way to loop things like Fire motion or Flag that is drive by noise.

Supposedly if we have 2 noise values that is not looping, we can somewhat do this:
A - > B
B -> A 
------- +
--- X ---

Blended and mix together so that there is a common value that can be looked in the middle.

Is there a simple way to do this?

**Comment by enzyme69** [comment]
![screen shot 2017-07-31 at 19 57 06](https://user-images.githubusercontent.com/3952687/28772734-6e046cd8-762a-11e7-9e7c-dcbf052b75b2.png)

Maybe if Animation Nodes has some kind of Noise node...? Jacques said that Wiggle is like a noise...

**Comment by JacquesLucke** [comment]
Unfortunately there is currently no simpler way to do this afaik.
Wiggle has the special property that it does not repeat :D I might try to make it easier to make it loop in the future.

You are right. The wiggle node uses 1D perlin noise in the background. The problem is that it is 1D that makes it harder too loop.
However I'm already planning to implement [this](https://github.com/Auburns/FastNoise) or the corresponding [SIMD](https://github.com/Auburns/FastNoiseSIMD) noise library in AN. Not sure yet if that will work out well but I think so. With this it will be much easier to create more noise patterns, also looping using the strategy you just showed will become in reach in AN,

**Comment by enzyme69** [comment]
Gotcha! Ok in the meantime I pass data from SV to AN and bake. Cheers!
