### ISSUE TITLE
Node Color

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#805]
How do I change the colour of a node in the node's .py file?

Herewith a screenshot of the .py file:

![screen shot 2017-10-16 at 20 20 29](https://user-images.githubusercontent.com/29657804/31630774-8fed2c9c-b2af-11e7-9025-33b937e12dbc.png)

I want the color to change when the required file has been selected...

The python manual says to use .color( ) but this does not work.

**Comment by JacquesLucke** [comment]
well AN assigns colors to every itself so, I suggest not to work against that. Otherwise people might confuse your node with a subprogram.

If you really want to give your node a custom color you have to first set `useNetworkColor` to false and then assign your color to the `color` attribute.

Is your code uploaded somewhere?

**Comment by Clockmender** [comment]
It's not uploaded anywhere yet, I am not sure it is ready to be released...

I have just mailed you the .py file.

**Comment by JacquesLucke** [comment]
Well uploading it does not mean to release it. It might just be interesting for other interested people to see your progress even if it is not yet finished. e.g. I always upload my wip code for AN in separate branches.

Didn't get the mail yet, guess it will arrive soon :)

**Comment by Clockmender** [comment]
I have uploaded it here - not sure if this is the right place, I am very new here!

https://github.com/Clockmender/animation_nodes

I should appreciate some feedback from anyone willing to look at it.
