### ISSUE TITLE
Blender 2.79 does not recognize AN 2.0 whatsoever

### ISSUE THREAD

**Issue by lucassel** [JacquesLucke/animation_nodes#827]
Hey,

Double checked every little thing I could possibly think of but I'm stuck: Blender will not recognize Animation Nodes, even though it installed correctly to my C:/User/AppData/etc. folder. Using 2.79 official build and the main branch from this github repo. 

Any idea somebody?

**Comment by Clockmender** [comment]
Post a screen shot like this one:

![screen shot 2017-11-16 at 21 40 33](https://user-images.githubusercontent.com/29657804/32917366-d772b486-cb16-11e7-8efe-98f6fd4194b4.png)

I need to see if you have a blank node tree option. How did you install AN - did you get your AN from here:

https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0

If not then it won't work. Load AN from the User Prefs => Addons tab and select the zip file you downloaded from the link above - just copying the nodes from the master branch will NOT work.

See this:

![screen shot 2017-11-16 at 21 44 08](https://user-images.githubusercontent.com/29657804/32917512-55027ddc-cb17-11e7-851a-5826fbbae2bf.png)

If you did all this properly, you need to give us MUCH more info otherwise we just guess.

Cheers, Clock.

**Comment by Clockmender** [comment]
Oh yes, and read this:

http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html

**Comment by lucassel** [comment]
Hey Clock! Thanks for the speedy answer. No, there is no mention of Animation Nodes in my Node editor, nor the Addon tab in my user preferences. After selecting the official .zip, my addon list does not update i.e. there is no mention of Animation Nodes, even though the files are copied to the correct directory (AppData/Roaming/Blender Foundation/2.79/scripts/).

![no animation nodes](https://user-images.githubusercontent.com/3310778/32953994-230d4dc0-cbb2-11e7-8c02-1f5f04bd94d5.PNG)

![directory](https://user-images.githubusercontent.com/3310778/32954008-292fa676-cbb2-11e7-97e7-60a2efb535e5.PNG)


I have installed Animation Nodes quite a few times so I am really stumped at this.

**Comment by Clockmender** [comment]
Your directory for AN should be ..../scripts/addons/animation_nodes

You need to remove that directory in total, with Bender shut down, then download the zip file for windows as I said above then go to User Prefs and install from that zip file.

The give-away is the directory name you have, it's not right.

**Comment by lucassel** [comment]
Hey Clockmender. It is though. If you check out my second screen? I did as you instructed, only to be greeted with exactly the same malfunction :/ even removing all of blender, downloading 2.78 does not work. At the same time, on my laptop it just works...

**Comment by cyaoeu** [comment]
You can also open the Blender console (Window - Toggle System Console) and see if you've got any errors related to AN.

**Comment by lucassel** [comment]
Problem fixed. Master branch was not working for some reason, dunno what changed these last days but runs flawlessly now :) thanks Jaques for this amazing piece of work!

**Comment by JacquesLucke** [comment]
Great!

The master branch is not supposed to work. Instead you had to download the release from the release page. You did that already now. :)
