### ISSUE TITLE
[Feature request] Fuzzy search for ctrl+a (like normal Blender spacebar search)

### ISSUE THREAD

**Issue by cyaoeu** [JacquesLucke/animation_nodes#828]
It would be nice if AN had a fuzzy search like the normal Blender spacebar search so if you for example type "ob tr" the object transform nodes were shown even though "object" wasn't spelled out. Now when you add a space the search stops if no valid nodes were found for what was typed (like "ob") instead of just keeping the results and refining them more and more with each search term. If that makes sense.

The Blender commit to add this to Blender itself is this: https://developer.blender.org/rB80a7efdc1d395f44a14e7bf1085a5d1b3fe45547 No idea if this actually helps though.

**Comment by JacquesLucke** [comment]
I'd love to have a bettee fuzzy search in AN. Unfortunately I don't have control about that. Blender manages everything in the search box.

I even thought about implementing my own search but that turned out to be a bit overkill.

I guess that we will get the behavior of the spacebar search at some point.
