### ISSUE TITLE
Why does Rotation-Wiggle node not have 'list option' ?

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#855]
Hi,
Vector-Wiggle node has list option but Number-Wiggle and Rotation-Wiggle nodes don't have list option, why?

![rot_wig_list](https://user-images.githubusercontent.com/30294746/35236727-4ba0c1c2-ffce-11e7-9a1b-5895c7c45717.png)

[rot_wig_list.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1653082/rot_wig_list.blend.zip)

**Comment by Singh-KS** [comment]
OK. Yes, I'm using the loop for the Rotation-Wiggle list. 

Another query is:- In a group node, is there a way that I can make a "New Input" connection in between the previous exiting connections (see the attached image). Because for a large number of inputs (say ~100), it takes a lot of time to move a particular newly created connection from bottom to top. 
Is it possible to just drag them up or down in the property window (Ctrl+N)? 

Thank You :) 

![screenshot](https://user-images.githubusercontent.com/30294746/35345736-612d8c94-0156-11e8-957e-ca4cc1d4cc1e.png)

**Comment by JacquesLucke** [comment]
unfortunately that is not possible, sry.
Currently there is no better way than to move the socket up manually..

**Comment by Singh-KS** [comment]
OK. Thanks, Jacques :)

**Comment by mattdw** [comment]
(Just noting that Quaternion Wiggle is also not listified yet.)

**Comment by OmarEmaraDev** [comment]
Added in cef7e33.
