### ISSUE TITLE
Text Object Output node has no Material input

### ISSUE THREAD

**Issue by davidgilson** [JacquesLucke/animation_nodes#861]
I am using Animation Nodes to manage large numbers of text objects and noticed that the Text Object Output node has no input to set an object's materials.

I don't know how much demand there would be for this but I would find it useful (please!).

**Comment by Clockmender** [comment]
You can do this easily to **any** object with a simple script node, my project:

![screen shot 2018-02-09 at 16 17 13](https://user-images.githubusercontent.com/29657804/36037451-baddfb88-0db4-11e8-8e9e-87da30494d43.png)

You can see the node tree, I have set the script to run on a list of objects, you could make this just single objects by using an Object-in socket rather than an Object List-in socket. Then just take the "for" loop out of the script. You will see the Expression node that uses the expression "bpy.data.materials" to return a list of all the materials in the project. The script below:

```
for ob in obs:
    if len(ob.material_slots) < 1:
        ob.data.materials.append(mat)
    else:
        ob.material_slots[0].material = mat
```

Adds a new material if the object has no materials, else it changes the first material to the one chosen in the "Get List Element" node. Simple, effective and works like a dream for any object. The input socket for the material on the script node is a Generic socket BTW.

Cheers, Clock.

Blend File:
[materials.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1711677/materials.blend.zip)

**Comment by davidgilson** [comment]
That's brilliant, thank you. That would also help with some Cycles settings I usually disable for text objects too!

**Comment by Clockmender** [comment]
You’re welcome. I am working on a material output node that will switch material according to a trigger and at a particular slot. So you can change the material in any of the slots when a trigger event occurs, like a frame range is met, or a music volume is reached, or a MIDI event occurs, etc. I hope to have this on my github soon.

Cheers, Clock.

**Comment by Clockmender** [comment]
OK, so here we go:

![screen shot 2018-02-12 at 17 07 31](https://user-images.githubusercontent.com/29657804/36109657-f1770e9a-1017-11e8-8997-7ecdc02a0f73.png)

This node tree changes the colour of the front left face (Material slot 2) after frame 50 thus:

![screen shot 2018-02-12 at 17 09 10](https://user-images.githubusercontent.com/29657804/36109679-00c6a5d6-1018-11e8-98f2-887cf71251a3.png)

The Materials Output Node can set a material to an object's material slot number, or replace a material with another if the "Input" value exceeds the "Trip" value, etc., etc. The node on the left gets all materials from the project that fit the search criteria - all if nothing specified, or material name starts with the value in the search field. Once I have debugged it properly I will upload the nodes to my GitHub.

Cheers, Clock.

**Comment by Clockmender** [comment]
Same thing for a list of Objects using a loop sub-programme:

![screen shot 2018-02-12 at 19 32 03](https://user-images.githubusercontent.com/29657804/36115621-86f37e28-102b-11e8-9329-4ae778292bc7.png)

These two nodes are now on my gitHub (https://github.com/Clockmender/My-AN-Nodes)

Cheers, Clock.

**Comment by Clockmender** [comment]
David, I have uploaded revised nodes to my GitHub, if these satisfy your requirements, you should close this thread please.

Cheers, Clock.

**Comment by davidgilson** [comment]
Hi Clock,
Before I try yours, I meant to ask you, how much would it conflict with standard Animation Nodes, and if Animation Nodes gets upgraded, will it break your stuff?

**Comment by Clockmender** [comment]
You need AN loaded, my nodes just add more nodes to the set. It’s all in the readme...

Cheers, Clock
