### ISSUE TITLE
Copy of node setup gives different results

### ISSUE THREAD

**Issue by fomaamof** [JacquesLucke/animation_nodes#879]
![filter](https://user-images.githubusercontent.com/33872502/37554487-ffc42470-29d9-11e8-9ddc-874c31a2d10e.png)
1. Make node setup to filter one list with other. (it doesn't matter if it can be done better)
2. Copy all nodes
3. Make new tree
4. Paste nodes
5. Choose proper copies of group and loop invokes
6. Reconnect lost connections
Now I have copy of previous setup giving switched output.

I think that computer shouldn't do that.

**Comment by JacquesLucke** [comment]
agreed, it should not do that :D
can you try to remove and recreate the Invoke Subprogram nodes?

**Comment by fomaamof** [comment]
Thanks. :-) I did it... but after few hours of looking for mistakes in my tree, which is much more complicated than this example. 
I wanted to make copy of some setups to test different versions, now i know that copying can be a trap. 

If I can make suggestions - it might have more tools to manage lists and arrays of datas - like grasshopper for rhino for example.

and... AN is wondrefull. I love working with it. Thank You.

**Comment by JacquesLucke** [comment]
Yes, unfortunately copying is relatively hard to handle in the AN source code. Also because the callbacks Blender provides are not always the once I'd need to make it work better.

Did you try Sverchok? It has much more list operations afaik. I decided not to make AN more complex by introducing lists of lists etc.

Glad you like it :)
