### ISSUE TITLE
Linux - version 2.1 builds with dynamic linking to libpython3.5m.so

### ISSUE THREAD

**Issue by sorinv** [JacquesLucke/animation_nodes#917]
In this case, even if we have Blender installed with full python support, because the binaries are built against the dynamic library instead of static, AN will fail to run on systems that don't have python installed.

I see no reason to install python as well when it's already present in Blender. Version 2.0 does not have this dependency and works well on systems without Python installed.

Would it be possible to build the 2.1 version against the static libraries instead? 

Thanks,
Sorin

**Comment by JacquesLucke** [comment]
Hey, the main reason the v2.1 linux builds use dynamic linking is that they were done by me and not @jasperges. I just did not setup my build environment on linux yet so that it uses a static python library.

For more details read this: https://github.com/JacquesLucke/animation_nodes/issues/729
Maybe you can try to compile AN yourself for now.

So yes, it is possible to build AN against a static python library, I just did not manage to do it yet (it wasn't high on my priority list for test builds). 

Let me know if you have more questions.
