### ISSUE TITLE
"Set Vertex Color Node" of AN2.1 does not work in Blender 2.79 (Latest Build)

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#998]
Hi...
Set Vertex Color Node of AN2.1 does not work in blender 2.79 (latest build). Here is the screenshot of blender and terminal: 
![screenshot from 2019-01-11 00-18-06](https://user-images.githubusercontent.com/30294746/50995325-ce067580-1544-11e9-9812-8efcdd0345d4.png)

![screenshot from 2019-01-11 00-18-22](https://user-images.githubusercontent.com/30294746/50995337-d78fdd80-1544-11e9-8f40-fb0de2d5c768.png)

**Comment by OmarSquircleArt** [comment]
Hmmm, are they changing the API for 2.79 as well?
Can you replace the `/home/ks/.config/blender/2.79/scripts/addons/animation_nodes/nodes/color/set_vertex_color.py` file with [this file](https://raw.githubusercontent.com/JacquesLucke/animation_nodes/blender2.8/animation_nodes/nodes/color/set_vertex_color.py) and see if it works?

**Comment by 3DSingh** [comment]
@OmarSquircleArt It does not work and shows this error on terminal:

![screenshot from 2019-01-11 12-25-55](https://user-images.githubusercontent.com/30294746/51018069-4b110980-159c-11e9-9fcd-58ad682d2c7e.png)

I think this node is not working due to color input which is only RGB. However, the latest blender build, vertex color takes RGBA. In the original file 'set_vertex_color.py' if I change the **line 38**,
`newColor = tuple(min(max(int(x * 255) / 255, 0), 1) for x in color[:3])`
 to
 `newColor = tuple(min(max(int(x * 255) / 255, 0), 1) for x in color[:4])`
then it does not show error message but the _node does not change the vertex color_.

**Comment by OmarSquircleArt** [comment]
Yes, that's what the new file fixes. In the new file, replace the `:` with `=` in the following two lines:

```
vertexColorName: StringProperty(name = "Vertex Color Group", default = "Col", update = propertyChanged)
checkIfColorIsSet: BoolProperty(default = True)
```
Does this work?

**Comment by 3DSingh** [comment]
It did not work and showed this error message on terminal:

![51018069-4b110980-159c-11e9-9fcd-58ad682d2c7e](https://user-images.githubusercontent.com/30294746/51023794-c333fb00-15ad-11e9-8c87-c8078f4cd672.png)

**Comment by 3DSingh** [comment]
@OmarSquircleArt Thanks. It is working :)

**Comment by OmarSquircleArt** [comment]
@3DSingh That's good to hear.
@JacquesLucke What should we do about this?
